version: "2"
run:
  tests: true
linters:
  enable:
    - durationcheck
    - gosec
    - misspell
    - revive
    - unconvert
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
    paths:
      - docs
      - internal/database/sqlc
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
