// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const addStaffRole = `-- name: AddStaffRole :exec
INSERT INTO staff_operational_roles (staff_identity_id, role)
VALUES ($1, $2)
ON CONFLICT (staff_identity_id, role) DO NOTHING
`

type AddStaffRoleParams struct {
	StaffIdentityID uuid.UUID `json:"staff_identity_id"`
	Role            string    `json:"role"`
}

func (q *Queries) AddStaffRole(ctx context.Context, arg AddStaffRoleParams) error {
	_, err := q.db.ExecContext(ctx, addStaffRole, arg.StaffIdentityID, arg.Role)
	return err
}

const clearStaffRoles = `-- name: ClearStaffRoles :exec
DELETE FROM staff_operational_roles
WHERE staff_identity_id = $1
`

func (q *Queries) ClearStaffRoles(ctx context.Context, staffIdentityID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearStaffRoles, staffIdentityID)
	return err
}

const countActiveManagers = `-- name: CountActiveManagers :one
SELECT count(DISTINCT si.id)::bigint
FROM staff_identities si
JOIN staff_operational_roles sor ON sor.staff_identity_id = si.id
WHERE si.enabled = true AND sor.role = 'MANAGER'
`

func (q *Queries) CountActiveManagers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveManagers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createStaffIdentity = `-- name: CreateStaffIdentity :one
INSERT INTO staff_identities (display_name, login_code, pin_hash, enabled)
VALUES ($1, upper(btrim($2)), $3, $4)
RETURNING id, display_name, login_code, enabled, created_at
`

type CreateStaffIdentityParams struct {
	DisplayName string `json:"display_name"`
	Btrim       string `json:"btrim"`
	PinHash     string `json:"pin_hash"`
	Enabled     bool   `json:"enabled"`
}

type CreateStaffIdentityRow struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
	LoginCode   string    `json:"login_code"`
	Enabled     bool      `json:"enabled"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreateStaffIdentity(ctx context.Context, arg CreateStaffIdentityParams) (CreateStaffIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, createStaffIdentity,
		arg.DisplayName,
		arg.Btrim,
		arg.PinHash,
		arg.Enabled,
	)
	var i CreateStaffIdentityRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.LoginCode,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const createStaffSession = `-- name: CreateStaffSession :one
INSERT INTO staff_access_sessions (
    token_hash, staff_identity_id, state, active_workspace, 
    last_authenticated_at, last_human_activity_at, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, token_hash, staff_identity_id, state, active_workspace, expires_at, revoked_at
`

type CreateStaffSessionParams struct {
	TokenHash           string         `json:"token_hash"`
	StaffIdentityID     uuid.UUID      `json:"staff_identity_id"`
	State               string         `json:"state"`
	ActiveWorkspace     sql.NullString `json:"active_workspace"`
	LastAuthenticatedAt time.Time      `json:"last_authenticated_at"`
	LastHumanActivityAt time.Time      `json:"last_human_activity_at"`
	ExpiresAt           time.Time      `json:"expires_at"`
}

type CreateStaffSessionRow struct {
	ID              uuid.UUID      `json:"id"`
	TokenHash       string         `json:"token_hash"`
	StaffIdentityID uuid.UUID      `json:"staff_identity_id"`
	State           string         `json:"state"`
	ActiveWorkspace sql.NullString `json:"active_workspace"`
	ExpiresAt       time.Time      `json:"expires_at"`
	RevokedAt       sql.NullTime   `json:"revoked_at"`
}

func (q *Queries) CreateStaffSession(ctx context.Context, arg CreateStaffSessionParams) (CreateStaffSessionRow, error) {
	row := q.db.QueryRowContext(ctx, createStaffSession,
		arg.TokenHash,
		arg.StaffIdentityID,
		arg.State,
		arg.ActiveWorkspace,
		arg.LastAuthenticatedAt,
		arg.LastHumanActivityAt,
		arg.ExpiresAt,
	)
	var i CreateStaffSessionRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.StaffIdentityID,
		&i.State,
		&i.ActiveWorkspace,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, actor_id, action, request_hash, response_code, response_body, created_at
FROM idempotency_keys
WHERE actor_id = $1 AND key = $2
LIMIT 1
`

type GetIdempotencyKeyParams struct {
	ActorID uuid.UUID `json:"actor_id"`
	Key     uuid.UUID `json:"key"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, getIdempotencyKey, arg.ActorID, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.ActorID,
		&i.Action,
		&i.RequestHash,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT 
    s.id AS session_id,
    s.token_hash,
    s.staff_identity_id,
    s.state AS session_state,
    s.active_workspace,
    s.last_authenticated_at,
    s.last_human_activity_at,
    s.expires_at,
    s.revoked_at,
    si.display_name,
    si.login_code,
    si.pin_hash,
    si.enabled AS identity_enabled
FROM staff_access_sessions s
JOIN staff_identities si ON si.id = s.staff_identity_id
WHERE s.token_hash = $1
LIMIT 1
`

type GetSessionByTokenHashRow struct {
	SessionID           uuid.UUID      `json:"session_id"`
	TokenHash           string         `json:"token_hash"`
	StaffIdentityID     uuid.UUID      `json:"staff_identity_id"`
	SessionState        string         `json:"session_state"`
	ActiveWorkspace     sql.NullString `json:"active_workspace"`
	LastAuthenticatedAt time.Time      `json:"last_authenticated_at"`
	LastHumanActivityAt time.Time      `json:"last_human_activity_at"`
	ExpiresAt           time.Time      `json:"expires_at"`
	RevokedAt           sql.NullTime   `json:"revoked_at"`
	DisplayName         string         `json:"display_name"`
	LoginCode           string         `json:"login_code"`
	PinHash             string         `json:"pin_hash"`
	IdentityEnabled     bool           `json:"identity_enabled"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.SessionID,
		&i.TokenHash,
		&i.StaffIdentityID,
		&i.SessionState,
		&i.ActiveWorkspace,
		&i.LastAuthenticatedAt,
		&i.LastHumanActivityAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.DisplayName,
		&i.LoginCode,
		&i.PinHash,
		&i.IdentityEnabled,
	)
	return i, err
}

const getStaffByID = `-- name: GetStaffByID :one
SELECT id, display_name, login_code, pin_hash, enabled, created_at
FROM staff_identities
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetStaffByID(ctx context.Context, id uuid.UUID) (StaffIdentity, error) {
	row := q.db.QueryRowContext(ctx, getStaffByID, id)
	var i StaffIdentity
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.LoginCode,
		&i.PinHash,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const getStaffByLoginCode = `-- name: GetStaffByLoginCode :one
SELECT id, display_name, login_code, pin_hash, enabled, created_at
FROM staff_identities
WHERE upper(btrim(login_code)) = upper(btrim($1))
LIMIT 1
`

func (q *Queries) GetStaffByLoginCode(ctx context.Context, btrim string) (StaffIdentity, error) {
	row := q.db.QueryRowContext(ctx, getStaffByLoginCode, btrim)
	var i StaffIdentity
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.LoginCode,
		&i.PinHash,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const getStaffRoles = `-- name: GetStaffRoles :many
SELECT role
FROM staff_operational_roles
WHERE staff_identity_id = $1
ORDER BY role ASC
`

func (q *Queries) GetStaffRoles(ctx context.Context, staffIdentityID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getStaffRoles, staffIdentityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :exec
INSERT INTO idempotency_keys (key, actor_id, action, request_hash, response_code, response_body)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertIdempotencyKeyParams struct {
	Key          uuid.UUID       `json:"key"`
	ActorID      uuid.UUID       `json:"actor_id"`
	Action       string          `json:"action"`
	RequestHash  string          `json:"request_hash"`
	ResponseCode int32           `json:"response_code"`
	ResponseBody json.RawMessage `json:"response_body"`
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertIdempotencyKey,
		arg.Key,
		arg.ActorID,
		arg.Action,
		arg.RequestHash,
		arg.ResponseCode,
		arg.ResponseBody,
	)
	return err
}

const listActiveIdentities = `-- name: ListActiveIdentities :many
SELECT display_name, login_code
FROM staff_identities
WHERE enabled = true
ORDER BY display_name ASC
`

type ListActiveIdentitiesRow struct {
	DisplayName string `json:"display_name"`
	LoginCode   string `json:"login_code"`
}

func (q *Queries) ListActiveIdentities(ctx context.Context) ([]ListActiveIdentitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveIdentities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveIdentitiesRow{}
	for rows.Next() {
		var i ListActiveIdentitiesRow
		if err := rows.Scan(&i.DisplayName, &i.LoginCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllStaff = `-- name: ListAllStaff :many
SELECT id, display_name, login_code, enabled, created_at
FROM staff_identities
ORDER BY display_name ASC
`

type ListAllStaffRow struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
	LoginCode   string    `json:"login_code"`
	Enabled     bool      `json:"enabled"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) ListAllStaff(ctx context.Context) ([]ListAllStaffRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllStaff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllStaffRow{}
	for rows.Next() {
		var i ListAllStaffRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.LoginCode,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllStaffRoles = `-- name: ListAllStaffRoles :many
SELECT staff_identity_id, role
FROM staff_operational_roles
ORDER BY staff_identity_id, role ASC
`

func (q *Queries) ListAllStaffRoles(ctx context.Context) ([]StaffOperationalRole, error) {
	rows, err := q.db.QueryContext(ctx, listAllStaffRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StaffOperationalRole{}
	for rows.Next() {
		var i StaffOperationalRole
		if err := rows.Scan(&i.StaffIdentityID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllStaffSessions = `-- name: RevokeAllStaffSessions :exec
UPDATE staff_access_sessions
SET revoked_at = now()
WHERE staff_identity_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllStaffSessions(ctx context.Context, staffIdentityID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeAllStaffSessions, staffIdentityID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE staff_access_sessions
SET revoked_at = now()
WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeSession, id)
	return err
}

const setStaffEnabled = `-- name: SetStaffEnabled :one
UPDATE staff_identities
SET enabled = $2
WHERE id = $1
RETURNING id, display_name, login_code, enabled
`

type SetStaffEnabledParams struct {
	ID      uuid.UUID `json:"id"`
	Enabled bool      `json:"enabled"`
}

type SetStaffEnabledRow struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
	LoginCode   string    `json:"login_code"`
	Enabled     bool      `json:"enabled"`
}

func (q *Queries) SetStaffEnabled(ctx context.Context, arg SetStaffEnabledParams) (SetStaffEnabledRow, error) {
	row := q.db.QueryRowContext(ctx, setStaffEnabled, arg.ID, arg.Enabled)
	var i SetStaffEnabledRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.LoginCode,
		&i.Enabled,
	)
	return i, err
}

const updateSessionActivity = `-- name: UpdateSessionActivity :exec
UPDATE staff_access_sessions
SET last_human_activity_at = $2
WHERE id = $1 AND revoked_at IS NULL
`

type UpdateSessionActivityParams struct {
	ID                  uuid.UUID `json:"id"`
	LastHumanActivityAt time.Time `json:"last_human_activity_at"`
}

func (q *Queries) UpdateSessionActivity(ctx context.Context, arg UpdateSessionActivityParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionActivity, arg.ID, arg.LastHumanActivityAt)
	return err
}

const updateSessionState = `-- name: UpdateSessionState :exec
UPDATE staff_access_sessions
SET state = $2
WHERE id = $1 AND revoked_at IS NULL
`

type UpdateSessionStateParams struct {
	ID    uuid.UUID `json:"id"`
	State string    `json:"state"`
}

func (q *Queries) UpdateSessionState(ctx context.Context, arg UpdateSessionStateParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionState, arg.ID, arg.State)
	return err
}

const updateSessionWorkspace = `-- name: UpdateSessionWorkspace :exec
UPDATE staff_access_sessions
SET active_workspace = $2
WHERE id = $1 AND revoked_at IS NULL
`

type UpdateSessionWorkspaceParams struct {
	ID              uuid.UUID      `json:"id"`
	ActiveWorkspace sql.NullString `json:"active_workspace"`
}

func (q *Queries) UpdateSessionWorkspace(ctx context.Context, arg UpdateSessionWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionWorkspace, arg.ID, arg.ActiveWorkspace)
	return err
}

const updateStaffPin = `-- name: UpdateStaffPin :exec
UPDATE staff_identities
SET pin_hash = $2
WHERE id = $1
`

type UpdateStaffPinParams struct {
	ID      uuid.UUID `json:"id"`
	PinHash string    `json:"pin_hash"`
}

func (q *Queries) UpdateStaffPin(ctx context.Context, arg UpdateStaffPinParams) error {
	_, err := q.db.ExecContext(ctx, updateStaffPin, arg.ID, arg.PinHash)
	return err
}
