// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preparation.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const acknowledgePreparationAlert = `-- name: AcknowledgePreparationAlert :one
UPDATE preparation_alerts
SET acknowledged_by_staff_identity_id = $1,
    acknowledged_staff_access_session_id = $2,
    acknowledged_at = $3
WHERE id = $4
RETURNING id, acknowledged_by_staff_identity_id,
          acknowledged_staff_access_session_id, acknowledged_at
`

type AcknowledgePreparationAlertParams struct {
	AcknowledgedByStaffIdentityID    uuid.NullUUID `json:"acknowledged_by_staff_identity_id"`
	AcknowledgedStaffAccessSessionID uuid.NullUUID `json:"acknowledged_staff_access_session_id"`
	AcknowledgedAt                   sql.NullTime  `json:"acknowledged_at"`
	ID                               uuid.UUID     `json:"id"`
}

type AcknowledgePreparationAlertRow struct {
	ID                               uuid.UUID     `json:"id"`
	AcknowledgedByStaffIdentityID    uuid.NullUUID `json:"acknowledged_by_staff_identity_id"`
	AcknowledgedStaffAccessSessionID uuid.NullUUID `json:"acknowledged_staff_access_session_id"`
	AcknowledgedAt                   sql.NullTime  `json:"acknowledged_at"`
}

// Fills the acknowledgment tuple together; the all-or-nothing check
// constraint rejects any partial write.
func (q *Queries) AcknowledgePreparationAlert(ctx context.Context, arg AcknowledgePreparationAlertParams) (AcknowledgePreparationAlertRow, error) {
	row := q.db.QueryRowContext(ctx, acknowledgePreparationAlert,
		arg.AcknowledgedByStaffIdentityID,
		arg.AcknowledgedStaffAccessSessionID,
		arg.AcknowledgedAt,
		arg.ID,
	)
	var i AcknowledgePreparationAlertRow
	err := row.Scan(
		&i.ID,
		&i.AcknowledgedByStaffIdentityID,
		&i.AcknowledgedStaffAccessSessionID,
		&i.AcknowledgedAt,
	)
	return i, err
}

const getNextPreparationUnitNumber = `-- name: GetNextPreparationUnitNumber :one
SELECT (coalesce(max(unit_number), 0) + 1)::integer AS next_unit_number
FROM preparation_units
WHERE order_item_id = $1
`

// Runs under the owning Order Item lock, so max + 1 cannot collide across
// concurrent Remakes of the same item.
func (q *Queries) GetNextPreparationUnitNumber(ctx context.Context, orderItemID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getNextPreparationUnitNumber, orderItemID)
	var next_unit_number int32
	err := row.Scan(&next_unit_number)
	return next_unit_number, err
}

const getPreparationCurrentTime = `-- name: GetPreparationCurrentTime :one
SELECT clock_timestamp()::timestamptz AS current_time
`

func (q *Queries) GetPreparationCurrentTime(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getPreparationCurrentTime)
	var current_time time.Time
	err := row.Scan(&current_time)
	return current_time, err
}

const getPreparationUnit = `-- name: GetPreparationUnit :one
SELECT id, order_item_id, unit_number, state, service_number, category_name,
       item_name, size_name, modifiers, preparation_note, queued_at,
       in_preparation_at, priority, remake_of_preparation_unit_id
FROM preparation_units
WHERE id = $1
`

func (q *Queries) GetPreparationUnit(ctx context.Context, id uuid.UUID) (PreparationUnit, error) {
	row := q.db.QueryRowContext(ctx, getPreparationUnit, id)
	var i PreparationUnit
	err := row.Scan(
		&i.ID,
		&i.OrderItemID,
		&i.UnitNumber,
		&i.State,
		&i.ServiceNumber,
		&i.CategoryName,
		&i.ItemName,
		&i.SizeName,
		&i.Modifiers,
		&i.PreparationNote,
		&i.QueuedAt,
		&i.InPreparationAt,
		&i.Priority,
		&i.RemakeOfPreparationUnitID,
	)
	return i, err
}

const insertPreparationAlert = `-- name: InsertPreparationAlert :one
INSERT INTO preparation_alerts (preparation_unit_id, kind, reason, note,
                                created_by_staff_identity_id,
                                created_staff_access_session_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, preparation_unit_id, kind, reason, note,
          created_by_staff_identity_id, created_staff_access_session_id,
          created_at, acknowledged_by_staff_identity_id,
          acknowledged_staff_access_session_id, acknowledged_at
`

type InsertPreparationAlertParams struct {
	PreparationUnitID           uuid.UUID      `json:"preparation_unit_id"`
	Kind                        string         `json:"kind"`
	Reason                      string         `json:"reason"`
	Note                        sql.NullString `json:"note"`
	CreatedByStaffIdentityID    uuid.UUID      `json:"created_by_staff_identity_id"`
	CreatedStaffAccessSessionID uuid.UUID      `json:"created_staff_access_session_id"`
	CreatedAt                   time.Time      `json:"created_at"`
}

func (q *Queries) InsertPreparationAlert(ctx context.Context, arg InsertPreparationAlertParams) (PreparationAlert, error) {
	row := q.db.QueryRowContext(ctx, insertPreparationAlert,
		arg.PreparationUnitID,
		arg.Kind,
		arg.Reason,
		arg.Note,
		arg.CreatedByStaffIdentityID,
		arg.CreatedStaffAccessSessionID,
		arg.CreatedAt,
	)
	var i PreparationAlert
	err := row.Scan(
		&i.ID,
		&i.PreparationUnitID,
		&i.Kind,
		&i.Reason,
		&i.Note,
		&i.CreatedByStaffIdentityID,
		&i.CreatedStaffAccessSessionID,
		&i.CreatedAt,
		&i.AcknowledgedByStaffIdentityID,
		&i.AcknowledgedStaffAccessSessionID,
		&i.AcknowledgedAt,
	)
	return i, err
}

const insertPreparationAuditEventsBatch = `-- name: InsertPreparationAuditEventsBatch :exec
INSERT INTO audit_events (event_type, actor_id, session_id, details, occurred_at)
SELECT batch.event_type_value, $1::uuid,
       $2::uuid, batch.details_value::jsonb,
       $3::timestamptz
FROM (
    SELECT unnest($4::text[]) AS event_type_value,
           unnest($5::text[]) AS details_value
) AS batch
`

type InsertPreparationAuditEventsBatchParams struct {
	ActorID      uuid.UUID `json:"actor_id"`
	SessionID    uuid.UUID `json:"session_id"`
	OccurredAt   time.Time `json:"occurred_at"`
	EventTypes   []string  `json:"event_types"`
	DetailsBatch []string  `json:"details_batch"`
}

// Batches audit events of differing types into one round trip. event_types
// and details_batch must be equal length; the parallel unnests zip row-wise
// and pad the shorter array with nulls, so any caller drift fails the target
// columns' NOT NULL constraints instead of silently truncating one array.
// details_batch is text[] cast to jsonb per element, for the same pq.Array
// reason the Catalog batch query records. Callers validate equal non-zero
// lengths in Go before calling.
func (q *Queries) InsertPreparationAuditEventsBatch(ctx context.Context, arg InsertPreparationAuditEventsBatchParams) error {
	_, err := q.db.ExecContext(ctx, insertPreparationAuditEventsBatch,
		arg.ActorID,
		arg.SessionID,
		arg.OccurredAt,
		pq.Array(arg.EventTypes),
		pq.Array(arg.DetailsBatch),
	)
	return err
}

const insertPreparationRemake = `-- name: InsertPreparationRemake :one
INSERT INTO preparation_remakes (waste_id, preparation_unit_id, reason, note,
                                 actor_staff_identity_id,
                                 staff_access_session_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, waste_id, preparation_unit_id, reason, note,
          actor_staff_identity_id, staff_access_session_id, created_at
`

type InsertPreparationRemakeParams struct {
	WasteID              uuid.UUID      `json:"waste_id"`
	PreparationUnitID    uuid.UUID      `json:"preparation_unit_id"`
	Reason               string         `json:"reason"`
	Note                 sql.NullString `json:"note"`
	ActorStaffIdentityID uuid.UUID      `json:"actor_staff_identity_id"`
	StaffAccessSessionID uuid.UUID      `json:"staff_access_session_id"`
	CreatedAt            time.Time      `json:"created_at"`
}

func (q *Queries) InsertPreparationRemake(ctx context.Context, arg InsertPreparationRemakeParams) (PreparationRemake, error) {
	row := q.db.QueryRowContext(ctx, insertPreparationRemake,
		arg.WasteID,
		arg.PreparationUnitID,
		arg.Reason,
		arg.Note,
		arg.ActorStaffIdentityID,
		arg.StaffAccessSessionID,
		arg.CreatedAt,
	)
	var i PreparationRemake
	err := row.Scan(
		&i.ID,
		&i.WasteID,
		&i.PreparationUnitID,
		&i.Reason,
		&i.Note,
		&i.ActorStaffIdentityID,
		&i.StaffAccessSessionID,
		&i.CreatedAt,
	)
	return i, err
}

const insertPreparationRemakeUnit = `-- name: InsertPreparationRemakeUnit :one
INSERT INTO preparation_units (order_item_id, unit_number, state, service_number,
                               category_name, item_name, size_name, modifiers,
                               preparation_note, queued_at, priority,
                               remake_of_preparation_unit_id)
VALUES ($1, $2, 'QUEUED', $3, $4, $5, $6, $7, $8, $9, 'REMAKE', $10)
RETURNING id, order_item_id, unit_number, state, service_number, category_name,
          item_name, size_name, modifiers, preparation_note, queued_at,
          in_preparation_at, priority, remake_of_preparation_unit_id
`

type InsertPreparationRemakeUnitParams struct {
	OrderItemID               uuid.UUID       `json:"order_item_id"`
	UnitNumber                int32           `json:"unit_number"`
	ServiceNumber             string          `json:"service_number"`
	CategoryName              string          `json:"category_name"`
	ItemName                  string          `json:"item_name"`
	SizeName                  sql.NullString  `json:"size_name"`
	Modifiers                 json.RawMessage `json:"modifiers"`
	PreparationNote           sql.NullString  `json:"preparation_note"`
	QueuedAt                  time.Time       `json:"queued_at"`
	RemakeOfPreparationUnitID uuid.NullUUID   `json:"remake_of_preparation_unit_id"`
}

// Creates the linked replacement unit: the source unit's immutable
// preparation snapshot under the next unit number, QUEUED at REMAKE
// priority, and linked back to its source. Adds no Order Item or charge.
func (q *Queries) InsertPreparationRemakeUnit(ctx context.Context, arg InsertPreparationRemakeUnitParams) (PreparationUnit, error) {
	row := q.db.QueryRowContext(ctx, insertPreparationRemakeUnit,
		arg.OrderItemID,
		arg.UnitNumber,
		arg.ServiceNumber,
		arg.CategoryName,
		arg.ItemName,
		arg.SizeName,
		arg.Modifiers,
		arg.PreparationNote,
		arg.QueuedAt,
		arg.RemakeOfPreparationUnitID,
	)
	var i PreparationUnit
	err := row.Scan(
		&i.ID,
		&i.OrderItemID,
		&i.UnitNumber,
		&i.State,
		&i.ServiceNumber,
		&i.CategoryName,
		&i.ItemName,
		&i.SizeName,
		&i.Modifiers,
		&i.PreparationNote,
		&i.QueuedAt,
		&i.InPreparationAt,
		&i.Priority,
		&i.RemakeOfPreparationUnitID,
	)
	return i, err
}

const insertPreparationStateCorrection = `-- name: InsertPreparationStateCorrection :one
INSERT INTO preparation_state_corrections (preparation_unit_id, prior_state,
                                           resulting_state, reason, note,
                                           actor_staff_identity_id,
                                           staff_access_session_id,
                                           occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, preparation_unit_id, prior_state, resulting_state, reason, note,
          actor_staff_identity_id, staff_access_session_id, occurred_at
`

type InsertPreparationStateCorrectionParams struct {
	PreparationUnitID    uuid.UUID      `json:"preparation_unit_id"`
	PriorState           string         `json:"prior_state"`
	ResultingState       string         `json:"resulting_state"`
	Reason               string         `json:"reason"`
	Note                 sql.NullString `json:"note"`
	ActorStaffIdentityID uuid.UUID      `json:"actor_staff_identity_id"`
	StaffAccessSessionID uuid.UUID      `json:"staff_access_session_id"`
	OccurredAt           time.Time      `json:"occurred_at"`
}

func (q *Queries) InsertPreparationStateCorrection(ctx context.Context, arg InsertPreparationStateCorrectionParams) (PreparationStateCorrection, error) {
	row := q.db.QueryRowContext(ctx, insertPreparationStateCorrection,
		arg.PreparationUnitID,
		arg.PriorState,
		arg.ResultingState,
		arg.Reason,
		arg.Note,
		arg.ActorStaffIdentityID,
		arg.StaffAccessSessionID,
		arg.OccurredAt,
	)
	var i PreparationStateCorrection
	err := row.Scan(
		&i.ID,
		&i.PreparationUnitID,
		&i.PriorState,
		&i.ResultingState,
		&i.Reason,
		&i.Note,
		&i.ActorStaffIdentityID,
		&i.StaffAccessSessionID,
		&i.OccurredAt,
	)
	return i, err
}

const insertPreparationUnitTransition = `-- name: InsertPreparationUnitTransition :exec
INSERT INTO preparation_unit_transitions (preparation_unit_id, prior_state,
                                          resulting_state,
                                          actor_staff_identity_id,
                                          staff_access_session_id, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertPreparationUnitTransitionParams struct {
	PreparationUnitID    uuid.UUID `json:"preparation_unit_id"`
	PriorState           string    `json:"prior_state"`
	ResultingState       string    `json:"resulting_state"`
	ActorStaffIdentityID uuid.UUID `json:"actor_staff_identity_id"`
	StaffAccessSessionID uuid.UUID `json:"staff_access_session_id"`
	OccurredAt           time.Time `json:"occurred_at"`
}

func (q *Queries) InsertPreparationUnitTransition(ctx context.Context, arg InsertPreparationUnitTransitionParams) error {
	_, err := q.db.ExecContext(ctx, insertPreparationUnitTransition,
		arg.PreparationUnitID,
		arg.PriorState,
		arg.ResultingState,
		arg.ActorStaffIdentityID,
		arg.StaffAccessSessionID,
		arg.OccurredAt,
	)
	return err
}

const insertPreparationWaste = `-- name: InsertPreparationWaste :one
INSERT INTO preparation_wastes (preparation_unit_id, prior_state, reason, note,
                                actor_staff_identity_id,
                                staff_access_session_id, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, preparation_unit_id, prior_state, reason, note,
          actor_staff_identity_id, staff_access_session_id, occurred_at
`

type InsertPreparationWasteParams struct {
	PreparationUnitID    uuid.UUID      `json:"preparation_unit_id"`
	PriorState           string         `json:"prior_state"`
	Reason               string         `json:"reason"`
	Note                 sql.NullString `json:"note"`
	ActorStaffIdentityID uuid.UUID      `json:"actor_staff_identity_id"`
	StaffAccessSessionID uuid.UUID      `json:"staff_access_session_id"`
	OccurredAt           time.Time      `json:"occurred_at"`
}

func (q *Queries) InsertPreparationWaste(ctx context.Context, arg InsertPreparationWasteParams) (PreparationWaste, error) {
	row := q.db.QueryRowContext(ctx, insertPreparationWaste,
		arg.PreparationUnitID,
		arg.PriorState,
		arg.Reason,
		arg.Note,
		arg.ActorStaffIdentityID,
		arg.StaffAccessSessionID,
		arg.OccurredAt,
	)
	var i PreparationWaste
	err := row.Scan(
		&i.ID,
		&i.PreparationUnitID,
		&i.PriorState,
		&i.Reason,
		&i.Note,
		&i.ActorStaffIdentityID,
		&i.StaffAccessSessionID,
		&i.OccurredAt,
	)
	return i, err
}

const listActivePreparationAlerts = `-- name: ListActivePreparationAlerts :many
SELECT pa.id, pa.preparation_unit_id, pa.kind, pa.reason, pa.note,
       pa.created_by_staff_identity_id, pa.created_staff_access_session_id,
       pa.created_at, pa.acknowledged_by_staff_identity_id,
       pa.acknowledged_staff_access_session_id, pa.acknowledged_at,
       pu.service_number, pu.item_name, pu.unit_number,
       w.id AS waste_id
FROM preparation_alerts AS pa
JOIN preparation_units AS pu ON pu.id = pa.preparation_unit_id
LEFT JOIN preparation_wastes AS w
       ON w.preparation_unit_id = pu.id AND pa.kind = 'WASTE'
WHERE pa.acknowledged_at IS NULL
ORDER BY pa.created_at ASC, pa.id ASC
`

type ListActivePreparationAlertsRow struct {
	ID                               uuid.UUID      `json:"id"`
	PreparationUnitID                uuid.UUID      `json:"preparation_unit_id"`
	Kind                             string         `json:"kind"`
	Reason                           string         `json:"reason"`
	Note                             sql.NullString `json:"note"`
	CreatedByStaffIdentityID         uuid.UUID      `json:"created_by_staff_identity_id"`
	CreatedStaffAccessSessionID      uuid.UUID      `json:"created_staff_access_session_id"`
	CreatedAt                        time.Time      `json:"created_at"`
	AcknowledgedByStaffIdentityID    uuid.NullUUID  `json:"acknowledged_by_staff_identity_id"`
	AcknowledgedStaffAccessSessionID uuid.NullUUID  `json:"acknowledged_staff_access_session_id"`
	AcknowledgedAt                   sql.NullTime   `json:"acknowledged_at"`
	ServiceNumber                    string         `json:"service_number"`
	ItemName                         string         `json:"item_name"`
	UnitNumber                       int32          `json:"unit_number"`
	WasteID                          uuid.NullUUID  `json:"waste_id"`
}

// The queue's active alerts, oldest first. The Waste join matches only
// WASTE alerts, so waste_id resolves through the Waste fact for WASTE and
// stays null for the reserved Cancellation kinds even if their unit carries
// a Waste.
func (q *Queries) ListActivePreparationAlerts(ctx context.Context) ([]ListActivePreparationAlertsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivePreparationAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivePreparationAlertsRow{}
	for rows.Next() {
		var i ListActivePreparationAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.PreparationUnitID,
			&i.Kind,
			&i.Reason,
			&i.Note,
			&i.CreatedByStaffIdentityID,
			&i.CreatedStaffAccessSessionID,
			&i.CreatedAt,
			&i.AcknowledgedByStaffIdentityID,
			&i.AcknowledgedStaffAccessSessionID,
			&i.AcknowledgedAt,
			&i.ServiceNumber,
			&i.ItemName,
			&i.UnitNumber,
			&i.WasteID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePreparationUnits = `-- name: ListActivePreparationUnits :many
SELECT pu.id,
       pu.order_item_id,
       pu.unit_number,
       pu.state,
       pu.service_number,
       pu.category_name,
       pu.item_name,
       pu.size_name,
       pu.modifiers,
       pu.preparation_note,
       pu.queued_at,
       pu.in_preparation_at,
       pu.priority,
       pu.remake_of_preparation_unit_id,
       o.service_session_id,
       (SELECT count(*)::integer
        FROM preparation_units AS pu2
        WHERE pu2.order_item_id = pu.order_item_id) AS order_item_unit_count
FROM preparation_units AS pu
JOIN order_items AS oi ON oi.id = pu.order_item_id
JOIN orders AS o ON o.id = oi.order_id
WHERE pu.state IN ('QUEUED', 'IN_PREPARATION', 'READY')
   OR (
       pu.state IN ('CANCELLED', 'WASTED')
       AND EXISTS (
           SELECT 1
           FROM preparation_alerts AS pa
           WHERE pa.preparation_unit_id = pu.id
             AND pa.acknowledged_at IS NULL
       )
   )
ORDER BY
    CASE
        WHEN pu.state IN ('QUEUED', 'IN_PREPARATION', 'READY')
             AND pu.priority = 'REMAKE' THEN 1
        WHEN pu.state IN ('QUEUED', 'IN_PREPARATION', 'READY') THEN 2
        ELSE 3
    END,
    pu.queued_at, pu.id
`

type ListActivePreparationUnitsRow struct {
	ID                        uuid.UUID       `json:"id"`
	OrderItemID               uuid.UUID       `json:"order_item_id"`
	UnitNumber                int32           `json:"unit_number"`
	State                     string          `json:"state"`
	ServiceNumber             string          `json:"service_number"`
	CategoryName              string          `json:"category_name"`
	ItemName                  string          `json:"item_name"`
	SizeName                  sql.NullString  `json:"size_name"`
	Modifiers                 json.RawMessage `json:"modifiers"`
	PreparationNote           sql.NullString  `json:"preparation_note"`
	QueuedAt                  time.Time       `json:"queued_at"`
	InPreparationAt           sql.NullTime    `json:"in_preparation_at"`
	Priority                  string          `json:"priority"`
	RemakeOfPreparationUnitID uuid.NullUUID   `json:"remake_of_preparation_unit_id"`
	ServiceSessionID          uuid.UUID       `json:"service_session_id"`
	OrderItemUnitCount        int32           `json:"order_item_unit_count"`
}

// The bar's work list: every active unit, plus a CANCELLED or WASTED unit
// while it still has an unacknowledged alert (EXISTS, so several alerts on
// one unit cannot duplicate the row). Active Remakes come first, active
// STANDARD units second, alert-retained terminal units last; each lane is
// FIFO by queued_at then id. unit_count is every physical unit of the Order
// Item, including Remakes and terminal units, computed per row via a
// correlated subquery (order_item_id is the leading column of
// preparation_unit_item_number_unique) rather than a full-table GROUP BY, so
// the cost tracks the small active-queue result set on this polled read.
func (q *Queries) ListActivePreparationUnits(ctx context.Context) ([]ListActivePreparationUnitsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivePreparationUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivePreparationUnitsRow{}
	for rows.Next() {
		var i ListActivePreparationUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderItemID,
			&i.UnitNumber,
			&i.State,
			&i.ServiceNumber,
			&i.CategoryName,
			&i.ItemName,
			&i.SizeName,
			&i.Modifiers,
			&i.PreparationNote,
			&i.QueuedAt,
			&i.InPreparationAt,
			&i.Priority,
			&i.RemakeOfPreparationUnitID,
			&i.ServiceSessionID,
			&i.OrderItemUnitCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentPreparationTables = `-- name: ListCurrentPreparationTables :many
SELECT ta.service_session_id, t.name
FROM table_assignments AS ta
JOIN tables AS t ON t.id = ta.table_id
WHERE ta.service_session_id = ANY($1::uuid[])
  AND ta.released_at IS NULL
ORDER BY ta.service_session_id, ta.sequence, ta.id
`

type ListCurrentPreparationTablesRow struct {
	ServiceSessionID uuid.UUID `json:"service_session_id"`
	Name             string    `json:"name"`
}

func (q *Queries) ListCurrentPreparationTables(ctx context.Context, serviceSessionIds []uuid.UUID) ([]ListCurrentPreparationTablesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCurrentPreparationTables, pq.Array(serviceSessionIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentPreparationTablesRow{}
	for rows.Next() {
		var i ListCurrentPreparationTablesRow
		if err := rows.Scan(&i.ServiceSessionID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreparationUnitsForCorrection = `-- name: ListPreparationUnitsForCorrection :many
SELECT pu.id, pu.state, pu.order_item_id, o.service_session_id
FROM preparation_units AS pu
JOIN order_items AS oi ON oi.id = pu.order_item_id
JOIN orders AS o ON o.id = oi.order_id
WHERE pu.id = ANY($1::uuid[])
`

type ListPreparationUnitsForCorrectionRow struct {
	ID               uuid.UUID `json:"id"`
	State            string    `json:"state"`
	OrderItemID      uuid.UUID `json:"order_item_id"`
	ServiceSessionID uuid.UUID `json:"service_session_id"`
}

// Resolves the selected units and their owning Sessions without locks, so a
// correction can reject missing ids before taking any.
func (q *Queries) ListPreparationUnitsForCorrection(ctx context.Context, preparationUnitIds []uuid.UUID) ([]ListPreparationUnitsForCorrectionRow, error) {
	rows, err := q.db.QueryContext(ctx, listPreparationUnitsForCorrection, pq.Array(preparationUnitIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPreparationUnitsForCorrectionRow{}
	for rows.Next() {
		var i ListPreparationUnitsForCorrectionRow
		if err := rows.Scan(
			&i.ID,
			&i.State,
			&i.OrderItemID,
			&i.ServiceSessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPreparationCorrections = `-- name: ListRecentPreparationCorrections :many
SELECT 'WASTE' AS entry_kind,
       w.id AS fact_id,
       NULL::uuid AS waste_id,
       w.preparation_unit_id,
       NULL::uuid AS source_preparation_unit_id,
       NULL::integer AS source_unit_number,
       pu.unit_number,
       pu.service_number,
       pu.item_name,
       w.reason,
       w.note,
       w.occurred_at
FROM preparation_wastes AS w
JOIN preparation_units AS pu ON pu.id = w.preparation_unit_id
JOIN order_items AS oi ON oi.id = pu.order_item_id
JOIN orders AS o ON o.id = oi.order_id
JOIN service_sessions AS ss ON ss.id = o.service_session_id
WHERE ss.state = 'ACTIVE'
UNION ALL
SELECT 'REMAKE' AS entry_kind,
       r.id AS fact_id,
       r.waste_id,
       r.preparation_unit_id,
       w.preparation_unit_id AS source_preparation_unit_id,
       wpu.unit_number AS source_unit_number,
       pu.unit_number,
       pu.service_number,
       pu.item_name,
       r.reason,
       r.note,
       r.created_at AS occurred_at
FROM preparation_remakes AS r
JOIN preparation_wastes AS w ON w.id = r.waste_id
JOIN preparation_units AS pu ON pu.id = r.preparation_unit_id
JOIN preparation_units AS wpu ON wpu.id = w.preparation_unit_id
JOIN order_items AS oi ON oi.id = pu.order_item_id
JOIN orders AS o ON o.id = oi.order_id
JOIN service_sessions AS ss ON ss.id = o.service_session_id
WHERE ss.state = 'ACTIVE'
ORDER BY occurred_at DESC, fact_id DESC
LIMIT 50
`

type ListRecentPreparationCorrectionsRow struct {
	EntryKind               string         `json:"entry_kind"`
	FactID                  uuid.UUID      `json:"fact_id"`
	WasteID                 uuid.NullUUID  `json:"waste_id"`
	PreparationUnitID       uuid.UUID      `json:"preparation_unit_id"`
	SourcePreparationUnitID uuid.NullUUID  `json:"source_preparation_unit_id"`
	SourceUnitNumber        sql.NullInt32  `json:"source_unit_number"`
	UnitNumber              int32          `json:"unit_number"`
	ServiceNumber           string         `json:"service_number"`
	ItemName                string         `json:"item_name"`
	Reason                  string         `json:"reason"`
	Note                    sql.NullString `json:"note"`
	OccurredAt              time.Time      `json:"occurred_at"`
}

// The queue's Waste and Remake history for active Sessions: one set-based
// UNION ALL, newest first, capped at 50. entry_kind discriminates the two
// row shapes; the nullable columns carry what each shape needs.
func (q *Queries) ListRecentPreparationCorrections(ctx context.Context) ([]ListRecentPreparationCorrectionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentPreparationCorrections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentPreparationCorrectionsRow{}
	for rows.Next() {
		var i ListRecentPreparationCorrectionsRow
		if err := rows.Scan(
			&i.EntryKind,
			&i.FactID,
			&i.WasteID,
			&i.PreparationUnitID,
			&i.SourcePreparationUnitID,
			&i.SourceUnitNumber,
			&i.UnitNumber,
			&i.ServiceNumber,
			&i.ItemName,
			&i.Reason,
			&i.Note,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPreparationAlert = `-- name: LockPreparationAlert :one
SELECT id, preparation_unit_id, kind, reason, note,
       created_by_staff_identity_id, created_staff_access_session_id,
       created_at, acknowledged_by_staff_identity_id,
       acknowledged_staff_access_session_id, acknowledged_at
FROM preparation_alerts
WHERE id = $1
FOR UPDATE
`

// Locks one alert for acknowledgment, returning its creation and
// acknowledgment evidence.
func (q *Queries) LockPreparationAlert(ctx context.Context, id uuid.UUID) (PreparationAlert, error) {
	row := q.db.QueryRowContext(ctx, lockPreparationAlert, id)
	var i PreparationAlert
	err := row.Scan(
		&i.ID,
		&i.PreparationUnitID,
		&i.Kind,
		&i.Reason,
		&i.Note,
		&i.CreatedByStaffIdentityID,
		&i.CreatedStaffAccessSessionID,
		&i.CreatedAt,
		&i.AcknowledgedByStaffIdentityID,
		&i.AcknowledgedStaffAccessSessionID,
		&i.AcknowledgedAt,
	)
	return i, err
}

const lockPreparationOrderItem = `-- name: LockPreparationOrderItem :one
SELECT oi.id, oi.order_id, o.service_session_id
FROM order_items AS oi
JOIN orders AS o ON o.id = oi.order_id
WHERE oi.id = $1
FOR UPDATE OF oi
`

type LockPreparationOrderItemRow struct {
	ID               uuid.UUID `json:"id"`
	OrderID          uuid.UUID `json:"order_id"`
	ServiceSessionID uuid.UUID `json:"service_session_id"`
}

// Locks the Order Item so Remake's max(unit_number) + 1 allocation
// serializes across concurrent Wastes of the same item, and returns the
// owning Session the caller locked first.
func (q *Queries) LockPreparationOrderItem(ctx context.Context, id uuid.UUID) (LockPreparationOrderItemRow, error) {
	row := q.db.QueryRowContext(ctx, lockPreparationOrderItem, id)
	var i LockPreparationOrderItemRow
	err := row.Scan(&i.ID, &i.OrderID, &i.ServiceSessionID)
	return i, err
}

const lockPreparationServiceSessions = `-- name: LockPreparationServiceSessions :many

SELECT id, service_number, state
FROM service_sessions
WHERE id = ANY($1::uuid[])
ORDER BY id ASC
FOR UPDATE
`

type LockPreparationServiceSessionsRow struct {
	ID            uuid.UUID `json:"id"`
	ServiceNumber string    `json:"service_number"`
	State         string    `json:"state"`
}

// Phase 6B: correction locks, facts, and queue recovery reads.
//
// Lock order is the concurrency contract (design section 10): Remake and
// State Correction lock owning Service Sessions before their work rows, so
// they serialize with Service Session closure. Waste uses the unit lock.
// Locks the owning Service Sessions before correction work. Callers pass
// unique ids; ORDER BY id makes the multi-Session lock order deterministic.
func (q *Queries) LockPreparationServiceSessions(ctx context.Context, serviceSessionIds []uuid.UUID) ([]LockPreparationServiceSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, lockPreparationServiceSessions, pq.Array(serviceSessionIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockPreparationServiceSessionsRow{}
	for rows.Next() {
		var i LockPreparationServiceSessionsRow
		if err := rows.Scan(&i.ID, &i.ServiceNumber, &i.State); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPreparationUnit = `-- name: LockPreparationUnit :one

SELECT id, order_item_id, unit_number, state, service_number, category_name,
       item_name, size_name, modifiers, preparation_note, queued_at,
       in_preparation_at, priority, remake_of_preparation_unit_id
FROM preparation_units
WHERE id = $1
FOR UPDATE
`

// Preparation slice queries.
//
// Boundary (ADR-024): nothing here writes orders, order_items, or
// completed_sales. internal/sales creates Preparation Units at Submit and
// reads their state during closure; this package owns every transition.
func (q *Queries) LockPreparationUnit(ctx context.Context, id uuid.UUID) (PreparationUnit, error) {
	row := q.db.QueryRowContext(ctx, lockPreparationUnit, id)
	var i PreparationUnit
	err := row.Scan(
		&i.ID,
		&i.OrderItemID,
		&i.UnitNumber,
		&i.State,
		&i.ServiceNumber,
		&i.CategoryName,
		&i.ItemName,
		&i.SizeName,
		&i.Modifiers,
		&i.PreparationNote,
		&i.QueuedAt,
		&i.InPreparationAt,
		&i.Priority,
		&i.RemakeOfPreparationUnitID,
	)
	return i, err
}

const lockPreparationUnitsForCorrection = `-- name: LockPreparationUnitsForCorrection :many
SELECT id, state
FROM preparation_units
WHERE id = ANY($1::uuid[])
ORDER BY id ASC
FOR UPDATE
`

type LockPreparationUnitsForCorrectionRow struct {
	ID    uuid.UUID `json:"id"`
	State string    `json:"state"`
}

// Locks the correction batch in unit-id order after its Sessions are locked.
func (q *Queries) LockPreparationUnitsForCorrection(ctx context.Context, preparationUnitIds []uuid.UUID) ([]LockPreparationUnitsForCorrectionRow, error) {
	rows, err := q.db.QueryContext(ctx, lockPreparationUnitsForCorrection, pq.Array(preparationUnitIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockPreparationUnitsForCorrectionRow{}
	for rows.Next() {
		var i LockPreparationUnitsForCorrectionRow
		if err := rows.Scan(&i.ID, &i.State); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPreparationWaste = `-- name: LockPreparationWaste :one
SELECT w.id, w.preparation_unit_id, w.prior_state, w.reason, w.note,
       w.actor_staff_identity_id, w.staff_access_session_id, w.occurred_at,
       pu.order_item_id, o.service_session_id
FROM preparation_wastes AS w
JOIN preparation_units AS pu ON pu.id = w.preparation_unit_id
JOIN order_items AS oi ON oi.id = pu.order_item_id
JOIN orders AS o ON o.id = oi.order_id
WHERE w.id = $1
FOR UPDATE OF w, pu
`

type LockPreparationWasteRow struct {
	ID                   uuid.UUID      `json:"id"`
	PreparationUnitID    uuid.UUID      `json:"preparation_unit_id"`
	PriorState           string         `json:"prior_state"`
	Reason               string         `json:"reason"`
	Note                 sql.NullString `json:"note"`
	ActorStaffIdentityID uuid.UUID      `json:"actor_staff_identity_id"`
	StaffAccessSessionID uuid.UUID      `json:"staff_access_session_id"`
	OccurredAt           time.Time      `json:"occurred_at"`
	OrderItemID          uuid.UUID      `json:"order_item_id"`
	ServiceSessionID     uuid.UUID      `json:"service_session_id"`
}

// Locks the Waste and its source Preparation Unit, and resolves the owning
// Order Item and Service Session ids the caller has already locked.
func (q *Queries) LockPreparationWaste(ctx context.Context, id uuid.UUID) (LockPreparationWasteRow, error) {
	row := q.db.QueryRowContext(ctx, lockPreparationWaste, id)
	var i LockPreparationWasteRow
	err := row.Scan(
		&i.ID,
		&i.PreparationUnitID,
		&i.PriorState,
		&i.Reason,
		&i.Note,
		&i.ActorStaffIdentityID,
		&i.StaffAccessSessionID,
		&i.OccurredAt,
		&i.OrderItemID,
		&i.ServiceSessionID,
	)
	return i, err
}

const setPreparationUnitCorrectedState = `-- name: SetPreparationUnitCorrectedState :exec
UPDATE preparation_units
SET state = $1,
    in_preparation_at = CASE
        WHEN $1::text = 'QUEUED'
            THEN NULL
        ELSE in_preparation_at
    END
WHERE id = $2
`

type SetPreparationUnitCorrectedStateParams struct {
	ResultingState string    `json:"resulting_state"`
	ID             uuid.UUID `json:"id"`
}

// Applies one reverse correction. Only a correction back to QUEUED clears
// in_preparation_at; the later targets keep it because the unit really did
// enter preparation at the earlier recorded instant.
func (q *Queries) SetPreparationUnitCorrectedState(ctx context.Context, arg SetPreparationUnitCorrectedStateParams) error {
	_, err := q.db.ExecContext(ctx, setPreparationUnitCorrectedState, arg.ResultingState, arg.ID)
	return err
}

const setPreparationUnitState = `-- name: SetPreparationUnitState :exec
UPDATE preparation_units
SET state = $1,
    in_preparation_at = CASE
        WHEN $1::text = 'IN_PREPARATION'
            THEN $2::timestamptz
        ELSE in_preparation_at
    END
WHERE id = $3
`

type SetPreparationUnitStateParams struct {
	State      string    `json:"state"`
	OccurredAt time.Time `json:"occurred_at"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) SetPreparationUnitState(ctx context.Context, arg SetPreparationUnitStateParams) error {
	_, err := q.db.ExecContext(ctx, setPreparationUnitState, arg.State, arg.OccurredAt, arg.ID)
	return err
}
