// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preparation.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getPreparationUnit = `-- name: GetPreparationUnit :one
SELECT id, order_item_id, unit_number, state, service_number, category_name,
       item_name, size_name, modifiers, preparation_note, queued_at
FROM preparation_units
WHERE id = $1
`

func (q *Queries) GetPreparationUnit(ctx context.Context, id uuid.UUID) (PreparationUnit, error) {
	row := q.db.QueryRowContext(ctx, getPreparationUnit, id)
	var i PreparationUnit
	err := row.Scan(
		&i.ID,
		&i.OrderItemID,
		&i.UnitNumber,
		&i.State,
		&i.ServiceNumber,
		&i.CategoryName,
		&i.ItemName,
		&i.SizeName,
		&i.Modifiers,
		&i.PreparationNote,
		&i.QueuedAt,
	)
	return i, err
}

const insertPreparationUnitTransition = `-- name: InsertPreparationUnitTransition :exec
INSERT INTO preparation_unit_transitions (preparation_unit_id, prior_state,
                                          resulting_state,
                                          actor_staff_identity_id,
                                          staff_access_session_id, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertPreparationUnitTransitionParams struct {
	PreparationUnitID    uuid.UUID `json:"preparation_unit_id"`
	PriorState           string    `json:"prior_state"`
	ResultingState       string    `json:"resulting_state"`
	ActorStaffIdentityID uuid.UUID `json:"actor_staff_identity_id"`
	StaffAccessSessionID uuid.UUID `json:"staff_access_session_id"`
	OccurredAt           time.Time `json:"occurred_at"`
}

func (q *Queries) InsertPreparationUnitTransition(ctx context.Context, arg InsertPreparationUnitTransitionParams) error {
	_, err := q.db.ExecContext(ctx, insertPreparationUnitTransition,
		arg.PreparationUnitID,
		arg.PriorState,
		arg.ResultingState,
		arg.ActorStaffIdentityID,
		arg.StaffAccessSessionID,
		arg.OccurredAt,
	)
	return err
}

const lockPreparationUnit = `-- name: LockPreparationUnit :one

SELECT id, order_item_id, unit_number, state, service_number, category_name,
       item_name, size_name, modifiers, preparation_note, queued_at
FROM preparation_units
WHERE id = $1
FOR UPDATE
`

// Preparation slice queries.
//
// Boundary (ADR-024): nothing here writes orders, order_items, or
// completed_sales. internal/sales creates Preparation Units at Submit and
// reads their state during closure; this package owns every transition.
func (q *Queries) LockPreparationUnit(ctx context.Context, id uuid.UUID) (PreparationUnit, error) {
	row := q.db.QueryRowContext(ctx, lockPreparationUnit, id)
	var i PreparationUnit
	err := row.Scan(
		&i.ID,
		&i.OrderItemID,
		&i.UnitNumber,
		&i.State,
		&i.ServiceNumber,
		&i.CategoryName,
		&i.ItemName,
		&i.SizeName,
		&i.Modifiers,
		&i.PreparationNote,
		&i.QueuedAt,
	)
	return i, err
}

const setPreparationUnitState = `-- name: SetPreparationUnitState :exec
UPDATE preparation_units SET state = $2 WHERE id = $1
`

type SetPreparationUnitStateParams struct {
	ID    uuid.UUID `json:"id"`
	State string    `json:"state"`
}

func (q *Queries) SetPreparationUnitState(ctx context.Context, arg SetPreparationUnitStateParams) error {
	_, err := q.db.ExecContext(ctx, setPreparationUnitState, arg.ID, arg.State)
	return err
}
