// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preparation.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getPreparationCurrentTime = `-- name: GetPreparationCurrentTime :one
SELECT clock_timestamp()::timestamptz AS current_time
`

func (q *Queries) GetPreparationCurrentTime(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getPreparationCurrentTime)
	var current_time time.Time
	err := row.Scan(&current_time)
	return current_time, err
}

const getPreparationUnit = `-- name: GetPreparationUnit :one
SELECT id, order_item_id, unit_number, state, service_number, category_name,
       item_name, size_name, modifiers, preparation_note, queued_at,
       in_preparation_at
FROM preparation_units
WHERE id = $1
`

func (q *Queries) GetPreparationUnit(ctx context.Context, id uuid.UUID) (PreparationUnit, error) {
	row := q.db.QueryRowContext(ctx, getPreparationUnit, id)
	var i PreparationUnit
	err := row.Scan(
		&i.ID,
		&i.OrderItemID,
		&i.UnitNumber,
		&i.State,
		&i.ServiceNumber,
		&i.CategoryName,
		&i.ItemName,
		&i.SizeName,
		&i.Modifiers,
		&i.PreparationNote,
		&i.QueuedAt,
		&i.InPreparationAt,
	)
	return i, err
}

const insertPreparationUnitTransition = `-- name: InsertPreparationUnitTransition :exec
INSERT INTO preparation_unit_transitions (preparation_unit_id, prior_state,
                                          resulting_state,
                                          actor_staff_identity_id,
                                          staff_access_session_id, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertPreparationUnitTransitionParams struct {
	PreparationUnitID    uuid.UUID `json:"preparation_unit_id"`
	PriorState           string    `json:"prior_state"`
	ResultingState       string    `json:"resulting_state"`
	ActorStaffIdentityID uuid.UUID `json:"actor_staff_identity_id"`
	StaffAccessSessionID uuid.UUID `json:"staff_access_session_id"`
	OccurredAt           time.Time `json:"occurred_at"`
}

func (q *Queries) InsertPreparationUnitTransition(ctx context.Context, arg InsertPreparationUnitTransitionParams) error {
	_, err := q.db.ExecContext(ctx, insertPreparationUnitTransition,
		arg.PreparationUnitID,
		arg.PriorState,
		arg.ResultingState,
		arg.ActorStaffIdentityID,
		arg.StaffAccessSessionID,
		arg.OccurredAt,
	)
	return err
}

const listActivePreparationUnits = `-- name: ListActivePreparationUnits :many
WITH unit_counts AS (
    SELECT order_item_id, count(*)::integer AS unit_count
    FROM preparation_units
    GROUP BY order_item_id
)
SELECT pu.id,
       pu.order_item_id,
       pu.unit_number,
       pu.state,
       pu.service_number,
       pu.category_name,
       pu.item_name,
       pu.size_name,
       pu.modifiers,
       pu.preparation_note,
       pu.queued_at,
       pu.in_preparation_at,
       o.service_session_id,
       uc.unit_count AS order_item_unit_count
FROM preparation_units AS pu
JOIN order_items AS oi ON oi.id = pu.order_item_id
JOIN orders AS o ON o.id = oi.order_id
JOIN unit_counts AS uc ON uc.order_item_id = pu.order_item_id
WHERE pu.state IN ('QUEUED', 'IN_PREPARATION', 'READY')
ORDER BY pu.queued_at, pu.id
`

type ListActivePreparationUnitsRow struct {
	ID                 uuid.UUID       `json:"id"`
	OrderItemID        uuid.UUID       `json:"order_item_id"`
	UnitNumber         int32           `json:"unit_number"`
	State              string          `json:"state"`
	ServiceNumber      string          `json:"service_number"`
	CategoryName       string          `json:"category_name"`
	ItemName           string          `json:"item_name"`
	SizeName           sql.NullString  `json:"size_name"`
	Modifiers          json.RawMessage `json:"modifiers"`
	PreparationNote    sql.NullString  `json:"preparation_note"`
	QueuedAt           time.Time       `json:"queued_at"`
	InPreparationAt    sql.NullTime    `json:"in_preparation_at"`
	ServiceSessionID   uuid.UUID       `json:"service_session_id"`
	OrderItemUnitCount int32           `json:"order_item_unit_count"`
}

func (q *Queries) ListActivePreparationUnits(ctx context.Context) ([]ListActivePreparationUnitsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivePreparationUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivePreparationUnitsRow{}
	for rows.Next() {
		var i ListActivePreparationUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderItemID,
			&i.UnitNumber,
			&i.State,
			&i.ServiceNumber,
			&i.CategoryName,
			&i.ItemName,
			&i.SizeName,
			&i.Modifiers,
			&i.PreparationNote,
			&i.QueuedAt,
			&i.InPreparationAt,
			&i.ServiceSessionID,
			&i.OrderItemUnitCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentPreparationTables = `-- name: ListCurrentPreparationTables :many
SELECT ta.service_session_id, t.name
FROM table_assignments AS ta
JOIN tables AS t ON t.id = ta.table_id
WHERE ta.service_session_id = ANY($1::uuid[])
  AND ta.released_at IS NULL
ORDER BY ta.service_session_id, ta.sequence, ta.id
`

type ListCurrentPreparationTablesRow struct {
	ServiceSessionID uuid.UUID `json:"service_session_id"`
	Name             string    `json:"name"`
}

func (q *Queries) ListCurrentPreparationTables(ctx context.Context, serviceSessionIds []uuid.UUID) ([]ListCurrentPreparationTablesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCurrentPreparationTables, pq.Array(serviceSessionIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentPreparationTablesRow{}
	for rows.Next() {
		var i ListCurrentPreparationTablesRow
		if err := rows.Scan(&i.ServiceSessionID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPreparationUnit = `-- name: LockPreparationUnit :one

SELECT id, order_item_id, unit_number, state, service_number, category_name,
       item_name, size_name, modifiers, preparation_note, queued_at,
       in_preparation_at
FROM preparation_units
WHERE id = $1
FOR UPDATE
`

// Preparation slice queries.
//
// Boundary (ADR-024): nothing here writes orders, order_items, or
// completed_sales. internal/sales creates Preparation Units at Submit and
// reads their state during closure; this package owns every transition.
func (q *Queries) LockPreparationUnit(ctx context.Context, id uuid.UUID) (PreparationUnit, error) {
	row := q.db.QueryRowContext(ctx, lockPreparationUnit, id)
	var i PreparationUnit
	err := row.Scan(
		&i.ID,
		&i.OrderItemID,
		&i.UnitNumber,
		&i.State,
		&i.ServiceNumber,
		&i.CategoryName,
		&i.ItemName,
		&i.SizeName,
		&i.Modifiers,
		&i.PreparationNote,
		&i.QueuedAt,
		&i.InPreparationAt,
	)
	return i, err
}

const setPreparationUnitState = `-- name: SetPreparationUnitState :exec
UPDATE preparation_units
SET state = $1,
    in_preparation_at = CASE
        WHEN $1::text = 'IN_PREPARATION'
            THEN $2::timestamptz
        ELSE in_preparation_at
    END
WHERE id = $3
`

type SetPreparationUnitStateParams struct {
	State      string    `json:"state"`
	OccurredAt time.Time `json:"occurred_at"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) SetPreparationUnitState(ctx context.Context, arg SetPreparationUnitStateParams) error {
	_, err := q.db.ExecContext(ctx, setPreparationUnitState, arg.State, arg.OccurredAt, arg.ID)
	return err
}
