// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	// Fills the acknowledgment tuple together; the all-or-nothing check
	// constraint rejects any partial write.
	AcknowledgePreparationAlert(ctx context.Context, arg AcknowledgePreparationAlertParams) (AcknowledgePreparationAlertRow, error)
	AddStaffRole(ctx context.Context, arg AddStaffRoleParams) error
	// -- Advisory Lock --
	CatalogAdvisoryLock(ctx context.Context, pgAdvisoryXactLock int64) error
	ClaimCatalogRequest(ctx context.Context, arg ClaimCatalogRequestParams) (CatalogMutationRequest, error)
	ClaimIdempotencyRecord(ctx context.Context, arg ClaimIdempotencyRecordParams) (IdempotencyKey, error)
	ClearStaffRoles(ctx context.Context, staffIdentityID uuid.UUID) error
	CloseServiceSession(ctx context.Context, id uuid.UUID) error
	CountActiveManagers(ctx context.Context) (int64, error)
	// Split and Merge rejection evidence (design section 6.2): the number of the
	// given Checks that carry at least one LIVE_CHECK Charge Adjustment. The
	// caller rejects with CHECK_HAS_CHARGE_ADJUSTMENT when this is non-zero.
	CountLiveChargeAdjustmentsForChecks(ctx context.Context, checkIds []uuid.UUID) (int64, error)
	CountManagers(ctx context.Context) (int64, error)
	CountPaymentsForChecks(ctx context.Context, dollar_1 []uuid.UUID) (int64, error)
	CreateCategoryModifierGroup(ctx context.Context, arg CreateCategoryModifierGroupParams) error
	// -- Association Queries --
	CreateItemModifierGroup(ctx context.Context, arg CreateItemModifierGroupParams) error
	CreateItemModifierGroupExclusion(ctx context.Context, arg CreateItemModifierGroupExclusionParams) error
	// -- Menu Categories --
	CreateMenuCategory(ctx context.Context, arg CreateMenuCategoryParams) (MenuCategory, error)
	// -- Menu Items --
	CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error)
	// -- Menu Item Sizes --
	CreateMenuItemSize(ctx context.Context, arg CreateMenuItemSizeParams) (MenuItemSize, error)
	CreateMenuItemSizes(ctx context.Context, arg CreateMenuItemSizesParams) ([]MenuItemSize, error)
	// -- Modifier Groups --
	CreateModifierGroup(ctx context.Context, arg CreateModifierGroupParams) (ModifierGroup, error)
	CreateModifierGroupDefaultOption(ctx context.Context, arg CreateModifierGroupDefaultOptionParams) error
	CreateModifierGroupDefaultOptions(ctx context.Context, arg CreateModifierGroupDefaultOptionsParams) error
	// -- Modifier Options --
	CreateModifierOption(ctx context.Context, arg CreateModifierOptionParams) (ModifierOption, error)
	CreateModifierOptions(ctx context.Context, arg CreateModifierOptionsParams) ([]ModifierOption, error)
	CreateStaffIdentity(ctx context.Context, arg CreateStaffIdentityParams) (CreateStaffIdentityRow, error)
	CreateStaffSession(ctx context.Context, arg CreateStaffSessionParams) (CreateStaffSessionRow, error)
	// -- Tables --
	CreateTable(ctx context.Context, arg CreateTableParams) (Table, error)
	DeleteAllocations(ctx context.Context, ids []uuid.UUID) error
	DeleteDraftItem(ctx context.Context, id uuid.UUID) error
	DeleteDraftItemModifierOptions(ctx context.Context, orderDraftItemID uuid.UUID) error
	DeleteModifierGroupDefaultOptions(ctx context.Context, modifierGroupID uuid.UUID) error
	DisableIdentity(ctx context.Context, arg DisableIdentityParams) error
	ExpireSession(ctx context.Context, arg ExpireSessionParams) error
	// A draft that prevents a new one opening: EDITABLE, or COMMITTED without a
	// corresponding Order.
	//
	// 5D added the orders table and completed the second clause as 5B's comment
	// promised. The rule stops staff stacking rounds ahead of the kitchen; it does
	// not limit a Service Session to one round.
	//
	// NOT EXISTS rather than a LEFT JOIN, for the reason LockSubmittableDraft
	// gives: PostgreSQL refuses row locks across a LEFT JOIN's nullable side.
	// (The outer service_session_id is spelled order_drafts.service_session_id
	// because sqlc's analyzer, unlike PostgreSQL, sees the subquery's orders
	// column of the same name and calls the bare reference ambiguous.)
	FindBlockingDraft(ctx context.Context, serviceSessionID uuid.UUID) (uuid.UUID, error)
	FindCompletedSaleByServiceSession(ctx context.Context, serviceSessionID uuid.UUID) (uuid.UUID, error)
	FindDraftItemByComposition(ctx context.Context, arg FindDraftItemByCompositionParams) (FindDraftItemByCompositionRow, error)
	// findDraftItemByComposition plus an id <> $n clause, so the row being edited
	// never matches itself. A separate query rather than a nullable exclusion
	// parameter keeps the add path's query untouched.
	FindDraftItemByCompositionExcluding(ctx context.Context, arg FindDraftItemByCompositionExcludingParams) (FindDraftItemByCompositionExcludingRow, error)
	// Non-locking resolution for CHANGE. Returns no row when the replacement Order
	// does not exist at all; the three boolean columns let the handler reject a
	// cross-Session, source, or not-later Order with one typed error.
	GetCancellationReplacementOrder(ctx context.Context, arg GetCancellationReplacementOrderParams) (GetCancellationReplacementOrderRow, error)
	GetCatalogMutationRequest(ctx context.Context, arg GetCatalogMutationRequestParams) (CatalogMutationRequest, error)
	// Catalog sqlc queries
	// Authorization, advisory-lock, idempotency, audit, and entity CRUD primitives.
	GetCatalogSessionAuthority(ctx context.Context, arg GetCatalogSessionAuthorityParams) (GetCatalogSessionAuthorityRow, error)
	GetCatalogSessionRoles(ctx context.Context, staffIdentityID uuid.UUID) ([]string, error)
	GetCategoryModifierGroup(ctx context.Context, arg GetCategoryModifierGroupParams) (CategoryModifierGroup, error)
	GetCompletedSale(ctx context.Context, id uuid.UUID) (GetCompletedSaleRow, error)
	GetEditableDraft(ctx context.Context, serviceSessionID uuid.UUID) (GetEditableDraftRow, error)
	// Includes released assignments, so a released sequence number is never
	// reused and the audit trail stays unambiguous.
	GetHighestAssignmentSequence(ctx context.Context, serviceSessionID uuid.UUID) (int32, error)
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error)
	// -- Shared idempotency (ADR-005) --
	GetIdempotencyRecord(ctx context.Context, arg GetIdempotencyRecordParams) (IdempotencyKey, error)
	GetMenuCategoryByID(ctx context.Context, id uuid.UUID) (MenuCategory, error)
	GetMenuCategoryForUpdate(ctx context.Context, id uuid.UUID) (MenuCategory, error)
	GetMenuItemByID(ctx context.Context, id uuid.UUID) (MenuItem, error)
	GetMenuItemForUpdate(ctx context.Context, id uuid.UUID) (MenuItem, error)
	GetMenuItemSizeByID(ctx context.Context, id uuid.UUID) (MenuItemSize, error)
	GetMenuItemSizeForUpdate(ctx context.Context, id uuid.UUID) (MenuItemSize, error)
	GetModifierGroupByID(ctx context.Context, id uuid.UUID) (ModifierGroup, error)
	GetModifierGroupForUpdate(ctx context.Context, id uuid.UUID) (ModifierGroup, error)
	GetModifierOptionByID(ctx context.Context, id uuid.UUID) (ModifierOption, error)
	GetModifierOptionForUpdate(ctx context.Context, id uuid.UUID) (ModifierOption, error)
	// Runs under the owning Order Item lock, so max + 1 cannot collide across
	// concurrent Remakes of the same item.
	GetNextPreparationUnitNumber(ctx context.Context, orderItemID uuid.UUID) (int32, error)
	// Callers MUST hold the advisory lock on the Sales Shift before running this.
	// Without it two concurrent opens read the same maximum and one loses to the
	// unique index.
	GetNextServiceSequence(ctx context.Context, salesShiftID uuid.UUID) (int32, error)
	GetOpenSalesShift(ctx context.Context) (GetOpenSalesShiftRow, error)
	// Single-table so the row lock is unambiguous; the opener is fetched separately
	// with GetStaffSummary.
	GetOpenSalesShiftForUpdate(ctx context.Context, id uuid.UUID) (GetOpenSalesShiftForUpdateRow, error)
	// Sales reads the Shift-owned table through its own query rather than
	// importing internal/shift, per ADR-006's precedent.
	GetOpenSalesShiftID(ctx context.Context) (uuid.UUID, error)
	GetOrderDraftCheckTarget(ctx context.Context, id uuid.UUID) (string, error)
	// Financial evidence for a Cancellation's affected Check, read while the
	// caller holds the Check lock. base_charge_vnd is the live sum of original
	// Charge Allocations; live_adjustment_vnd is every committed LIVE_CHECK
	// adjustment; valid_payment_vnd excludes voided Payments; completed_refund_vnd
	// counts completed live Refunds. The handler verifies stored charge = base -
	// live adjustments, then recomputes settlement and pending Refund from these
	// terms.
	GetPreparationCheckFinancials(ctx context.Context, id uuid.UUID) (GetPreparationCheckFinancialsRow, error)
	GetPreparationCurrentTime(ctx context.Context) (time.Time, error)
	GetPreparationUnit(ctx context.Context, id uuid.UUID) (PreparationUnit, error)
	GetSalesOccurredAt(ctx context.Context) (time.Time, error)
	// Queries for internal/sales (Phase 5A).
	//
	// Authority, role, and advisory-lock queries are slice-local by ADR-007: the
	// shared table is shared, the helper logic is not.
	GetSalesSessionAuthority(ctx context.Context, arg GetSalesSessionAuthorityParams) (GetSalesSessionAuthorityRow, error)
	GetSalesSessionRoles(ctx context.Context, staffIdentityID uuid.UUID) ([]string, error)
	GetSalesShiftStateByID(ctx context.Context, id uuid.UUID) (string, error)
	GetServiceSession(ctx context.Context, id uuid.UUID) (GetServiceSessionRow, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error)
	// -- Phase 6C: Payment Void, Refund & correction reconciliation --
	// Every Phase 6C reconciliation term for one Shift in one read (ADR-046).
	// Cash and Manual QR Payment terms count original applied amounts; a Payment
	// Void removes its source's whole amount; completed Refunds count money out;
	// a pending Manual QR Refund has not moved money yet.
	//
	// pending_refund_vnd is money owed back, matching the Check equation in spec
	// 6.1. For every distinct Check carrying a LIVE_CHECK Charge Adjustment
	// attributed to this Shift it sums
	//     greatest(valid_payments - completed_live_refunds - corrected_charge, 0)
	// where corrected_charge = base allocations - all LIVE_CHECK adjustments on
	// that Check (from every shift, because they all shape its current charge),
	// valid_payments excludes voided Payments, and completed_live_refunds counts
	// only completed Refunds without a Completed Sale. A Check touched by more
	// than one shift reports its whole live obligation in each affected shift's
	// read; a single shift read is the authoritative view of its own obligations
	// and never over-reports from adjustment capacity. unresolved_post_sale_
	// adjustment_vnd keeps its capacity-based meaning (the POST_SALE adjustment
	// amount not yet covered by completed Refunds) and is included in
	// pending_refund_vnd. internal/shift owns this SQL and imports neither sales
	// nor preparation.
	GetShiftReconciliationTotals(ctx context.Context, salesShiftID uuid.UUID) (GetShiftReconciliationTotalsRow, error)
	// -- Authority --
	// Names are prefixed because sqlc query names are global across the package.
	GetShiftSessionAuthority(ctx context.Context, arg GetShiftSessionAuthorityParams) (GetShiftSessionAuthorityRow, error)
	GetShiftSessionRoles(ctx context.Context, staffIdentityID uuid.UUID) ([]string, error)
	GetStaffByID(ctx context.Context, id uuid.UUID) (StaffIdentity, error)
	// Locks the actor's own identity row so State Correction's self-PIN
	// verification cannot interleave with a concurrent disablement or PIN
	// rotation. Follow with GetStaffRolesForUpdate on the same identity.
	GetStaffByIDForUpdate(ctx context.Context, id uuid.UUID) (StaffIdentity, error)
	GetStaffByLoginCode(ctx context.Context, btrim string) (StaffIdentity, error)
	// Locks the approver row so a concurrent disablement or role change cannot
	// interleave between verification and use. Used by VerifyManagerApproval.
	GetStaffByLoginCodeForUpdate(ctx context.Context, btrim string) (StaffIdentity, error)
	GetStaffRoles(ctx context.Context, staffIdentityID uuid.UUID) ([]string, error)
	GetStaffRolesForUpdate(ctx context.Context, staffIdentityID uuid.UUID) ([]string, error)
	GetStaffSummary(ctx context.Context, id uuid.UUID) (GetStaffSummaryRow, error)
	GetTableForUpdate(ctx context.Context, id uuid.UUID) (Table, error)
	// -- Authority --
	GetTablesSessionAuthority(ctx context.Context, arg GetTablesSessionAuthorityParams) (GetTablesSessionAuthorityRow, error)
	GetTablesSessionRoles(ctx context.Context, staffIdentityID uuid.UUID) ([]string, error)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error)
	// Batches a per-entry audit-insert loop into one round trip for callers
	// (Sales table-assignment audits) that write several events of the same type,
	// actor, session, and timestamp in one mutation, differing only in details.
	//
	// details_batch is text[], not jsonb[], and cast to jsonb per element inside
	// the query: the pq.Array encoder used for database/sql array parameters has
	// no driver.Valuer case for []json.RawMessage, so it falls through to its
	// generic reflection path and encodes each byte-slice element as a NESTED
	// ARRAY OF BYTES rather than a quoted string, which unnest then flatters into
	// one row per byte. []string goes through pq's dedicated, correct StringArray
	// codec instead.
	InsertAuditEventsBatch(ctx context.Context, arg InsertAuditEventsBatchParams) error
	// -- Cash Movements --
	InsertCashMovement(ctx context.Context, arg InsertCashMovementParams) (InsertCashMovementRow, error)
	InsertChargeAdjustment(ctx context.Context, arg InsertChargeAdjustmentParams) (ChargeAdjustment, error)
	InsertChargeAllocation(ctx context.Context, arg InsertChargeAllocationParams) error
	// The batched counterpart of InsertChargeAllocation, for a Split's destination
	// side. charge_allocation_item_check_unique allows at most one allocation per
	// (Committed Item, Check), so the caller lists only the items that do not have
	// one yet.
	InsertChargeAllocations(ctx context.Context, arg InsertChargeAllocationsParams) error
	InsertCheck(ctx context.Context, arg InsertCheckParams) (InsertCheckRow, error)
	InsertCommittedItem(ctx context.Context, arg InsertCommittedItemParams) (uuid.UUID, error)
	InsertCommittedItemModifierOption(ctx context.Context, arg InsertCommittedItemModifierOptionParams) error
	InsertCompletedSale(ctx context.Context, arg InsertCompletedSaleParams) (uuid.UUID, error)
	InsertDraftItem(ctx context.Context, arg InsertDraftItemParams) (InsertDraftItemRow, error)
	InsertDraftItemModifierOption(ctx context.Context, arg InsertDraftItemModifierOptionParams) error
	InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error
	InsertOrder(ctx context.Context, arg InsertOrderParams) (uuid.UUID, error)
	InsertOrderDraft(ctx context.Context, serviceSessionID uuid.UUID) (InsertOrderDraftRow, error)
	InsertOrderDraftForSession(ctx context.Context, arg InsertOrderDraftForSessionParams) (InsertOrderDraftForSessionRow, error)
	InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) (uuid.UUID, error)
	InsertPayment(ctx context.Context, arg InsertPaymentParams) (uuid.UUID, error)
	InsertPaymentVoid(ctx context.Context, arg InsertPaymentVoidParams) (PaymentVoid, error)
	InsertPreparationAlert(ctx context.Context, arg InsertPreparationAlertParams) (PreparationAlert, error)
	// Batches audit events of differing types into one round trip. event_types
	// and details_batch must be equal length; the parallel unnests zip row-wise
	// and pad the shorter array with nulls, so any caller drift fails the target
	// columns' NOT NULL constraints instead of silently truncating one array.
	// details_batch is text[] cast to jsonb per element, for the same pq.Array
	// reason the Catalog batch query records. Callers validate equal non-zero
	// lengths in Go before calling.
	InsertPreparationAuditEventsBatch(ctx context.Context, arg InsertPreparationAuditEventsBatchParams) error
	InsertPreparationCancellation(ctx context.Context, arg InsertPreparationCancellationParams) (PreparationCancellation, error)
	InsertPreparationRemake(ctx context.Context, arg InsertPreparationRemakeParams) (PreparationRemake, error)
	// Creates the linked replacement unit: the source unit's immutable
	// preparation snapshot under the next unit number, QUEUED at REMAKE
	// priority, and linked back to its source. Adds no Order Item or charge.
	InsertPreparationRemakeUnit(ctx context.Context, arg InsertPreparationRemakeUnitParams) (PreparationUnit, error)
	InsertPreparationStateCorrection(ctx context.Context, arg InsertPreparationStateCorrectionParams) (PreparationStateCorrection, error)
	InsertPreparationUnit(ctx context.Context, arg InsertPreparationUnitParams) error
	InsertPreparationUnitTransition(ctx context.Context, arg InsertPreparationUnitTransitionParams) error
	InsertPreparationWaste(ctx context.Context, arg InsertPreparationWasteParams) (PreparationWaste, error)
	InsertRefund(ctx context.Context, arg InsertRefundParams) (Refund, error)
	// The Charge Adjustment counterpart of InsertRefundPaymentAllocations.
	InsertRefundAdjustmentAllocations(ctx context.Context, arg InsertRefundAdjustmentAllocationsParams) error
	InsertRefundCompletion(ctx context.Context, arg InsertRefundCompletionParams) (RefundCompletion, error)
	// Writes one Refund's whole Payment allocation set in one round trip. The two
	// single-array unnests zip row-wise by ordinality, so row i is
	// (payment_ids[i], amounts[i]); the caller validates equal lengths and
	// positive amounts before calling, and the pair unique constraint rejects a
	// duplicated source.
	InsertRefundPaymentAllocations(ctx context.Context, arg InsertRefundPaymentAllocationsParams) error
	InsertSalesComp(ctx context.Context, arg InsertSalesCompParams) (SalesComp, error)
	InsertServiceSession(ctx context.Context, arg InsertServiceSessionParams) (InsertServiceSessionRow, error)
	// Batches assignTables' per-Table insert loop into one round trip. Two
	// single-array unnests joined by WITH ORDINALITY zip table_ids and sequences
	// into rows in lockstep, so row i of the result is table_ids[i] assigned at
	// sequences[i]; the caller relies on getting exactly len(table_ids) rows back
	// in that order.
	InsertTableAssignmentsBatch(ctx context.Context, arg InsertTableAssignmentsBatchParams) ([]InsertTableAssignmentsBatchRow, error)
	ListActiveIdentities(ctx context.Context) ([]ListActiveIdentitiesRow, error)
	// The queue's active alerts, oldest first. The Waste join matches only
	// WASTE alerts, so waste_id resolves through the Waste fact for WASTE and
	// stays null for the reserved Cancellation kinds even if their unit carries
	// a Waste.
	ListActivePreparationAlerts(ctx context.Context) ([]ListActivePreparationAlertsRow, error)
	// The bar's work list: every active unit, plus a CANCELLED or WASTED unit
	// while it still has an unacknowledged alert (EXISTS, so several alerts on
	// one unit cannot duplicate the row). Active Remakes come first, active
	// STANDARD units second, alert-retained terminal units last; each lane is
	// FIFO by queued_at then id. unit_count is every physical unit of the Order
	// Item, including Remakes and terminal units, computed per row via a
	// correlated subquery (order_item_id is the leading column of
	// preparation_unit_item_number_unique) rather than a full-table GROUP BY, so
	// the cost tracks the small active-queue result set on this polled read.
	ListActivePreparationUnits(ctx context.Context) ([]ListActivePreparationUnitsRow, error)
	ListActiveServiceSessions(ctx context.Context) ([]ListActiveServiceSessionsRow, error)
	// Every Refund allocation against the given Charge Adjustments, with the
	// owning Refund's scope and completion evidence, so the Check projection can
	// derive each Adjustment's remaining corrected capacity. Pending Manual QR
	// intents reserve capacity here too.
	ListAdjustmentRefundAllocations(ctx context.Context, chargeAdjustmentIds []uuid.UUID) ([]ListAdjustmentRefundAllocationsRow, error)
	ListAllCategoryModifierGroups(ctx context.Context) ([]ListAllCategoryModifierGroupsRow, error)
	ListAllItemModifierGroupExclusions(ctx context.Context) ([]ListAllItemModifierGroupExclusionsRow, error)
	ListAllItemModifierGroups(ctx context.Context) ([]ListAllItemModifierGroupsRow, error)
	ListAllMenuItemSizes(ctx context.Context) ([]MenuItemSize, error)
	ListAllMenuItemSizesPaginated(ctx context.Context, arg ListAllMenuItemSizesPaginatedParams) ([]MenuItemSize, error)
	// -- Bulk Queries for Projections --
	ListAllMenuItems(ctx context.Context) ([]MenuItem, error)
	ListAllMenuItemsPaginated(ctx context.Context, arg ListAllMenuItemsPaginatedParams) ([]MenuItem, error)
	ListAllModifierGroupDefaultOptions(ctx context.Context) ([]ListAllModifierGroupDefaultOptionsRow, error)
	ListAllModifierGroupsPaginated(ctx context.Context, arg ListAllModifierGroupsPaginatedParams) ([]ModifierGroup, error)
	ListAllModifierOptions(ctx context.Context) ([]ModifierOption, error)
	ListAllModifierOptionsPaginated(ctx context.Context, arg ListAllModifierOptionsPaginatedParams) ([]ModifierOption, error)
	ListAllStaff(ctx context.Context) ([]ListAllStaffRow, error)
	ListAllStaffRoles(ctx context.Context) ([]StaffOperationalRole, error)
	// One Check's allocations restricted to a set of Committed Items, with the
	// frozen unit price the moved amount is computed from.
	//
	// The array argument is named through sqlc.arg so the generated params struct
	// carries CommittedItemIds rather than a positional Column2.
	ListAllocationsForItems(ctx context.Context, arg ListAllocationsForItemsParams) ([]ListAllocationsForItemsRow, error)
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error)
	ListCashMovements(ctx context.Context, salesShiftID uuid.UUID) ([]ListCashMovementsRow, error)
	ListCategoryModifierGroupsByCategory(ctx context.Context, menuCategoryID uuid.UUID) ([]ListCategoryModifierGroupsByCategoryRow, error)
	ListCheckAllocationQuantities(ctx context.Context, checkID uuid.UUID) ([]ListCheckAllocationQuantitiesRow, error)
	ListCheckAllocations(ctx context.Context, checkID uuid.UUID) ([]ListCheckAllocationsRow, error)
	// The live Check projection's append-only charge reductions, ordered by
	// occurrence then id. POST_SALE adjustments are excluded: they correct a
	// closed sale and are read through ListCompletedSalePostSaleCorrections.
	ListCheckChargeAdjustments(ctx context.Context, checkID uuid.UUID) ([]ListCheckChargeAdjustmentsRow, error)
	// Ordered by (received_at, id), served directly by payment_check_index. The
	// LEFT JOIN carries Phase 6C Payment Void evidence so the Check projection can
	// present and subtract a voided Payment without a second read; void_id is null
	// while the Payment stands.
	ListCheckPayments(ctx context.Context, checkID uuid.UUID) ([]ListCheckPaymentsRow, error)
	// The live Check projection's Refunds, each with nullable completion evidence
	// so the caller derives PENDING or COMPLETED without a mutable state column.
	// Post-sale Refunds are excluded; they are read through
	// ListCompletedSalePostSaleCorrections.
	ListCheckRefunds(ctx context.Context, checkID uuid.UUID) ([]ListCheckRefundsRow, error)
	ListCommittedItemModifiers(ctx context.Context, committedItemIds []uuid.UUID) ([]ListCommittedItemModifiersRow, error)
	ListCommittedItemsForSubmission(ctx context.Context, orderDraftID uuid.UUID) ([]ListCommittedItemsForSubmissionRow, error)
	// Additive post-sale correction history for one Completed Sale: every
	// POST_SALE charge reduction (with its Comp fact) and every post-sale Refund,
	// ordered by occurrence then id. entry_kind discriminates the two row shapes;
	// each shape fills only its own columns. The leading WHERE false header exists
	// so the generated row type carries every column as nullable; a real row
	// always fills its own shape. Each row carries every column a full
	// PostSaleCorrectionResponse needs, so the shared loader never fabricates a
	// zero placeholder. The immutable sale snapshot itself is never rebuilt from
	// these rows.
	ListCompletedSalePostSaleCorrections(ctx context.Context, completedSaleID uuid.UUID) ([]ListCompletedSalePostSaleCorrectionsRow, error)
	ListCurrentPreparationTables(ctx context.Context, serviceSessionIds []uuid.UUID) ([]ListCurrentPreparationTablesRow, error)
	// -- Occupancy (read-only view of Sales-owned tables) --
	ListCurrentTableOccupants(ctx context.Context) ([]ListCurrentTableOccupantsRow, error)
	// Declared defaults of the given Groups, filtered to what is currently
	// selectable. A retired Group's defaults never apply.
	ListDefaultModifierOptionIDs(ctx context.Context, groupIds []uuid.UUID) ([]uuid.UUID, error)
	// Ordered by Group then Option name, which is the order the projection emits.
	ListDraftItemModifierOptions(ctx context.Context, orderDraftID uuid.UUID) ([]ListDraftItemModifierOptionsRow, error)
	ListDraftItemOptionIDs(ctx context.Context, orderDraftItemID uuid.UUID) ([]uuid.UUID, error)
	// The selected Options of the given draft items, with the Group facts the
	// Commit rules need. The Options are locked FOR SHARE per ADR-015's lock
	// list, so a retirement or availability change cannot land between the
	// Commit validation and its writes; modifier_groups stay unlocked.
	ListDraftItemOptionsForCommit(ctx context.Context, draftItemIds []uuid.UUID) ([]ListDraftItemOptionsForCommitRow, error)
	// price_vnd is the Size price when a Size is chosen and the Item price
	// otherwise, matching the canonical Menu Price rule. available is read live
	// rather than snapshotted: a draft is a live proposal, and an item that became
	// unavailable while the customer was deciding must show as such.
	//
	// price_vnd reads the Size price through a correlated scalar subquery rather
	// than the column directly. The subquery returns the same value (it references
	// the already-joined row), but sqlc infers scalar subqueries as nullable, so
	// COALESCE yields sql.NullInt64 instead of a bare int64 that cannot scan the
	// NULL price of a required-Size Item whose Size has not been chosen yet.
	ListDraftItems(ctx context.Context, orderDraftID uuid.UUID) ([]ListDraftItemsRow, error)
	// (inherited - exclusions) + direct, for one Menu Item.
	//
	// internal/catalog computes the same set in the exported pure function
	// EffectiveGroupIDs. Sales does not import it: MIGRATE_PLAN section 4.1
	// forbids importing another slice, and ADR-006 established reading another
	// slice's tables through one's own query. Expressing the algebra once in SQL
	// keeps the duplication to one function against one query, which
	// TestSalesResolutionMatchesCatalog pins together. See ADR-012.
	ListEffectiveModifierGroupIDs(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error)
	// (inherited - exclusions) + direct, for a SET of Menu Items, returning the
	// selection rules Commit enforces.
	//
	// This is the second expression of the algebra ListEffectiveModifierGroupIDs
	// already encodes. TestSalesResolutionMatchesCatalog pins both to
	// catalog.EffectiveGroupIDs over shared fixtures so they cannot drift. The
	// single-item query is left alone: the draft path does not need min/max and
	// should not pay for them. See ADR-012.
	ListEffectiveModifierGroupsForCommit(ctx context.Context, menuItemIds []uuid.UUID) ([]ListEffectiveModifierGroupsForCommitRow, error)
	ListHeldTableAssignments(ctx context.Context, serviceSessionID uuid.UUID) ([]ListHeldTableAssignmentsRow, error)
	ListItemModifierGroupExclusionsByItem(ctx context.Context, menuItemID uuid.UUID) ([]ListItemModifierGroupExclusionsByItemRow, error)
	ListItemModifierGroupsByItem(ctx context.Context, menuItemID uuid.UUID) ([]ListItemModifierGroupsByItemRow, error)
	ListMenuCategories(ctx context.Context) ([]MenuCategory, error)
	ListMenuItemSizesByItem(ctx context.Context, menuItemID uuid.UUID) ([]MenuItemSize, error)
	ListMenuItemsByCategory(ctx context.Context, categoryID uuid.UUID) ([]MenuItem, error)
	// -- Paginated Reads --
	ListMenuItemsByCategoryPaginated(ctx context.Context, arg ListMenuItemsByCategoryPaginatedParams) ([]MenuItem, error)
	ListModifierGroupDefaultOptionsByGroup(ctx context.Context, modifierGroupID uuid.UUID) ([]ListModifierGroupDefaultOptionsByGroupRow, error)
	ListModifierGroups(ctx context.Context) ([]ModifierGroup, error)
	ListModifierOptionsByGroup(ctx context.Context, modifierGroupID uuid.UUID) ([]ModifierOption, error)
	ListModifierOptionsForValidation(ctx context.Context, optionIds []uuid.UUID) ([]ListModifierOptionsForValidationRow, error)
	ListOrderItems(ctx context.Context, orderIds []uuid.UUID) ([]OrderItem, error)
	// Every Refund allocation against the given Payments, with the owning Refund's
	// scope and completion evidence, so the Check projection can derive each
	// Payment's remaining_refundable_vnd. Pending Manual QR intents appear too:
	// they reserve capacity before money moves. The caller applies the structural
	// snapshot rule (a post-sale allocation belongs to history, not the live
	// capacity) through refund_completed_sale_id.
	ListPaymentRefundAllocations(ctx context.Context, paymentIds []uuid.UUID) ([]ListPaymentRefundAllocationsRow, error)
	// Batched projection read for a set of ids already known to exist (e.g. a
	// cancellation batch), avoiding one GetPreparationUnit round trip per unit.
	ListPreparationUnitsByIDs(ctx context.Context, preparationUnitIds []uuid.UUID) ([]PreparationUnit, error)
	// Resolves the selected units and their owning Sessions without locks, so a
	// correction can reject missing ids before taking any.
	ListPreparationUnitsForCorrection(ctx context.Context, preparationUnitIds []uuid.UUID) ([]ListPreparationUnitsForCorrectionRow, error)
	// The queue's Waste and Remake history for active Sessions: one set-based
	// UNION ALL, newest first, capped at 50. entry_kind discriminates the two
	// row shapes; the nullable columns carry what each shape needs.
	ListRecentPreparationCorrections(ctx context.Context) ([]ListRecentPreparationCorrectionsRow, error)
	// One Refund's Charge Adjustment allocations, ordered by Adjustment id.
	ListRefundAdjustmentAllocations(ctx context.Context, refundID uuid.UUID) ([]ListRefundAdjustmentAllocationsRow, error)
	// Every Charge Adjustment allocation for the given Refunds, for a Check's
	// batched Refund projection: one round trip replaces one
	// ListRefundAdjustmentAllocations call per Refund.
	ListRefundAdjustmentAllocationsByRefundIDs(ctx context.Context, refundIds []uuid.UUID) ([]ListRefundAdjustmentAllocationsByRefundIDsRow, error)
	// One Refund's Payment allocations, ordered by Payment id, for the Refund
	// result and the Completed Sale history.
	ListRefundPaymentAllocations(ctx context.Context, refundID uuid.UUID) ([]ListRefundPaymentAllocationsRow, error)
	// Every Payment allocation for the given Refunds, for a Check's batched
	// Refund projection: one round trip replaces one ListRefundPaymentAllocations
	// call per Refund.
	ListRefundPaymentAllocationsByRefundIDs(ctx context.Context, refundIds []uuid.UUID) ([]ListRefundPaymentAllocationsByRefundIDsRow, error)
	// Current assignments only. Released rows are history, not occupancy.
	ListServiceSessionTables(ctx context.Context, serviceSessionID uuid.UUID) ([]ListServiceSessionTablesRow, error)
	ListSessionChecks(ctx context.Context, serviceSessionID uuid.UUID) ([]ListSessionChecksRow, error)
	ListSessionOrders(ctx context.Context, serviceSessionID uuid.UUID) ([]ListSessionOrdersRow, error)
	ListSessionPreparationTransitions(ctx context.Context, serviceSessionID uuid.UUID) ([]PreparationUnitTransition, error)
	// One read feeding both the live Service Session and Completed Sale unit
	// projections. priority and remake_of_preparation_unit_id carry the Phase 6B
	// Remake metadata; original units are STANDARD with a null link.
	ListSessionPreparationUnits(ctx context.Context, serviceSessionID uuid.UUID) ([]ListSessionPreparationUnitsRow, error)
	// The Shift response's Refund summaries ordered by (created_at, id), each
	// carrying derived completion state and no credentials.
	ListShiftRefunds(ctx context.Context, salesShiftID uuid.UUID) ([]ListShiftRefundsRow, error)
	// The `submitted` flag on a Charge Allocation is derived, not stored: there is
	// no submitted column anywhere in the schema, and therefore no flag that can
	// fall out of step with the Order that defines it.
	ListSubmittedCommittedItems(ctx context.Context, committedItemIds []uuid.UUID) ([]uuid.UUID, error)
	ListTables(ctx context.Context) ([]Table, error)
	// Step 4: the selected Charge Adjustments FOR UPDATE, each ascending UUID,
	// after the Payments so both refundable capacities are held in one order.
	LockChargeAdjustmentsForRefund(ctx context.Context, chargeAdjustmentIds []uuid.UUID) ([]LockChargeAdjustmentsForRefundRow, error)
	// The 5C lock protocol (ADR-016 as amended by ADR-030), first half: the Check
	// row FOR UPDATE. SQL does not guarantee that one statement's FOR UPDATE OF c, s
	// acquires the two relations' tuple locks in OF-list order, so the Session lock
	// is a separate statement: the caller locks the Check here and its Session
	// through LockServiceSessionForUpdate immediately afterwards, which is the same
	// Check-then-Session order lockChecks uses for restructurings. See ADR-030.
	//
	// The Session is exclusive (FOR UPDATE, not FOR SHARE), because a Payment does
	// not merely read the Session to evaluate a precondition -- it rebuilds the
	// whole Service Session read model through LoadServiceSession inside the same
	// READ COMMITTED transaction, and that rebuild is several statements. A sibling
	// Check's commit landing between them is observed half-applied and trips the
	// settlement invariant, which rolls back a valid Payment.
	//
	// The Shift is deliberately absent. A Payment's sales_shift_id is the Shift
	// open at the moment of the Payment, which is not necessarily the one the
	// Session was opened in (ADR-019), so it comes from LockOpenSalesShiftForShare.
	//
	// No row means the Check id does not exist. The state columns come back
	// unfiltered so the caller can report which precondition failed.
	LockCheckForPayment(ctx context.Context, id uuid.UUID) (LockCheckForPaymentRow, error)
	// The 5C lock protocol over a set of Checks (ADR-016 as amended by ADR-030),
	// ordered by id so two concurrent restructurings take the rows in the same
	// order and cannot deadlock against each other or against a Payment.
	//
	// The Session is deliberately NOT locked here, and `service_sessions` is not
	// joined. Locking it inside this statement would place it between two Check
	// locks (check(A) -> session -> check(B)) and create a cycle against a Payment
	// that already holds check(B) and is waiting for the Session. The caller locks
	// every Check first and the Session afterwards, which is the same order
	// LockCheckForPayment uses. See lockChecks and ADR-030.
	//
	// As in LockCheckForPayment, the Shift is not joined: the Shift precondition
	// is about the Shift open now, which LockOpenSalesShiftForShare reads.
	LockChecksForRestructuring(ctx context.Context, dollar_1 []uuid.UUID) ([]LockChecksForRestructuringRow, error)
	// Every distinct Check reachable from the draft's Committed Items, locked in
	// the ascending (created_at, id) order 5C's lock protocol established, so
	// Submit and a concurrent Payment serialize instead of deadlocking.
	//
	// The draft linkage lives in an IN subquery rather than a DISTINCT over a
	// join: PostgreSQL refuses the locking clause alongside DISTINCT, the same
	// restriction the NOT EXISTS form of LockSubmittableDraft avoids. Selecting
	// from checks directly makes DISTINCT unnecessary — c.id is the primary key —
	// and keeps the lock scoped to the checks relation exactly as the join's
	// FOR UPDATE OF c intended.
	LockChecksForSubmission(ctx context.Context, orderDraftID uuid.UUID) ([]LockChecksForSubmissionRow, error)
	// The Session's most recent OPEN Check, for the CURRENT_UNPAID target.
	LockCurrentOpenCheck(ctx context.Context, serviceSessionID uuid.UUID) (LockCurrentOpenCheckRow, error)
	LockCurrentTableAssignments(ctx context.Context, serviceSessionID uuid.UUID) ([]LockCurrentTableAssignmentsRow, error)
	// Scoped to the draft, so a caller cannot reach an item of another Session by
	// guessing its id.
	LockDraftItem(ctx context.Context, arg LockDraftItemParams) (LockDraftItemRow, error)
	// Every draft item with the Catalog facts Commit revalidates against, locked
	// so the rows cannot change between validation and write: the draft items FOR
	// UPDATE, and the joined Menu Items FOR SHARE per ADR-015's lock list.
	// Ordered by (created_at, id), which also fixes the order of the Committed
	// Items.
	LockDraftItemsForCommit(ctx context.Context, orderDraftID uuid.UUID) ([]LockDraftItemsForCommitRow, error)
	// Checks every precondition and takes the lock in one statement, so there is
	// no window between the check and the write.
	//
	// No match means the Session is missing, closed, its draft already committed,
	// or its Sales Shift closed. The caller reports EDITABLE_DRAFT_NOT_FOUND for
	// all four: the remedy is the same, and distinguishing them would leak state
	// about Sessions the caller did not ask about.
	LockEditableDraft(ctx context.Context, id uuid.UUID) (LockEditableDraftRow, error)
	// Locked FOR UPDATE so the Item cannot be retired between validation and
	// write. Sales rows are always locked before Catalog rows, and
	// internal/catalog never locks Sales rows, so no deadlock cycle exists.
	LockMenuItemForDraft(ctx context.Context, id uuid.UUID) (LockMenuItemForDraftRow, error)
	// Locked FOR UPDATE for the same reason as LockMenuItemForDraft: without it, a
	// concurrent retirement of this Size can slip between validation and the
	// draft-item write.
	LockMenuItemSizeForDraft(ctx context.Context, id uuid.UUID) (LockMenuItemSizeForDraftRow, error)
	// Locked FOR SHARE: Commit only reads these rows and must merely prevent a
	// retirement or availability change landing mid-transaction. FOR UPDATE would
	// serialize two cashiers committing orders that share a popular item, on the
	// busiest path in the system, for no correctness gain. internal/catalog's
	// mutations take FOR UPDATE and are still excluded. See ADR-015.
	LockMenuItemSizesForCommit(ctx context.Context, sizeIds []uuid.UUID) ([]LockMenuItemSizesForCommitRow, error)
	// Step 3: the one open Sales Shift. FOR SHARE, because Cancellation only reads
	// the Shift for settlement evidence and never writes Shift state; Shift
	// closure takes FOR UPDATE and stays excluded for the whole transaction. No
	// row means no Shift is open.
	LockOpenSalesShiftForCancellation(ctx context.Context) (LockOpenSalesShiftForCancellationRow, error)
	// The Sales Shift open right now, locked FOR SHARE. Only one Shift can be open
	// at a time, enforced by sales_shift_only_one_open_unique, so no ordering or
	// disambiguation is needed.
	//
	// Read from sales_shifts rather than through the Check's Session. The Shift in
	// which money reached the cashier is an independent fact — a Session opened in
	// one Shift can be paid in the next — which is why ADR-019 stores it on the
	// Payment at all.
	//
	// FOR SHARE, not FOR UPDATE: every command here only reads the Shift to
	// evaluate a precondition. Shift closure takes FOR UPDATE and stays excluded
	// for the duration of the transaction. See §6.1.
	//
	// No row means no Shift is open.
	LockOpenSalesShiftForShare(ctx context.Context) (uuid.UUID, error)
	// Locks one Payment for Void after its Check, Session, and Shift are locked.
	// Refund allocations, if any, are read separately under this lock to reject a
	// refunded Payment.
	LockPaymentForVoid(ctx context.Context, id uuid.UUID) (LockPaymentForVoidRow, error)
	// Steps 4: the selected Payments FOR UPDATE, each ascending UUID, so two
	// overlapping Refunds cannot allocate the same capacity twice and cannot
	// deadlock against each other.
	LockPaymentsForRefund(ctx context.Context, paymentIds []uuid.UUID) ([]LockPaymentsForRefundRow, error)
	// Locks one alert for acknowledgment, returning its creation and
	// acknowledgment evidence.
	LockPreparationAlert(ctx context.Context, id uuid.UUID) (PreparationAlert, error)
	// Step 1 of the common correction lock order: every affected Check FOR UPDATE,
	// ordered by id so concurrent corrections take the rows in the same order.
	LockPreparationChecksForCancellation(ctx context.Context, checkIds []uuid.UUID) ([]LockPreparationChecksForCancellationRow, error)
	// Locks the Order Item so Remake's max(unit_number) + 1 allocation
	// serializes across concurrent Wastes of the same item, and returns the
	// owning Session the caller locked first.
	LockPreparationOrderItem(ctx context.Context, id uuid.UUID) (LockPreparationOrderItemRow, error)
	// Phase 6B: correction locks, facts, and queue recovery reads.
	//
	// Lock order is the concurrency contract (design section 10): Remake and
	// State Correction lock owning Service Sessions before their work rows, so
	// they serialize with Service Session closure. Waste uses the unit lock.
	// Locks the owning Service Sessions before correction work. Callers pass
	// unique ids; ORDER BY id makes the multi-Session lock order deterministic.
	LockPreparationServiceSessions(ctx context.Context, serviceSessionIds []uuid.UUID) ([]LockPreparationServiceSessionsRow, error)
	// Step 2: the owning Service Sessions, after their Checks and before the
	// current Shift and the work rows.
	LockPreparationSessionsForCancellation(ctx context.Context, serviceSessionIds []uuid.UUID) ([]LockPreparationSessionsForCancellationRow, error)
	// Preparation slice queries.
	//
	// Boundary (ADR-024): nothing here writes orders, order_items, or
	// completed_sales. internal/sales creates Preparation Units at Submit and
	// reads their state during closure; this package owns every transition.
	LockPreparationUnit(ctx context.Context, id uuid.UUID) (PreparationUnit, error)
	// Step 5: the selected Preparation Units, locked last in id order after their
	// Checks and Sessions. The caller revalidates QUEUED and re-resolves the
	// unit-to-allocation mapping against the committed rows.
	LockPreparationUnitsForCancellation(ctx context.Context, preparationUnitIds []uuid.UUID) ([]LockPreparationUnitsForCancellationRow, error)
	// Locks the correction batch in unit-id order after its Sessions are locked.
	LockPreparationUnitsForCorrection(ctx context.Context, preparationUnitIds []uuid.UUID) ([]LockPreparationUnitsForCorrectionRow, error)
	// Locks the Waste and its source Preparation Unit, and resolves the owning
	// Order Item and Service Session ids the caller has already locked.
	LockPreparationWaste(ctx context.Context, id uuid.UUID) (LockPreparationWasteRow, error)
	// Locks one Refund for Manual QR confirmation, after its Check, Session, and
	// Shift are locked, and returns the completion evidence that decides replay.
	LockRefundForConfirmation(ctx context.Context, id uuid.UUID) (LockRefundForConfirmationRow, error)
	LockServiceSessionForClosure(ctx context.Context, id uuid.UUID) (LockServiceSessionForClosureRow, error)
	// The Submit source's Service Session, locked first. The state is returned
	// rather than filtered so an unknown Session and a closed one map to their own
	// errors instead of collapsing into ErrNothingToSubmit, per spec §9.3.
	LockServiceSessionForSubmission(ctx context.Context, id uuid.UUID) (LockServiceSessionForSubmissionRow, error)
	LockServiceSessionForUpdate(ctx context.Context, id uuid.UUID) (LockServiceSessionForUpdateRow, error)
	// The committed-but-unsubmitted Order Draft of the Session the caller has
	// already locked with LockServiceSessionForSubmission. Only the draft is
	// locked here: the Session lock is its own query so a missing or closed
	// Session can be told apart from "nothing to submit".
	//
	// NOT EXISTS rather than the canonical LEFT JOIN ... IS NULL: PostgreSQL
	// refuses row locks across a LEFT JOIN's nullable side, which forces the
	// canonical source to scope FOR UPDATE by hand and explain the workaround in
	// two places. Written this way the restriction does not arise.
	//
	// Known remaining window, recorded rather than reordered (ADR-031): this
	// query runs after the Session lock and before LockChecksForSubmission, so
	// the AB-BA window spans Submit's Session → Draft → Checks lock sequence —
	// the reverse of Payment's Check-then-Session order — and a concurrent
	// Payment can abort one side with 40P01 across it.
	LockSubmittableDraft(ctx context.Context, serviceSessionID uuid.UUID) (uuid.UUID, error)
	// Locks the selected Tables in id order so two concurrent assignments over
	// overlapping sets cannot deadlock against each other. The caller must sort
	// the ids before calling.
	LockTablesForAssignment(ctx context.Context, tableIds []uuid.UUID) ([]LockTablesForAssignmentRow, error)
	// Step 5: the Waste and its source Preparation Unit, locked after the Check,
	// Session, and Shift resolved by ResolveCompSource. The unit lock serializes
	// concurrent Comps of one Waste alongside the unique Waste reference.
	LockWasteForComp(ctx context.Context, id uuid.UUID) (LockWasteForCompRow, error)
	// The absorbed Check keeps no charge and points at the survivor, which is
	// what the MERGED branch of check_settlement_evidence_valid requires.
	MarkCheckMerged(ctx context.Context, arg MarkCheckMergedParams) error
	MarkOrderDraftCommitted(ctx context.Context, id uuid.UUID) error
	MoveAllocationsToCheck(ctx context.Context, arg MoveAllocationsToCheckParams) error
	// -- Sales Shift --
	OpenSalesShift(ctx context.Context, arg OpenSalesShiftParams) (SalesShift, error)
	RaiseCheckCharge(ctx context.Context, arg RaiseCheckChargeParams) error
	// released_at and released_by_staff_identity_id must be set together; the
	// table_assignment_release_evidence_valid constraint from migration 000006
	// rejects one without the other.
	ReleaseTableAssignment(ctx context.Context, arg ReleaseTableAssignmentParams) error
	RenameMenuCategory(ctx context.Context, arg RenameMenuCategoryParams) (MenuCategory, error)
	RenameMenuItem(ctx context.Context, arg RenameMenuItemParams) (MenuItem, error)
	RenameMenuItemSize(ctx context.Context, arg RenameMenuItemSizeParams) (MenuItemSize, error)
	RenameModifierGroup(ctx context.Context, arg RenameModifierGroupParams) (ModifierGroup, error)
	RenameModifierOption(ctx context.Context, arg RenameModifierOptionParams) (ModifierOption, error)
	RenameTable(ctx context.Context, arg RenameTableParams) (Table, error)
	// The settlement consequence of a whole Payment Void that leaves a positive
	// balance: the Check moves back from SETTLED to OPEN. All four
	// settlement-evidence columns are cleared in the same statement because
	// check_settlement_evidence_valid rejects OPEN with any evidence set. The
	// caller has already recomputed the positive balance under the Check lock.
	ReopenCheckAfterPaymentVoid(ctx context.Context, id uuid.UUID) error
	RepriceMenuItem(ctx context.Context, arg RepriceMenuItemParams) (MenuItem, error)
	RepriceMenuItemSize(ctx context.Context, arg RepriceMenuItemSizeParams) (MenuItemSize, error)
	RepriceModifierOption(ctx context.Context, arg RepriceModifierOptionParams) (ModifierOption, error)
	// Phase 6C: Cancellation locks, resolution, and facts.
	//
	// Lock order is the concurrency contract (design section 11.1): resolve
	// ownership without locks, then lock Checks ascending by id, Service Sessions
	// ascending by id, the current open Sales Shift, and finally the selected
	// Preparation Units ascending by id. Restructuring locks Checks; closure locks
	// Sessions; Waste and State Correction lock Sessions before units but never
	// wait on a Check, so no lock cycle exists.
	// Non-locking resolution of a Cancellation selection. Each STANDARD unit maps
	// to the immutable per-unit price of its Committed Item and to the Charge
	// Allocation whose cumulative quantity range (allocations ordered by
	// created_at then id) covers its unit_number. A REMAKE unit, or a unit beyond
	// every allocation range, carries a null allocation, Check, and price because
	// it was never charged.
	ResolveCancellationUnits(ctx context.Context, preparationUnitIds []uuid.UUID) ([]ResolveCancellationUnitsRow, error)
	// Phase 6C: Comp, Refund, and Payment Void resolution, locks, and facts.
	//
	// Lock order is the concurrency contract (design section 11.1): non-locking
	// resolution first, then Checks ascending, Service Sessions ascending, the
	// current or original Sales Shift, Payments and Charge Adjustments each
	// ascending, and finally Preparation source facts and Units ascending.
	// Non-locking ownership resolution for Comp. Resolves the Waste, its source
	// unit, the owning Order Item and Service Session, the Completed Sale when the
	// Session is already closed, and the original Charge Allocation whose
	// cumulative quantity range (allocations ordered by created_at then id) covers
	// the unit_number. A Wasted Remake maps to a null allocation and price because
	// it was never charged.
	ResolveCompSource(ctx context.Context, id uuid.UUID) (ResolveCompSourceRow, error)
	RetireMenuCategory(ctx context.Context, arg RetireMenuCategoryParams) (MenuCategory, error)
	RetireMenuItem(ctx context.Context, arg RetireMenuItemParams) (MenuItem, error)
	RetireMenuItemSize(ctx context.Context, arg RetireMenuItemSizeParams) (MenuItemSize, error)
	RetireModifierGroup(ctx context.Context, arg RetireModifierGroupParams) (ModifierGroup, error)
	RetireModifierOption(ctx context.Context, arg RetireModifierOptionParams) (ModifierOption, error)
	RevokeAllStaffSessions(ctx context.Context, staffIdentityID uuid.UUID) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	SalesAdvisoryLock(ctx context.Context, pgAdvisoryXactLock int64) error
	// A whole set of quantity rewrites in one statement. Split and Merge compute
	// the new quantities in Go and hand the batch over, so the work done while the
	// Checks are locked is a fixed number of round trips rather than one per
	// allocation touched.
	SetAllocationQuantities(ctx context.Context, arg SetAllocationQuantitiesParams) error
	SetCheckCharge(ctx context.Context, arg SetCheckChargeParams) error
	SetDraftItemQuantity(ctx context.Context, arg SetDraftItemQuantityParams) (SetDraftItemQuantityRow, error)
	SetMenuItemAvailability(ctx context.Context, arg SetMenuItemAvailabilityParams) (MenuItem, error)
	SetMenuItemSizeAvailability(ctx context.Context, arg SetMenuItemSizeAvailabilityParams) (MenuItemSize, error)
	SetModifierOptionAvailability(ctx context.Context, arg SetModifierOptionAvailabilityParams) (ModifierOption, error)
	SetOrderDraftCheckTarget(ctx context.Context, arg SetOrderDraftCheckTargetParams) error
	// Applies one reverse correction. Only a correction back to QUEUED clears
	// in_preparation_at; the later targets keep it because the unit really did
	// enter preparation at the earlier recorded instant.
	SetPreparationUnitCorrectedState(ctx context.Context, arg SetPreparationUnitCorrectedStateParams) error
	SetPreparationUnitState(ctx context.Context, arg SetPreparationUnitStateParams) error
	SetStaffEnabled(ctx context.Context, arg SetStaffEnabledParams) (SetStaffEnabledRow, error)
	SetTableAvailability(ctx context.Context, arg SetTableAvailabilityParams) (Table, error)
	// The settlement consequence of a Cancellation or Comp that reduces a live
	// Check to zero balance. All four evidence columns are written together
	// because check_settlement_evidence_valid rejects any partial set; the
	// initiator and the current open Shift supply the evidence.
	SettleAdjustedCheck(ctx context.Context, arg SettleAdjustedCheckParams) error
	// Writes all four evidence columns together, because the composite constraint
	// check_settlement_evidence_valid rejects any partial set.
	SettleCheck(ctx context.Context, arg SettleCheckParams) error
	ShiftAdvisoryLock(ctx context.Context, pgAdvisoryXactLock int64) error
	StoreCatalogRequestResult(ctx context.Context, arg StoreCatalogRequestResultParams) error
	StoreIdempotencyResult(ctx context.Context, arg StoreIdempotencyResultParams) error
	SumCashMovements(ctx context.Context, salesShiftID uuid.UUID) (SumCashMovementsRow, error)
	// The live sum that a Check's stored charge_vnd denormalizes, in one round trip
	// rather than loading every allocation and its modifiers to add them up.
	//
	// The caller compares this against the stored value; it is evidence, never
	// authority. The product cannot overflow BIGINT because charge_allocations
	// bounds quantity to 1..9999, and PostgreSQL would raise rather than wrap.
	SumCheckAllocatedCharge(ctx context.Context, checkID uuid.UUID) (int64, error)
	SumCheckPayments(ctx context.Context, checkID uuid.UUID) (int64, error)
	TablesAdvisoryLock(ctx context.Context, pgAdvisoryXactLock int64) error
	// Writes the denormalized live charge after one Cancellation batch plans all
	// of its adjustments. The invariant is stored charge = base charge - live
	// adjustments; POST_SALE adjustments are excluded.
	UpdateAdjustedCheckCharge(ctx context.Context, arg UpdateAdjustedCheckChargeParams) error
	// size_key and note_key are generated columns, so they follow the write.
	UpdateDraftItemComposition(ctx context.Context, arg UpdateDraftItemCompositionParams) error
	UpdateSessionActivity(ctx context.Context, arg UpdateSessionActivityParams) error
	UpdateSessionState(ctx context.Context, arg UpdateSessionStateParams) error
	UpdateSessionWorkspace(ctx context.Context, arg UpdateSessionWorkspaceParams) error
	UpdateStaffPin(ctx context.Context, arg UpdateStaffPinParams) error
}

var _ Querier = (*Queries)(nil)
