// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getEditableDraft = `-- name: GetEditableDraft :one
SELECT id, service_session_id, state, created_at
FROM order_drafts
WHERE service_session_id = $1 AND state = 'EDITABLE'
`

func (q *Queries) GetEditableDraft(ctx context.Context, serviceSessionID uuid.UUID) (OrderDraft, error) {
	row := q.db.QueryRowContext(ctx, getEditableDraft, serviceSessionID)
	var i OrderDraft
	err := row.Scan(
		&i.ID,
		&i.ServiceSessionID,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const getNextServiceSequence = `-- name: GetNextServiceSequence :one
SELECT COALESCE(MAX(sequence), 0)::int + 1 AS next_sequence
FROM service_sessions
WHERE sales_shift_id = $1
`

// Callers MUST hold the advisory lock on the Sales Shift before running this.
// Without it two concurrent opens read the same maximum and one loses to the
// unique index.
func (q *Queries) GetNextServiceSequence(ctx context.Context, salesShiftID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getNextServiceSequence, salesShiftID)
	var next_sequence int32
	err := row.Scan(&next_sequence)
	return next_sequence, err
}

const getOpenSalesShiftID = `-- name: GetOpenSalesShiftID :one
SELECT id FROM sales_shifts WHERE state = 'OPEN' LIMIT 1
`

// Sales reads the Shift-owned table through its own query rather than
// importing internal/shift, per ADR-006's precedent.
func (q *Queries) GetOpenSalesShiftID(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getOpenSalesShiftID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getSalesSessionAuthority = `-- name: GetSalesSessionAuthority :one

SELECT s.id AS session_id, s.staff_identity_id, s.state, s.active_workspace,
       s.last_human_activity_at, s.expires_at, s.revoked_at,
       i.enabled AS identity_enabled, i.display_name, i.login_code
FROM staff_access_sessions s
JOIN staff_identities i ON i.id = s.staff_identity_id
WHERE s.id = $1 AND s.staff_identity_id = $2
`

type GetSalesSessionAuthorityParams struct {
	ID              uuid.UUID `json:"id"`
	StaffIdentityID uuid.UUID `json:"staff_identity_id"`
}

type GetSalesSessionAuthorityRow struct {
	SessionID           uuid.UUID      `json:"session_id"`
	StaffIdentityID     uuid.UUID      `json:"staff_identity_id"`
	State               string         `json:"state"`
	ActiveWorkspace     sql.NullString `json:"active_workspace"`
	LastHumanActivityAt time.Time      `json:"last_human_activity_at"`
	ExpiresAt           time.Time      `json:"expires_at"`
	RevokedAt           sql.NullTime   `json:"revoked_at"`
	IdentityEnabled     bool           `json:"identity_enabled"`
	DisplayName         string         `json:"display_name"`
	LoginCode           string         `json:"login_code"`
}

// Queries for internal/sales (Phase 5A).
//
// Authority, role, and advisory-lock queries are slice-local by ADR-007: the
// shared table is shared, the helper logic is not.
func (q *Queries) GetSalesSessionAuthority(ctx context.Context, arg GetSalesSessionAuthorityParams) (GetSalesSessionAuthorityRow, error) {
	row := q.db.QueryRowContext(ctx, getSalesSessionAuthority, arg.ID, arg.StaffIdentityID)
	var i GetSalesSessionAuthorityRow
	err := row.Scan(
		&i.SessionID,
		&i.StaffIdentityID,
		&i.State,
		&i.ActiveWorkspace,
		&i.LastHumanActivityAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.IdentityEnabled,
		&i.DisplayName,
		&i.LoginCode,
	)
	return i, err
}

const getSalesSessionRoles = `-- name: GetSalesSessionRoles :many
SELECT role
FROM staff_operational_roles
WHERE staff_identity_id = $1
ORDER BY role ASC
`

func (q *Queries) GetSalesSessionRoles(ctx context.Context, staffIdentityID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getSalesSessionRoles, staffIdentityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServiceSession = `-- name: GetServiceSession :one
SELECT id, service_number, sequence, service_mode, state, sales_shift_id,
       created_by_staff_identity_id, created_at
FROM service_sessions
WHERE id = $1
`

type GetServiceSessionRow struct {
	ID                       uuid.UUID `json:"id"`
	ServiceNumber            string    `json:"service_number"`
	Sequence                 int32     `json:"sequence"`
	ServiceMode              string    `json:"service_mode"`
	State                    string    `json:"state"`
	SalesShiftID             uuid.UUID `json:"sales_shift_id"`
	CreatedByStaffIdentityID uuid.UUID `json:"created_by_staff_identity_id"`
	CreatedAt                time.Time `json:"created_at"`
}

func (q *Queries) GetServiceSession(ctx context.Context, id uuid.UUID) (GetServiceSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getServiceSession, id)
	var i GetServiceSessionRow
	err := row.Scan(
		&i.ID,
		&i.ServiceNumber,
		&i.Sequence,
		&i.ServiceMode,
		&i.State,
		&i.SalesShiftID,
		&i.CreatedByStaffIdentityID,
		&i.CreatedAt,
	)
	return i, err
}

const insertOrderDraft = `-- name: InsertOrderDraft :one
INSERT INTO order_drafts (service_session_id) VALUES ($1)
RETURNING id, service_session_id, state, created_at
`

func (q *Queries) InsertOrderDraft(ctx context.Context, serviceSessionID uuid.UUID) (OrderDraft, error) {
	row := q.db.QueryRowContext(ctx, insertOrderDraft, serviceSessionID)
	var i OrderDraft
	err := row.Scan(
		&i.ID,
		&i.ServiceSessionID,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const insertServiceSession = `-- name: InsertServiceSession :one
INSERT INTO service_sessions
    (service_number, sequence, service_mode, state,
     created_by_staff_identity_id, sales_shift_id)
VALUES ($1, $2, $3, 'ACTIVE', $4, $5)
RETURNING id, service_number, sequence, service_mode, state, sales_shift_id, created_at
`

type InsertServiceSessionParams struct {
	ServiceNumber            string    `json:"service_number"`
	Sequence                 int32     `json:"sequence"`
	ServiceMode              string    `json:"service_mode"`
	CreatedByStaffIdentityID uuid.UUID `json:"created_by_staff_identity_id"`
	SalesShiftID             uuid.UUID `json:"sales_shift_id"`
}

type InsertServiceSessionRow struct {
	ID            uuid.UUID `json:"id"`
	ServiceNumber string    `json:"service_number"`
	Sequence      int32     `json:"sequence"`
	ServiceMode   string    `json:"service_mode"`
	State         string    `json:"state"`
	SalesShiftID  uuid.UUID `json:"sales_shift_id"`
	CreatedAt     time.Time `json:"created_at"`
}

func (q *Queries) InsertServiceSession(ctx context.Context, arg InsertServiceSessionParams) (InsertServiceSessionRow, error) {
	row := q.db.QueryRowContext(ctx, insertServiceSession,
		arg.ServiceNumber,
		arg.Sequence,
		arg.ServiceMode,
		arg.CreatedByStaffIdentityID,
		arg.SalesShiftID,
	)
	var i InsertServiceSessionRow
	err := row.Scan(
		&i.ID,
		&i.ServiceNumber,
		&i.Sequence,
		&i.ServiceMode,
		&i.State,
		&i.SalesShiftID,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveServiceSessions = `-- name: ListActiveServiceSessions :many
SELECT id, service_number, sequence, service_mode, state, sales_shift_id,
       created_by_staff_identity_id, created_at
FROM service_sessions
WHERE state = 'ACTIVE'
ORDER BY created_at ASC, id ASC
`

type ListActiveServiceSessionsRow struct {
	ID                       uuid.UUID `json:"id"`
	ServiceNumber            string    `json:"service_number"`
	Sequence                 int32     `json:"sequence"`
	ServiceMode              string    `json:"service_mode"`
	State                    string    `json:"state"`
	SalesShiftID             uuid.UUID `json:"sales_shift_id"`
	CreatedByStaffIdentityID uuid.UUID `json:"created_by_staff_identity_id"`
	CreatedAt                time.Time `json:"created_at"`
}

func (q *Queries) ListActiveServiceSessions(ctx context.Context) ([]ListActiveServiceSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveServiceSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveServiceSessionsRow{}
	for rows.Next() {
		var i ListActiveServiceSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceNumber,
			&i.Sequence,
			&i.ServiceMode,
			&i.State,
			&i.SalesShiftID,
			&i.CreatedByStaffIdentityID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftItemModifierOptions = `-- name: ListDraftItemModifierOptions :many
SELECT m.order_draft_item_id, o.id AS option_id, o.name AS option_name,
       o.surcharge_vnd, g.id AS group_id, g.name AS group_name
FROM order_draft_item_modifier_options m
JOIN modifier_options o ON o.id = m.modifier_option_id
JOIN modifier_groups g ON g.id = o.modifier_group_id
JOIN order_draft_items di ON di.id = m.order_draft_item_id
WHERE di.order_draft_id = $1
ORDER BY g.name ASC, o.name ASC, o.id ASC
`

type ListDraftItemModifierOptionsRow struct {
	OrderDraftItemID uuid.UUID `json:"order_draft_item_id"`
	OptionID         uuid.UUID `json:"option_id"`
	OptionName       string    `json:"option_name"`
	SurchargeVnd     int64     `json:"surcharge_vnd"`
	GroupID          uuid.UUID `json:"group_id"`
	GroupName        string    `json:"group_name"`
}

// Ordered by Group then Option name, which is the order the projection emits.
func (q *Queries) ListDraftItemModifierOptions(ctx context.Context, orderDraftID uuid.UUID) ([]ListDraftItemModifierOptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDraftItemModifierOptions, orderDraftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDraftItemModifierOptionsRow{}
	for rows.Next() {
		var i ListDraftItemModifierOptionsRow
		if err := rows.Scan(
			&i.OrderDraftItemID,
			&i.OptionID,
			&i.OptionName,
			&i.SurchargeVnd,
			&i.GroupID,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftItems = `-- name: ListDraftItems :many
SELECT di.id, di.menu_item_id, mi.name AS menu_item_name,
       di.size_id, s.name AS size_name,
       COALESCE((SELECT s.price_vnd), mi.price_vnd) AS price_vnd,
       di.quantity, di.preparation_note, di.modifier_key, di.created_at,
       (mi.available AND mi.retired_at IS NULL
        AND (di.size_id IS NULL OR (s.available AND s.retired_at IS NULL))) AS available
FROM order_draft_items di
JOIN menu_items mi ON mi.id = di.menu_item_id
LEFT JOIN menu_item_sizes s ON s.id = di.size_id
WHERE di.order_draft_id = $1
ORDER BY di.created_at ASC, di.id ASC
`

type ListDraftItemsRow struct {
	ID              uuid.UUID      `json:"id"`
	MenuItemID      uuid.UUID      `json:"menu_item_id"`
	MenuItemName    string         `json:"menu_item_name"`
	SizeID          uuid.NullUUID  `json:"size_id"`
	SizeName        sql.NullString `json:"size_name"`
	PriceVnd        sql.NullInt64  `json:"price_vnd"`
	Quantity        int32          `json:"quantity"`
	PreparationNote sql.NullString `json:"preparation_note"`
	ModifierKey     string         `json:"modifier_key"`
	CreatedAt       time.Time      `json:"created_at"`
	Available       sql.NullBool   `json:"available"`
}

// price_vnd is the Size price when a Size is chosen and the Item price
// otherwise, matching the canonical Menu Price rule. available is read live
// rather than snapshotted: a draft is a live proposal, and an item that became
// unavailable while the customer was deciding must show as such.
//
// price_vnd reads the Size price through a correlated scalar subquery rather
// than the column directly. The subquery returns the same value (it references
// the already-joined row), but sqlc infers scalar subqueries as nullable, so
// COALESCE yields sql.NullInt64 instead of a bare int64 that cannot scan the
// NULL price of a required-Size Item whose Size has not been chosen yet.
func (q *Queries) ListDraftItems(ctx context.Context, orderDraftID uuid.UUID) ([]ListDraftItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDraftItems, orderDraftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDraftItemsRow{}
	for rows.Next() {
		var i ListDraftItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.MenuItemID,
			&i.MenuItemName,
			&i.SizeID,
			&i.SizeName,
			&i.PriceVnd,
			&i.Quantity,
			&i.PreparationNote,
			&i.ModifierKey,
			&i.CreatedAt,
			&i.Available,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceSessionTables = `-- name: ListServiceSessionTables :many
SELECT t.id, t.name, a.sequence
FROM table_assignments a
JOIN tables t ON t.id = a.table_id
WHERE a.service_session_id = $1 AND a.released_at IS NULL
ORDER BY a.sequence ASC
`

type ListServiceSessionTablesRow struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Sequence int32     `json:"sequence"`
}

// Current assignments only. Released rows are history, not occupancy.
func (q *Queries) ListServiceSessionTables(ctx context.Context, serviceSessionID uuid.UUID) ([]ListServiceSessionTablesRow, error) {
	rows, err := q.db.QueryContext(ctx, listServiceSessionTables, serviceSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceSessionTablesRow{}
	for rows.Next() {
		var i ListServiceSessionTablesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Sequence); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesAdvisoryLock = `-- name: SalesAdvisoryLock :exec
SELECT pg_advisory_xact_lock($1)
`

func (q *Queries) SalesAdvisoryLock(ctx context.Context, pgAdvisoryXactLock int64) error {
	_, err := q.db.ExecContext(ctx, salesAdvisoryLock, pgAdvisoryXactLock)
	return err
}
