// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const deleteDraftItem = `-- name: DeleteDraftItem :exec
DELETE FROM order_draft_items WHERE id = $1
`

func (q *Queries) DeleteDraftItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDraftItem, id)
	return err
}

const deleteDraftItemModifierOptions = `-- name: DeleteDraftItemModifierOptions :exec
DELETE FROM order_draft_item_modifier_options WHERE order_draft_item_id = $1
`

func (q *Queries) DeleteDraftItemModifierOptions(ctx context.Context, orderDraftItemID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDraftItemModifierOptions, orderDraftItemID)
	return err
}

const findBlockingDraft = `-- name: FindBlockingDraft :one
SELECT id
FROM order_drafts
WHERE service_session_id = $1
  AND state IN ('EDITABLE', 'COMMITTED')
ORDER BY created_at ASC, id ASC
LIMIT 1
FOR UPDATE
`

// A draft that prevents a new one opening: EDITABLE, or COMMITTED without a
// corresponding Order.
//
// 5B has no orders table, so the second clause matches every COMMITTED draft
// and a Session that has committed once cannot open another draft. That dead
// end is deliberate and disappears when 5D adds the orders join here: the
// rule exists to stop staff stacking rounds ahead of the kitchen, and
// relaxing it now would ship a rule no phase wants. See the spec's accepted
// consequences.
func (q *Queries) FindBlockingDraft(ctx context.Context, serviceSessionID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, findBlockingDraft, serviceSessionID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findDraftItemByComposition = `-- name: FindDraftItemByComposition :one
SELECT id, quantity
FROM order_draft_items
WHERE order_draft_id = $1
  AND menu_item_id = $2
  AND size_key = COALESCE($4::uuid::text, '')
  AND note_key = COALESCE($5::text, '')
  AND modifier_key = $3
`

type FindDraftItemByCompositionParams struct {
	OrderDraftID    uuid.UUID      `json:"order_draft_id"`
	MenuItemID      uuid.UUID      `json:"menu_item_id"`
	ModifierKey     string         `json:"modifier_key"`
	SizeID          uuid.NullUUID  `json:"size_id"`
	PreparationNote sql.NullString `json:"preparation_note"`
}

type FindDraftItemByCompositionRow struct {
	ID       uuid.UUID `json:"id"`
	Quantity int32     `json:"quantity"`
}

func (q *Queries) FindDraftItemByComposition(ctx context.Context, arg FindDraftItemByCompositionParams) (FindDraftItemByCompositionRow, error) {
	row := q.db.QueryRowContext(ctx, findDraftItemByComposition,
		arg.OrderDraftID,
		arg.MenuItemID,
		arg.ModifierKey,
		arg.SizeID,
		arg.PreparationNote,
	)
	var i FindDraftItemByCompositionRow
	err := row.Scan(&i.ID, &i.Quantity)
	return i, err
}

const findDraftItemByCompositionExcluding = `-- name: FindDraftItemByCompositionExcluding :one
SELECT id, quantity
FROM order_draft_items
WHERE order_draft_id = $1
  AND menu_item_id = $2
  AND size_key = COALESCE($5::uuid::text, '')
  AND note_key = COALESCE($6::text, '')
  AND modifier_key = $3
  AND id <> $4
`

type FindDraftItemByCompositionExcludingParams struct {
	OrderDraftID    uuid.UUID      `json:"order_draft_id"`
	MenuItemID      uuid.UUID      `json:"menu_item_id"`
	ModifierKey     string         `json:"modifier_key"`
	ID              uuid.UUID      `json:"id"`
	SizeID          uuid.NullUUID  `json:"size_id"`
	PreparationNote sql.NullString `json:"preparation_note"`
}

type FindDraftItemByCompositionExcludingRow struct {
	ID       uuid.UUID `json:"id"`
	Quantity int32     `json:"quantity"`
}

// findDraftItemByComposition plus an id <> $n clause, so the row being edited
// never matches itself. A separate query rather than a nullable exclusion
// parameter keeps the add path's query untouched.
func (q *Queries) FindDraftItemByCompositionExcluding(ctx context.Context, arg FindDraftItemByCompositionExcludingParams) (FindDraftItemByCompositionExcludingRow, error) {
	row := q.db.QueryRowContext(ctx, findDraftItemByCompositionExcluding,
		arg.OrderDraftID,
		arg.MenuItemID,
		arg.ModifierKey,
		arg.ID,
		arg.SizeID,
		arg.PreparationNote,
	)
	var i FindDraftItemByCompositionExcludingRow
	err := row.Scan(&i.ID, &i.Quantity)
	return i, err
}

const getEditableDraft = `-- name: GetEditableDraft :one
SELECT id, service_session_id, state, created_at
FROM order_drafts
WHERE service_session_id = $1 AND state = 'EDITABLE'
`

type GetEditableDraftRow struct {
	ID               uuid.UUID `json:"id"`
	ServiceSessionID uuid.UUID `json:"service_session_id"`
	State            string    `json:"state"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) GetEditableDraft(ctx context.Context, serviceSessionID uuid.UUID) (GetEditableDraftRow, error) {
	row := q.db.QueryRowContext(ctx, getEditableDraft, serviceSessionID)
	var i GetEditableDraftRow
	err := row.Scan(
		&i.ID,
		&i.ServiceSessionID,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const getHighestAssignmentSequence = `-- name: GetHighestAssignmentSequence :one
SELECT COALESCE(MAX(sequence), -1)::int AS highest
FROM table_assignments
WHERE service_session_id = $1
`

// Includes released assignments, so a released sequence number is never
// reused and the audit trail stays unambiguous.
func (q *Queries) GetHighestAssignmentSequence(ctx context.Context, serviceSessionID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getHighestAssignmentSequence, serviceSessionID)
	var highest int32
	err := row.Scan(&highest)
	return highest, err
}

const getNextServiceSequence = `-- name: GetNextServiceSequence :one
SELECT COALESCE(MAX(sequence), 0)::int + 1 AS next_sequence
FROM service_sessions
WHERE sales_shift_id = $1
`

// Callers MUST hold the advisory lock on the Sales Shift before running this.
// Without it two concurrent opens read the same maximum and one loses to the
// unique index.
func (q *Queries) GetNextServiceSequence(ctx context.Context, salesShiftID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getNextServiceSequence, salesShiftID)
	var next_sequence int32
	err := row.Scan(&next_sequence)
	return next_sequence, err
}

const getOpenSalesShiftID = `-- name: GetOpenSalesShiftID :one
SELECT id FROM sales_shifts WHERE state = 'OPEN' LIMIT 1
`

// Sales reads the Shift-owned table through its own query rather than
// importing internal/shift, per ADR-006's precedent.
func (q *Queries) GetOpenSalesShiftID(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getOpenSalesShiftID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getOrderDraftCheckTarget = `-- name: GetOrderDraftCheckTarget :one
SELECT check_target FROM order_drafts WHERE id = $1
`

func (q *Queries) GetOrderDraftCheckTarget(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getOrderDraftCheckTarget, id)
	var check_target string
	err := row.Scan(&check_target)
	return check_target, err
}

const getSalesSessionAuthority = `-- name: GetSalesSessionAuthority :one

SELECT s.id AS session_id, s.staff_identity_id, s.state, s.active_workspace,
       s.last_human_activity_at, s.expires_at, s.revoked_at,
       i.enabled AS identity_enabled, i.display_name, i.login_code
FROM staff_access_sessions s
JOIN staff_identities i ON i.id = s.staff_identity_id
WHERE s.id = $1 AND s.staff_identity_id = $2
`

type GetSalesSessionAuthorityParams struct {
	ID              uuid.UUID `json:"id"`
	StaffIdentityID uuid.UUID `json:"staff_identity_id"`
}

type GetSalesSessionAuthorityRow struct {
	SessionID           uuid.UUID      `json:"session_id"`
	StaffIdentityID     uuid.UUID      `json:"staff_identity_id"`
	State               string         `json:"state"`
	ActiveWorkspace     sql.NullString `json:"active_workspace"`
	LastHumanActivityAt time.Time      `json:"last_human_activity_at"`
	ExpiresAt           time.Time      `json:"expires_at"`
	RevokedAt           sql.NullTime   `json:"revoked_at"`
	IdentityEnabled     bool           `json:"identity_enabled"`
	DisplayName         string         `json:"display_name"`
	LoginCode           string         `json:"login_code"`
}

// Queries for internal/sales (Phase 5A).
//
// Authority, role, and advisory-lock queries are slice-local by ADR-007: the
// shared table is shared, the helper logic is not.
func (q *Queries) GetSalesSessionAuthority(ctx context.Context, arg GetSalesSessionAuthorityParams) (GetSalesSessionAuthorityRow, error) {
	row := q.db.QueryRowContext(ctx, getSalesSessionAuthority, arg.ID, arg.StaffIdentityID)
	var i GetSalesSessionAuthorityRow
	err := row.Scan(
		&i.SessionID,
		&i.StaffIdentityID,
		&i.State,
		&i.ActiveWorkspace,
		&i.LastHumanActivityAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.IdentityEnabled,
		&i.DisplayName,
		&i.LoginCode,
	)
	return i, err
}

const getSalesSessionRoles = `-- name: GetSalesSessionRoles :many
SELECT role
FROM staff_operational_roles
WHERE staff_identity_id = $1
ORDER BY role ASC
`

func (q *Queries) GetSalesSessionRoles(ctx context.Context, staffIdentityID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getSalesSessionRoles, staffIdentityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSalesShiftStateByID = `-- name: GetSalesShiftStateByID :one
SELECT state FROM sales_shifts WHERE id = $1
`

func (q *Queries) GetSalesShiftStateByID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getSalesShiftStateByID, id)
	var state string
	err := row.Scan(&state)
	return state, err
}

const getServiceSession = `-- name: GetServiceSession :one
SELECT id, service_number, sequence, service_mode, state, sales_shift_id,
       created_by_staff_identity_id, created_at
FROM service_sessions
WHERE id = $1
`

type GetServiceSessionRow struct {
	ID                       uuid.UUID `json:"id"`
	ServiceNumber            string    `json:"service_number"`
	Sequence                 int32     `json:"sequence"`
	ServiceMode              string    `json:"service_mode"`
	State                    string    `json:"state"`
	SalesShiftID             uuid.UUID `json:"sales_shift_id"`
	CreatedByStaffIdentityID uuid.UUID `json:"created_by_staff_identity_id"`
	CreatedAt                time.Time `json:"created_at"`
}

func (q *Queries) GetServiceSession(ctx context.Context, id uuid.UUID) (GetServiceSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getServiceSession, id)
	var i GetServiceSessionRow
	err := row.Scan(
		&i.ID,
		&i.ServiceNumber,
		&i.Sequence,
		&i.ServiceMode,
		&i.State,
		&i.SalesShiftID,
		&i.CreatedByStaffIdentityID,
		&i.CreatedAt,
	)
	return i, err
}

const insertChargeAllocation = `-- name: InsertChargeAllocation :exec
INSERT INTO charge_allocations (committed_item_id, check_id, quantity, created_at)
VALUES ($1, $2, $3, $4)
`

type InsertChargeAllocationParams struct {
	CommittedItemID uuid.UUID `json:"committed_item_id"`
	CheckID         uuid.UUID `json:"check_id"`
	Quantity        int32     `json:"quantity"`
	CreatedAt       time.Time `json:"created_at"`
}

func (q *Queries) InsertChargeAllocation(ctx context.Context, arg InsertChargeAllocationParams) error {
	_, err := q.db.ExecContext(ctx, insertChargeAllocation,
		arg.CommittedItemID,
		arg.CheckID,
		arg.Quantity,
		arg.CreatedAt,
	)
	return err
}

const insertCheck = `-- name: InsertCheck :one
INSERT INTO checks (service_session_id, created_at)
VALUES ($1, $2)
RETURNING id, charge_vnd
`

type InsertCheckParams struct {
	ServiceSessionID uuid.UUID `json:"service_session_id"`
	CreatedAt        time.Time `json:"created_at"`
}

type InsertCheckRow struct {
	ID        uuid.UUID `json:"id"`
	ChargeVnd int64     `json:"charge_vnd"`
}

func (q *Queries) InsertCheck(ctx context.Context, arg InsertCheckParams) (InsertCheckRow, error) {
	row := q.db.QueryRowContext(ctx, insertCheck, arg.ServiceSessionID, arg.CreatedAt)
	var i InsertCheckRow
	err := row.Scan(&i.ID, &i.ChargeVnd)
	return i, err
}

const insertCommittedItem = `-- name: InsertCommittedItem :one
INSERT INTO committed_items (
    order_draft_id, source_draft_item_id, menu_item_id, category_name,
    item_name, size_name, quantity, unit_price_vnd, total_vnd,
    preparation_note, committed_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type InsertCommittedItemParams struct {
	OrderDraftID      uuid.UUID      `json:"order_draft_id"`
	SourceDraftItemID uuid.UUID      `json:"source_draft_item_id"`
	MenuItemID        uuid.UUID      `json:"menu_item_id"`
	CategoryName      string         `json:"category_name"`
	ItemName          string         `json:"item_name"`
	SizeName          sql.NullString `json:"size_name"`
	Quantity          int32          `json:"quantity"`
	UnitPriceVnd      int64          `json:"unit_price_vnd"`
	TotalVnd          int64          `json:"total_vnd"`
	PreparationNote   sql.NullString `json:"preparation_note"`
	CommittedAt       time.Time      `json:"committed_at"`
}

func (q *Queries) InsertCommittedItem(ctx context.Context, arg InsertCommittedItemParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insertCommittedItem,
		arg.OrderDraftID,
		arg.SourceDraftItemID,
		arg.MenuItemID,
		arg.CategoryName,
		arg.ItemName,
		arg.SizeName,
		arg.Quantity,
		arg.UnitPriceVnd,
		arg.TotalVnd,
		arg.PreparationNote,
		arg.CommittedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertCommittedItemModifierOption = `-- name: InsertCommittedItemModifierOption :exec
INSERT INTO committed_item_modifier_options (
    committed_item_id, modifier_group_id, modifier_group_name,
    modifier_option_id, modifier_option_name, surcharge_vnd
) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertCommittedItemModifierOptionParams struct {
	CommittedItemID    uuid.UUID `json:"committed_item_id"`
	ModifierGroupID    uuid.UUID `json:"modifier_group_id"`
	ModifierGroupName  string    `json:"modifier_group_name"`
	ModifierOptionID   uuid.UUID `json:"modifier_option_id"`
	ModifierOptionName string    `json:"modifier_option_name"`
	SurchargeVnd       int64     `json:"surcharge_vnd"`
}

func (q *Queries) InsertCommittedItemModifierOption(ctx context.Context, arg InsertCommittedItemModifierOptionParams) error {
	_, err := q.db.ExecContext(ctx, insertCommittedItemModifierOption,
		arg.CommittedItemID,
		arg.ModifierGroupID,
		arg.ModifierGroupName,
		arg.ModifierOptionID,
		arg.ModifierOptionName,
		arg.SurchargeVnd,
	)
	return err
}

const insertDraftItem = `-- name: InsertDraftItem :one
INSERT INTO order_draft_items
    (order_draft_id, menu_item_id, size_id, preparation_note, modifier_key, quantity)
VALUES ($1, $2, $3, $4, $5, 1)
RETURNING id, quantity
`

type InsertDraftItemParams struct {
	OrderDraftID    uuid.UUID      `json:"order_draft_id"`
	MenuItemID      uuid.UUID      `json:"menu_item_id"`
	SizeID          uuid.NullUUID  `json:"size_id"`
	PreparationNote sql.NullString `json:"preparation_note"`
	ModifierKey     string         `json:"modifier_key"`
}

type InsertDraftItemRow struct {
	ID       uuid.UUID `json:"id"`
	Quantity int32     `json:"quantity"`
}

func (q *Queries) InsertDraftItem(ctx context.Context, arg InsertDraftItemParams) (InsertDraftItemRow, error) {
	row := q.db.QueryRowContext(ctx, insertDraftItem,
		arg.OrderDraftID,
		arg.MenuItemID,
		arg.SizeID,
		arg.PreparationNote,
		arg.ModifierKey,
	)
	var i InsertDraftItemRow
	err := row.Scan(&i.ID, &i.Quantity)
	return i, err
}

const insertDraftItemModifierOption = `-- name: InsertDraftItemModifierOption :exec
INSERT INTO order_draft_item_modifier_options (order_draft_item_id, modifier_option_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertDraftItemModifierOptionParams struct {
	OrderDraftItemID uuid.UUID `json:"order_draft_item_id"`
	ModifierOptionID uuid.UUID `json:"modifier_option_id"`
}

func (q *Queries) InsertDraftItemModifierOption(ctx context.Context, arg InsertDraftItemModifierOptionParams) error {
	_, err := q.db.ExecContext(ctx, insertDraftItemModifierOption, arg.OrderDraftItemID, arg.ModifierOptionID)
	return err
}

const insertOrderDraft = `-- name: InsertOrderDraft :one
INSERT INTO order_drafts (service_session_id) VALUES ($1)
RETURNING id, service_session_id, state, created_at
`

type InsertOrderDraftRow struct {
	ID               uuid.UUID `json:"id"`
	ServiceSessionID uuid.UUID `json:"service_session_id"`
	State            string    `json:"state"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) InsertOrderDraft(ctx context.Context, serviceSessionID uuid.UUID) (InsertOrderDraftRow, error) {
	row := q.db.QueryRowContext(ctx, insertOrderDraft, serviceSessionID)
	var i InsertOrderDraftRow
	err := row.Scan(
		&i.ID,
		&i.ServiceSessionID,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const insertOrderDraftForSession = `-- name: InsertOrderDraftForSession :one
INSERT INTO order_drafts (service_session_id, created_at)
VALUES ($1, $2)
RETURNING id, state, check_target
`

type InsertOrderDraftForSessionParams struct {
	ServiceSessionID uuid.UUID `json:"service_session_id"`
	CreatedAt        time.Time `json:"created_at"`
}

type InsertOrderDraftForSessionRow struct {
	ID          uuid.UUID `json:"id"`
	State       string    `json:"state"`
	CheckTarget string    `json:"check_target"`
}

func (q *Queries) InsertOrderDraftForSession(ctx context.Context, arg InsertOrderDraftForSessionParams) (InsertOrderDraftForSessionRow, error) {
	row := q.db.QueryRowContext(ctx, insertOrderDraftForSession, arg.ServiceSessionID, arg.CreatedAt)
	var i InsertOrderDraftForSessionRow
	err := row.Scan(&i.ID, &i.State, &i.CheckTarget)
	return i, err
}

const insertServiceSession = `-- name: InsertServiceSession :one
INSERT INTO service_sessions
    (service_number, sequence, service_mode, state,
     created_by_staff_identity_id, sales_shift_id)
VALUES ($1, $2, $3, 'ACTIVE', $4, $5)
RETURNING id, service_number, sequence, service_mode, state, sales_shift_id, created_at
`

type InsertServiceSessionParams struct {
	ServiceNumber            string    `json:"service_number"`
	Sequence                 int32     `json:"sequence"`
	ServiceMode              string    `json:"service_mode"`
	CreatedByStaffIdentityID uuid.UUID `json:"created_by_staff_identity_id"`
	SalesShiftID             uuid.UUID `json:"sales_shift_id"`
}

type InsertServiceSessionRow struct {
	ID            uuid.UUID `json:"id"`
	ServiceNumber string    `json:"service_number"`
	Sequence      int32     `json:"sequence"`
	ServiceMode   string    `json:"service_mode"`
	State         string    `json:"state"`
	SalesShiftID  uuid.UUID `json:"sales_shift_id"`
	CreatedAt     time.Time `json:"created_at"`
}

func (q *Queries) InsertServiceSession(ctx context.Context, arg InsertServiceSessionParams) (InsertServiceSessionRow, error) {
	row := q.db.QueryRowContext(ctx, insertServiceSession,
		arg.ServiceNumber,
		arg.Sequence,
		arg.ServiceMode,
		arg.CreatedByStaffIdentityID,
		arg.SalesShiftID,
	)
	var i InsertServiceSessionRow
	err := row.Scan(
		&i.ID,
		&i.ServiceNumber,
		&i.Sequence,
		&i.ServiceMode,
		&i.State,
		&i.SalesShiftID,
		&i.CreatedAt,
	)
	return i, err
}

const insertTableAssignmentsBatch = `-- name: InsertTableAssignmentsBatch :many
INSERT INTO table_assignments (table_id, service_session_id, assigned_by_staff_identity_id, sequence)
SELECT tid.val, $2::uuid, $3::uuid, seq.val
FROM unnest($1::uuid[]) WITH ORDINALITY AS tid(val, ord)
JOIN unnest($4::int[]) WITH ORDINALITY AS seq(val, ord) ON seq.ord = tid.ord
RETURNING id, table_id, service_session_id, sequence, assigned_at
`

type InsertTableAssignmentsBatchParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Column2 uuid.UUID   `json:"column_2"`
	Column3 uuid.UUID   `json:"column_3"`
	Column4 []int32     `json:"column_4"`
}

type InsertTableAssignmentsBatchRow struct {
	ID               uuid.UUID `json:"id"`
	TableID          uuid.UUID `json:"table_id"`
	ServiceSessionID uuid.UUID `json:"service_session_id"`
	Sequence         int32     `json:"sequence"`
	AssignedAt       time.Time `json:"assigned_at"`
}

// Batches assignTables' per-Table insert loop into one round trip. Two
// single-array unnests joined by WITH ORDINALITY zip table_ids and sequences
// into rows in lockstep, so row i of the result is table_ids[i] assigned at
// sequences[i]; the caller relies on getting exactly len(table_ids) rows back
// in that order.
func (q *Queries) InsertTableAssignmentsBatch(ctx context.Context, arg InsertTableAssignmentsBatchParams) ([]InsertTableAssignmentsBatchRow, error) {
	rows, err := q.db.QueryContext(ctx, insertTableAssignmentsBatch,
		pq.Array(arg.Column1),
		arg.Column2,
		arg.Column3,
		pq.Array(arg.Column4),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InsertTableAssignmentsBatchRow{}
	for rows.Next() {
		var i InsertTableAssignmentsBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.TableID,
			&i.ServiceSessionID,
			&i.Sequence,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveServiceSessions = `-- name: ListActiveServiceSessions :many
SELECT id, service_number, sequence, service_mode, state, sales_shift_id,
       created_by_staff_identity_id, created_at
FROM service_sessions
WHERE state = 'ACTIVE'
ORDER BY created_at ASC, id ASC
`

type ListActiveServiceSessionsRow struct {
	ID                       uuid.UUID `json:"id"`
	ServiceNumber            string    `json:"service_number"`
	Sequence                 int32     `json:"sequence"`
	ServiceMode              string    `json:"service_mode"`
	State                    string    `json:"state"`
	SalesShiftID             uuid.UUID `json:"sales_shift_id"`
	CreatedByStaffIdentityID uuid.UUID `json:"created_by_staff_identity_id"`
	CreatedAt                time.Time `json:"created_at"`
}

func (q *Queries) ListActiveServiceSessions(ctx context.Context) ([]ListActiveServiceSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveServiceSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveServiceSessionsRow{}
	for rows.Next() {
		var i ListActiveServiceSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceNumber,
			&i.Sequence,
			&i.ServiceMode,
			&i.State,
			&i.SalesShiftID,
			&i.CreatedByStaffIdentityID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckAllocations = `-- name: ListCheckAllocations :many
SELECT ca.id, ca.quantity AS allocated_quantity, ca.created_at,
       ci.id AS committed_item_id, ci.menu_item_id, ci.category_name,
       ci.item_name, ci.size_name, ci.quantity AS committed_quantity,
       ci.unit_price_vnd, ci.total_vnd AS committed_total_vnd,
       ci.preparation_note
FROM charge_allocations ca
JOIN committed_items ci ON ci.id = ca.committed_item_id
WHERE ca.check_id = $1
ORDER BY ci.committed_at ASC, ci.id ASC
`

type ListCheckAllocationsRow struct {
	ID                uuid.UUID      `json:"id"`
	AllocatedQuantity int32          `json:"allocated_quantity"`
	CreatedAt         time.Time      `json:"created_at"`
	CommittedItemID   uuid.UUID      `json:"committed_item_id"`
	MenuItemID        uuid.UUID      `json:"menu_item_id"`
	CategoryName      string         `json:"category_name"`
	ItemName          string         `json:"item_name"`
	SizeName          sql.NullString `json:"size_name"`
	CommittedQuantity int32          `json:"committed_quantity"`
	UnitPriceVnd      int64          `json:"unit_price_vnd"`
	CommittedTotalVnd int64          `json:"committed_total_vnd"`
	PreparationNote   sql.NullString `json:"preparation_note"`
}

func (q *Queries) ListCheckAllocations(ctx context.Context, checkID uuid.UUID) ([]ListCheckAllocationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCheckAllocations, checkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCheckAllocationsRow{}
	for rows.Next() {
		var i ListCheckAllocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.AllocatedQuantity,
			&i.CreatedAt,
			&i.CommittedItemID,
			&i.MenuItemID,
			&i.CategoryName,
			&i.ItemName,
			&i.SizeName,
			&i.CommittedQuantity,
			&i.UnitPriceVnd,
			&i.CommittedTotalVnd,
			&i.PreparationNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommittedItemModifiers = `-- name: ListCommittedItemModifiers :many
SELECT committed_item_id, modifier_group_id, modifier_group_name,
       modifier_option_id, modifier_option_name, surcharge_vnd
FROM committed_item_modifier_options
WHERE committed_item_id = ANY($1::uuid[])
ORDER BY modifier_group_name ASC, modifier_option_name ASC
`

type ListCommittedItemModifiersRow struct {
	CommittedItemID    uuid.UUID `json:"committed_item_id"`
	ModifierGroupID    uuid.UUID `json:"modifier_group_id"`
	ModifierGroupName  string    `json:"modifier_group_name"`
	ModifierOptionID   uuid.UUID `json:"modifier_option_id"`
	ModifierOptionName string    `json:"modifier_option_name"`
	SurchargeVnd       int64     `json:"surcharge_vnd"`
}

func (q *Queries) ListCommittedItemModifiers(ctx context.Context, committedItemIds []uuid.UUID) ([]ListCommittedItemModifiersRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommittedItemModifiers, pq.Array(committedItemIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommittedItemModifiersRow{}
	for rows.Next() {
		var i ListCommittedItemModifiersRow
		if err := rows.Scan(
			&i.CommittedItemID,
			&i.ModifierGroupID,
			&i.ModifierGroupName,
			&i.ModifierOptionID,
			&i.ModifierOptionName,
			&i.SurchargeVnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDefaultModifierOptionIDs = `-- name: ListDefaultModifierOptionIDs :many
SELECT DISTINCT o.id
FROM modifier_group_default_options d
JOIN modifier_options o ON o.id = d.modifier_option_id
JOIN modifier_groups g ON g.id = o.modifier_group_id
WHERE d.modifier_group_id = ANY($1::uuid[])
  AND o.available
  AND o.retired_at IS NULL
  AND g.retired_at IS NULL
ORDER BY o.id ASC
`

// Declared defaults of the given Groups, filtered to what is currently
// selectable. A retired Group's defaults never apply.
func (q *Queries) ListDefaultModifierOptionIDs(ctx context.Context, groupIds []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listDefaultModifierOptionIDs, pq.Array(groupIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftItemModifierOptions = `-- name: ListDraftItemModifierOptions :many
SELECT m.order_draft_item_id, o.id AS option_id, o.name AS option_name,
       o.surcharge_vnd, g.id AS group_id, g.name AS group_name
FROM order_draft_item_modifier_options m
JOIN modifier_options o ON o.id = m.modifier_option_id
JOIN modifier_groups g ON g.id = o.modifier_group_id
JOIN order_draft_items di ON di.id = m.order_draft_item_id
WHERE di.order_draft_id = $1
ORDER BY g.name ASC, o.name ASC, o.id ASC
`

type ListDraftItemModifierOptionsRow struct {
	OrderDraftItemID uuid.UUID `json:"order_draft_item_id"`
	OptionID         uuid.UUID `json:"option_id"`
	OptionName       string    `json:"option_name"`
	SurchargeVnd     int64     `json:"surcharge_vnd"`
	GroupID          uuid.UUID `json:"group_id"`
	GroupName        string    `json:"group_name"`
}

// Ordered by Group then Option name, which is the order the projection emits.
func (q *Queries) ListDraftItemModifierOptions(ctx context.Context, orderDraftID uuid.UUID) ([]ListDraftItemModifierOptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDraftItemModifierOptions, orderDraftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDraftItemModifierOptionsRow{}
	for rows.Next() {
		var i ListDraftItemModifierOptionsRow
		if err := rows.Scan(
			&i.OrderDraftItemID,
			&i.OptionID,
			&i.OptionName,
			&i.SurchargeVnd,
			&i.GroupID,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftItemOptionIDs = `-- name: ListDraftItemOptionIDs :many
SELECT modifier_option_id
FROM order_draft_item_modifier_options
WHERE order_draft_item_id = $1
ORDER BY modifier_option_id ASC
`

func (q *Queries) ListDraftItemOptionIDs(ctx context.Context, orderDraftItemID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listDraftItemOptionIDs, orderDraftItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var modifier_option_id uuid.UUID
		if err := rows.Scan(&modifier_option_id); err != nil {
			return nil, err
		}
		items = append(items, modifier_option_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftItemOptionsForCommit = `-- name: ListDraftItemOptionsForCommit :many
SELECT dio.order_draft_item_id, o.id AS option_id, o.name AS option_name,
       o.surcharge_vnd, o.available,
       (o.retired_at IS NOT NULL) AS option_retired,
       g.id AS group_id, g.name AS group_name,
       (g.retired_at IS NOT NULL) AS group_retired
FROM order_draft_item_modifier_options dio
JOIN modifier_options o ON o.id = dio.modifier_option_id
JOIN modifier_groups g ON g.id = o.modifier_group_id
WHERE dio.order_draft_item_id = ANY($1::uuid[])
ORDER BY g.name ASC, o.name ASC, o.id ASC
`

type ListDraftItemOptionsForCommitRow struct {
	OrderDraftItemID uuid.UUID   `json:"order_draft_item_id"`
	OptionID         uuid.UUID   `json:"option_id"`
	OptionName       string      `json:"option_name"`
	SurchargeVnd     int64       `json:"surcharge_vnd"`
	Available        bool        `json:"available"`
	OptionRetired    interface{} `json:"option_retired"`
	GroupID          uuid.UUID   `json:"group_id"`
	GroupName        string      `json:"group_name"`
	GroupRetired     interface{} `json:"group_retired"`
}

// The selected Options of the given draft items, with the Group facts the
// Commit rules need.
func (q *Queries) ListDraftItemOptionsForCommit(ctx context.Context, draftItemIds []uuid.UUID) ([]ListDraftItemOptionsForCommitRow, error) {
	rows, err := q.db.QueryContext(ctx, listDraftItemOptionsForCommit, pq.Array(draftItemIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDraftItemOptionsForCommitRow{}
	for rows.Next() {
		var i ListDraftItemOptionsForCommitRow
		if err := rows.Scan(
			&i.OrderDraftItemID,
			&i.OptionID,
			&i.OptionName,
			&i.SurchargeVnd,
			&i.Available,
			&i.OptionRetired,
			&i.GroupID,
			&i.GroupName,
			&i.GroupRetired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftItems = `-- name: ListDraftItems :many
SELECT di.id, di.menu_item_id, mi.name AS menu_item_name,
       di.size_id, s.name AS size_name,
       COALESCE((SELECT s.price_vnd), mi.price_vnd) AS price_vnd,
       di.quantity, di.preparation_note, di.modifier_key, di.created_at,
       (mi.available AND mi.retired_at IS NULL
        AND (di.size_id IS NULL OR (s.available AND s.retired_at IS NULL))) AS available
FROM order_draft_items di
JOIN menu_items mi ON mi.id = di.menu_item_id
LEFT JOIN menu_item_sizes s ON s.id = di.size_id
WHERE di.order_draft_id = $1
ORDER BY di.created_at ASC, di.id ASC
`

type ListDraftItemsRow struct {
	ID              uuid.UUID      `json:"id"`
	MenuItemID      uuid.UUID      `json:"menu_item_id"`
	MenuItemName    string         `json:"menu_item_name"`
	SizeID          uuid.NullUUID  `json:"size_id"`
	SizeName        sql.NullString `json:"size_name"`
	PriceVnd        sql.NullInt64  `json:"price_vnd"`
	Quantity        int32          `json:"quantity"`
	PreparationNote sql.NullString `json:"preparation_note"`
	ModifierKey     string         `json:"modifier_key"`
	CreatedAt       time.Time      `json:"created_at"`
	Available       sql.NullBool   `json:"available"`
}

// price_vnd is the Size price when a Size is chosen and the Item price
// otherwise, matching the canonical Menu Price rule. available is read live
// rather than snapshotted: a draft is a live proposal, and an item that became
// unavailable while the customer was deciding must show as such.
//
// price_vnd reads the Size price through a correlated scalar subquery rather
// than the column directly. The subquery returns the same value (it references
// the already-joined row), but sqlc infers scalar subqueries as nullable, so
// COALESCE yields sql.NullInt64 instead of a bare int64 that cannot scan the
// NULL price of a required-Size Item whose Size has not been chosen yet.
func (q *Queries) ListDraftItems(ctx context.Context, orderDraftID uuid.UUID) ([]ListDraftItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDraftItems, orderDraftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDraftItemsRow{}
	for rows.Next() {
		var i ListDraftItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.MenuItemID,
			&i.MenuItemName,
			&i.SizeID,
			&i.SizeName,
			&i.PriceVnd,
			&i.Quantity,
			&i.PreparationNote,
			&i.ModifierKey,
			&i.CreatedAt,
			&i.Available,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEffectiveModifierGroupIDs = `-- name: ListEffectiveModifierGroupIDs :many
WITH target AS (
    SELECT id, category_id FROM menu_items WHERE id = $1
),
inherited AS (
    SELECT cmg.modifier_group_id
    FROM category_modifier_groups cmg
    JOIN target ON target.category_id = cmg.menu_category_id
    WHERE NOT EXISTS (
        SELECT 1
        FROM item_modifier_group_exclusions ex
        WHERE ex.menu_item_id = (SELECT id FROM target)
          AND ex.modifier_group_id = cmg.modifier_group_id
    )
),
direct AS (
    SELECT img.modifier_group_id
    FROM item_modifier_groups img
    JOIN target ON target.id = img.menu_item_id
)
SELECT modifier_group_id
FROM (
    SELECT modifier_group_id FROM inherited
    UNION
    SELECT modifier_group_id FROM direct
) g
ORDER BY modifier_group_id ASC
`

// (inherited - exclusions) + direct, for one Menu Item.
//
// internal/catalog computes the same set in the exported pure function
// EffectiveGroupIDs. Sales does not import it: MIGRATE_PLAN section 4.1
// forbids importing another slice, and ADR-006 established reading another
// slice's tables through one's own query. Expressing the algebra once in SQL
// keeps the duplication to one function against one query, which
// TestSalesResolutionMatchesCatalog pins together. See ADR-012.
func (q *Queries) ListEffectiveModifierGroupIDs(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listEffectiveModifierGroupIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var modifier_group_id uuid.UUID
		if err := rows.Scan(&modifier_group_id); err != nil {
			return nil, err
		}
		items = append(items, modifier_group_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEffectiveModifierGroupsForCommit = `-- name: ListEffectiveModifierGroupsForCommit :many
WITH targets AS (
    SELECT id, category_id FROM menu_items
    WHERE id = ANY($1::uuid[])
),
inherited AS (
    SELECT t.id AS menu_item_id, cmg.modifier_group_id
    FROM targets t
    JOIN category_modifier_groups cmg ON cmg.menu_category_id = t.category_id
    WHERE NOT EXISTS (
        SELECT 1 FROM item_modifier_group_exclusions ex
        WHERE ex.menu_item_id = t.id
          AND ex.modifier_group_id = cmg.modifier_group_id
    )
),
direct AS (
    SELECT t.id AS menu_item_id, img.modifier_group_id
    FROM targets t
    JOIN item_modifier_groups img ON img.menu_item_id = t.id
),
effective AS (
    SELECT menu_item_id, modifier_group_id FROM inherited
    UNION
    SELECT menu_item_id, modifier_group_id FROM direct
)
SELECT e.menu_item_id, e.modifier_group_id, g.name AS group_name,
       g.min_selections, g.max_selections,
       (g.retired_at IS NOT NULL) AS group_retired
FROM effective e
JOIN modifier_groups g ON g.id = e.modifier_group_id
ORDER BY e.menu_item_id ASC, e.modifier_group_id ASC
`

type ListEffectiveModifierGroupsForCommitRow struct {
	MenuItemID      uuid.UUID   `json:"menu_item_id"`
	ModifierGroupID uuid.UUID   `json:"modifier_group_id"`
	GroupName       string      `json:"group_name"`
	MinSelections   int32       `json:"min_selections"`
	MaxSelections   int32       `json:"max_selections"`
	GroupRetired    interface{} `json:"group_retired"`
}

// (inherited - exclusions) + direct, for a SET of Menu Items, returning the
// selection rules Commit enforces.
//
// This is the second expression of the algebra ListEffectiveModifierGroupIDs
// already encodes. TestSalesResolutionMatchesCatalog pins both to
// catalog.EffectiveGroupIDs over shared fixtures so they cannot drift. The
// single-item query is left alone: the draft path does not need min/max and
// should not pay for them. See ADR-012.
func (q *Queries) ListEffectiveModifierGroupsForCommit(ctx context.Context, menuItemIds []uuid.UUID) ([]ListEffectiveModifierGroupsForCommitRow, error) {
	rows, err := q.db.QueryContext(ctx, listEffectiveModifierGroupsForCommit, pq.Array(menuItemIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEffectiveModifierGroupsForCommitRow{}
	for rows.Next() {
		var i ListEffectiveModifierGroupsForCommitRow
		if err := rows.Scan(
			&i.MenuItemID,
			&i.ModifierGroupID,
			&i.GroupName,
			&i.MinSelections,
			&i.MaxSelections,
			&i.GroupRetired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModifierOptionsForValidation = `-- name: ListModifierOptionsForValidation :many
SELECT o.id, o.modifier_group_id, o.available,
       (o.retired_at IS NOT NULL) AS option_retired,
       (g.retired_at IS NOT NULL) AS group_retired
FROM modifier_options o
JOIN modifier_groups g ON g.id = o.modifier_group_id
WHERE o.id = ANY($1::uuid[])
`

type ListModifierOptionsForValidationRow struct {
	ID              uuid.UUID   `json:"id"`
	ModifierGroupID uuid.UUID   `json:"modifier_group_id"`
	Available       bool        `json:"available"`
	OptionRetired   interface{} `json:"option_retired"`
	GroupRetired    interface{} `json:"group_retired"`
}

func (q *Queries) ListModifierOptionsForValidation(ctx context.Context, optionIds []uuid.UUID) ([]ListModifierOptionsForValidationRow, error) {
	rows, err := q.db.QueryContext(ctx, listModifierOptionsForValidation, pq.Array(optionIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModifierOptionsForValidationRow{}
	for rows.Next() {
		var i ListModifierOptionsForValidationRow
		if err := rows.Scan(
			&i.ID,
			&i.ModifierGroupID,
			&i.Available,
			&i.OptionRetired,
			&i.GroupRetired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceSessionTables = `-- name: ListServiceSessionTables :many
SELECT t.id, t.name, a.sequence
FROM table_assignments a
JOIN tables t ON t.id = a.table_id
WHERE a.service_session_id = $1 AND a.released_at IS NULL
ORDER BY a.sequence ASC
`

type ListServiceSessionTablesRow struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Sequence int32     `json:"sequence"`
}

// Current assignments only. Released rows are history, not occupancy.
func (q *Queries) ListServiceSessionTables(ctx context.Context, serviceSessionID uuid.UUID) ([]ListServiceSessionTablesRow, error) {
	rows, err := q.db.QueryContext(ctx, listServiceSessionTables, serviceSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceSessionTablesRow{}
	for rows.Next() {
		var i ListServiceSessionTablesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Sequence); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionChecks = `-- name: ListSessionChecks :many
SELECT id, state, charge_vnd, created_at
FROM checks
WHERE service_session_id = $1
ORDER BY created_at ASC, id ASC
`

type ListSessionChecksRow struct {
	ID        uuid.UUID `json:"id"`
	State     string    `json:"state"`
	ChargeVnd int64     `json:"charge_vnd"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListSessionChecks(ctx context.Context, serviceSessionID uuid.UUID) ([]ListSessionChecksRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionChecks, serviceSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionChecksRow{}
	for rows.Next() {
		var i ListSessionChecksRow
		if err := rows.Scan(
			&i.ID,
			&i.State,
			&i.ChargeVnd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCurrentOpenCheck = `-- name: LockCurrentOpenCheck :one
SELECT id, charge_vnd
FROM checks
WHERE service_session_id = $1 AND state = 'OPEN'
ORDER BY created_at DESC, id DESC
LIMIT 1
FOR UPDATE
`

type LockCurrentOpenCheckRow struct {
	ID        uuid.UUID `json:"id"`
	ChargeVnd int64     `json:"charge_vnd"`
}

// The Session's most recent OPEN Check, for the CURRENT_UNPAID target.
func (q *Queries) LockCurrentOpenCheck(ctx context.Context, serviceSessionID uuid.UUID) (LockCurrentOpenCheckRow, error) {
	row := q.db.QueryRowContext(ctx, lockCurrentOpenCheck, serviceSessionID)
	var i LockCurrentOpenCheckRow
	err := row.Scan(&i.ID, &i.ChargeVnd)
	return i, err
}

const lockCurrentTableAssignments = `-- name: LockCurrentTableAssignments :many
SELECT id, table_id, sequence
FROM table_assignments
WHERE service_session_id = $1 AND released_at IS NULL
ORDER BY sequence ASC
FOR UPDATE
`

type LockCurrentTableAssignmentsRow struct {
	ID       uuid.UUID `json:"id"`
	TableID  uuid.UUID `json:"table_id"`
	Sequence int32     `json:"sequence"`
}

func (q *Queries) LockCurrentTableAssignments(ctx context.Context, serviceSessionID uuid.UUID) ([]LockCurrentTableAssignmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, lockCurrentTableAssignments, serviceSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockCurrentTableAssignmentsRow{}
	for rows.Next() {
		var i LockCurrentTableAssignmentsRow
		if err := rows.Scan(&i.ID, &i.TableID, &i.Sequence); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDraftItem = `-- name: LockDraftItem :one
SELECT id, order_draft_id, menu_item_id, size_id, quantity, preparation_note, modifier_key
FROM order_draft_items
WHERE id = $1 AND order_draft_id = $2
FOR UPDATE
`

type LockDraftItemParams struct {
	ID           uuid.UUID `json:"id"`
	OrderDraftID uuid.UUID `json:"order_draft_id"`
}

type LockDraftItemRow struct {
	ID              uuid.UUID      `json:"id"`
	OrderDraftID    uuid.UUID      `json:"order_draft_id"`
	MenuItemID      uuid.UUID      `json:"menu_item_id"`
	SizeID          uuid.NullUUID  `json:"size_id"`
	Quantity        int32          `json:"quantity"`
	PreparationNote sql.NullString `json:"preparation_note"`
	ModifierKey     string         `json:"modifier_key"`
}

// Scoped to the draft, so a caller cannot reach an item of another Session by
// guessing its id.
func (q *Queries) LockDraftItem(ctx context.Context, arg LockDraftItemParams) (LockDraftItemRow, error) {
	row := q.db.QueryRowContext(ctx, lockDraftItem, arg.ID, arg.OrderDraftID)
	var i LockDraftItemRow
	err := row.Scan(
		&i.ID,
		&i.OrderDraftID,
		&i.MenuItemID,
		&i.SizeID,
		&i.Quantity,
		&i.PreparationNote,
		&i.ModifierKey,
	)
	return i, err
}

const lockDraftItemsForCommit = `-- name: LockDraftItemsForCommit :many
SELECT di.id, di.menu_item_id, di.size_id, di.quantity, di.preparation_note,
       mi.name AS item_name, mi.price_vnd AS item_price_vnd,
       mi.available AS item_available,
       (mi.retired_at IS NOT NULL) AS item_retired,
       mc.name AS category_name
FROM order_draft_items di
JOIN menu_items mi ON mi.id = di.menu_item_id
JOIN menu_categories mc ON mc.id = mi.category_id
WHERE di.order_draft_id = $1
ORDER BY di.created_at ASC, di.id ASC
FOR UPDATE OF di
`

type LockDraftItemsForCommitRow struct {
	ID              uuid.UUID      `json:"id"`
	MenuItemID      uuid.UUID      `json:"menu_item_id"`
	SizeID          uuid.NullUUID  `json:"size_id"`
	Quantity        int32          `json:"quantity"`
	PreparationNote sql.NullString `json:"preparation_note"`
	ItemName        string         `json:"item_name"`
	ItemPriceVnd    sql.NullInt64  `json:"item_price_vnd"`
	ItemAvailable   bool           `json:"item_available"`
	ItemRetired     interface{}    `json:"item_retired"`
	CategoryName    string         `json:"category_name"`
}

// Every draft item with the Catalog facts Commit revalidates against, locked
// so the rows cannot change between validation and write. Ordered by
// (created_at, id), which also fixes the order of the Committed Items.
func (q *Queries) LockDraftItemsForCommit(ctx context.Context, orderDraftID uuid.UUID) ([]LockDraftItemsForCommitRow, error) {
	rows, err := q.db.QueryContext(ctx, lockDraftItemsForCommit, orderDraftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockDraftItemsForCommitRow{}
	for rows.Next() {
		var i LockDraftItemsForCommitRow
		if err := rows.Scan(
			&i.ID,
			&i.MenuItemID,
			&i.SizeID,
			&i.Quantity,
			&i.PreparationNote,
			&i.ItemName,
			&i.ItemPriceVnd,
			&i.ItemAvailable,
			&i.ItemRetired,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEditableDraft = `-- name: LockEditableDraft :one
SELECT d.id AS order_draft_id, s.id AS service_session_id, s.service_mode
FROM service_sessions s
JOIN order_drafts d ON d.service_session_id = s.id
JOIN sales_shifts sh ON sh.id = s.sales_shift_id
WHERE s.id = $1
  AND s.state = 'ACTIVE'
  AND d.state = 'EDITABLE'
  AND sh.state = 'OPEN'
FOR UPDATE OF d, s
`

type LockEditableDraftRow struct {
	OrderDraftID     uuid.UUID `json:"order_draft_id"`
	ServiceSessionID uuid.UUID `json:"service_session_id"`
	ServiceMode      string    `json:"service_mode"`
}

// Checks every precondition and takes the lock in one statement, so there is
// no window between the check and the write.
//
// No match means the Session is missing, closed, its draft already committed,
// or its Sales Shift closed. The caller reports EDITABLE_DRAFT_NOT_FOUND for
// all four: the remedy is the same, and distinguishing them would leak state
// about Sessions the caller did not ask about.
func (q *Queries) LockEditableDraft(ctx context.Context, id uuid.UUID) (LockEditableDraftRow, error) {
	row := q.db.QueryRowContext(ctx, lockEditableDraft, id)
	var i LockEditableDraftRow
	err := row.Scan(&i.OrderDraftID, &i.ServiceSessionID, &i.ServiceMode)
	return i, err
}

const lockMenuItemForDraft = `-- name: LockMenuItemForDraft :one
SELECT id, category_id, name, price_vnd, available, retired_at
FROM menu_items
WHERE id = $1
FOR UPDATE
`

type LockMenuItemForDraftRow struct {
	ID         uuid.UUID     `json:"id"`
	CategoryID uuid.UUID     `json:"category_id"`
	Name       string        `json:"name"`
	PriceVnd   sql.NullInt64 `json:"price_vnd"`
	Available  bool          `json:"available"`
	RetiredAt  sql.NullTime  `json:"retired_at"`
}

// Locked FOR UPDATE so the Item cannot be retired between validation and
// write. Sales rows are always locked before Catalog rows, and
// internal/catalog never locks Sales rows, so no deadlock cycle exists.
func (q *Queries) LockMenuItemForDraft(ctx context.Context, id uuid.UUID) (LockMenuItemForDraftRow, error) {
	row := q.db.QueryRowContext(ctx, lockMenuItemForDraft, id)
	var i LockMenuItemForDraftRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.PriceVnd,
		&i.Available,
		&i.RetiredAt,
	)
	return i, err
}

const lockMenuItemSizeForDraft = `-- name: LockMenuItemSizeForDraft :one
SELECT id, menu_item_id, name, price_vnd, available, retired_at
FROM menu_item_sizes
WHERE id = $1
FOR UPDATE
`

type LockMenuItemSizeForDraftRow struct {
	ID         uuid.UUID    `json:"id"`
	MenuItemID uuid.UUID    `json:"menu_item_id"`
	Name       string       `json:"name"`
	PriceVnd   int64        `json:"price_vnd"`
	Available  bool         `json:"available"`
	RetiredAt  sql.NullTime `json:"retired_at"`
}

// Locked FOR UPDATE for the same reason as LockMenuItemForDraft: without it, a
// concurrent retirement of this Size can slip between validation and the
// draft-item write.
func (q *Queries) LockMenuItemSizeForDraft(ctx context.Context, id uuid.UUID) (LockMenuItemSizeForDraftRow, error) {
	row := q.db.QueryRowContext(ctx, lockMenuItemSizeForDraft, id)
	var i LockMenuItemSizeForDraftRow
	err := row.Scan(
		&i.ID,
		&i.MenuItemID,
		&i.Name,
		&i.PriceVnd,
		&i.Available,
		&i.RetiredAt,
	)
	return i, err
}

const lockMenuItemSizesForCommit = `-- name: LockMenuItemSizesForCommit :many
SELECT id, menu_item_id, name, price_vnd, available,
       (retired_at IS NOT NULL) AS size_retired
FROM menu_item_sizes
WHERE id = ANY($1::uuid[])
ORDER BY id ASC
FOR SHARE
`

type LockMenuItemSizesForCommitRow struct {
	ID          uuid.UUID   `json:"id"`
	MenuItemID  uuid.UUID   `json:"menu_item_id"`
	Name        string      `json:"name"`
	PriceVnd    int64       `json:"price_vnd"`
	Available   bool        `json:"available"`
	SizeRetired interface{} `json:"size_retired"`
}

// Locked FOR SHARE: Commit only reads these rows and must merely prevent a
// retirement or availability change landing mid-transaction. FOR UPDATE would
// serialize two cashiers committing orders that share a popular item, on the
// busiest path in the system, for no correctness gain. internal/catalog's
// mutations take FOR UPDATE and are still excluded. See ADR-015.
func (q *Queries) LockMenuItemSizesForCommit(ctx context.Context, sizeIds []uuid.UUID) ([]LockMenuItemSizesForCommitRow, error) {
	rows, err := q.db.QueryContext(ctx, lockMenuItemSizesForCommit, pq.Array(sizeIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockMenuItemSizesForCommitRow{}
	for rows.Next() {
		var i LockMenuItemSizesForCommitRow
		if err := rows.Scan(
			&i.ID,
			&i.MenuItemID,
			&i.Name,
			&i.PriceVnd,
			&i.Available,
			&i.SizeRetired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockServiceSessionForUpdate = `-- name: LockServiceSessionForUpdate :one
SELECT id, service_mode, state, sales_shift_id
FROM service_sessions
WHERE id = $1
FOR UPDATE
`

type LockServiceSessionForUpdateRow struct {
	ID           uuid.UUID `json:"id"`
	ServiceMode  string    `json:"service_mode"`
	State        string    `json:"state"`
	SalesShiftID uuid.UUID `json:"sales_shift_id"`
}

func (q *Queries) LockServiceSessionForUpdate(ctx context.Context, id uuid.UUID) (LockServiceSessionForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, lockServiceSessionForUpdate, id)
	var i LockServiceSessionForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.ServiceMode,
		&i.State,
		&i.SalesShiftID,
	)
	return i, err
}

const lockTablesForAssignment = `-- name: LockTablesForAssignment :many
SELECT id, name, available
FROM tables
WHERE id = ANY($1::uuid[])
ORDER BY id ASC
FOR UPDATE
`

type LockTablesForAssignmentRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Available bool      `json:"available"`
}

// Locks the selected Tables in id order so two concurrent assignments over
// overlapping sets cannot deadlock against each other. The caller must sort
// the ids before calling.
func (q *Queries) LockTablesForAssignment(ctx context.Context, tableIds []uuid.UUID) ([]LockTablesForAssignmentRow, error) {
	rows, err := q.db.QueryContext(ctx, lockTablesForAssignment, pq.Array(tableIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockTablesForAssignmentRow{}
	for rows.Next() {
		var i LockTablesForAssignmentRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Available); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderDraftCommitted = `-- name: MarkOrderDraftCommitted :exec
UPDATE order_drafts SET state = 'COMMITTED' WHERE id = $1
`

func (q *Queries) MarkOrderDraftCommitted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markOrderDraftCommitted, id)
	return err
}

const raiseCheckCharge = `-- name: RaiseCheckCharge :exec
UPDATE checks SET charge_vnd = $2 WHERE id = $1
`

type RaiseCheckChargeParams struct {
	ID        uuid.UUID `json:"id"`
	ChargeVnd int64     `json:"charge_vnd"`
}

func (q *Queries) RaiseCheckCharge(ctx context.Context, arg RaiseCheckChargeParams) error {
	_, err := q.db.ExecContext(ctx, raiseCheckCharge, arg.ID, arg.ChargeVnd)
	return err
}

const releaseTableAssignment = `-- name: ReleaseTableAssignment :exec
UPDATE table_assignments
SET released_at = now(), released_by_staff_identity_id = $2
WHERE id = $1
`

type ReleaseTableAssignmentParams struct {
	ID                        uuid.UUID     `json:"id"`
	ReleasedByStaffIdentityID uuid.NullUUID `json:"released_by_staff_identity_id"`
}

// released_at and released_by_staff_identity_id must be set together; the
// table_assignment_release_evidence_valid constraint from migration 000006
// rejects one without the other.
func (q *Queries) ReleaseTableAssignment(ctx context.Context, arg ReleaseTableAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, releaseTableAssignment, arg.ID, arg.ReleasedByStaffIdentityID)
	return err
}

const salesAdvisoryLock = `-- name: SalesAdvisoryLock :exec
SELECT pg_advisory_xact_lock($1)
`

func (q *Queries) SalesAdvisoryLock(ctx context.Context, pgAdvisoryXactLock int64) error {
	_, err := q.db.ExecContext(ctx, salesAdvisoryLock, pgAdvisoryXactLock)
	return err
}

const setDraftItemQuantity = `-- name: SetDraftItemQuantity :one
UPDATE order_draft_items
SET quantity = $2
WHERE id = $1
RETURNING id, quantity
`

type SetDraftItemQuantityParams struct {
	ID       uuid.UUID `json:"id"`
	Quantity int32     `json:"quantity"`
}

type SetDraftItemQuantityRow struct {
	ID       uuid.UUID `json:"id"`
	Quantity int32     `json:"quantity"`
}

func (q *Queries) SetDraftItemQuantity(ctx context.Context, arg SetDraftItemQuantityParams) (SetDraftItemQuantityRow, error) {
	row := q.db.QueryRowContext(ctx, setDraftItemQuantity, arg.ID, arg.Quantity)
	var i SetDraftItemQuantityRow
	err := row.Scan(&i.ID, &i.Quantity)
	return i, err
}

const setOrderDraftCheckTarget = `-- name: SetOrderDraftCheckTarget :exec
UPDATE order_drafts SET check_target = $2 WHERE id = $1
`

type SetOrderDraftCheckTargetParams struct {
	ID          uuid.UUID `json:"id"`
	CheckTarget string    `json:"check_target"`
}

func (q *Queries) SetOrderDraftCheckTarget(ctx context.Context, arg SetOrderDraftCheckTargetParams) error {
	_, err := q.db.ExecContext(ctx, setOrderDraftCheckTarget, arg.ID, arg.CheckTarget)
	return err
}

const updateDraftItemComposition = `-- name: UpdateDraftItemComposition :exec
UPDATE order_draft_items
SET size_id = $2, preparation_note = $3, modifier_key = $4
WHERE id = $1
`

type UpdateDraftItemCompositionParams struct {
	ID              uuid.UUID      `json:"id"`
	SizeID          uuid.NullUUID  `json:"size_id"`
	PreparationNote sql.NullString `json:"preparation_note"`
	ModifierKey     string         `json:"modifier_key"`
}

// size_key and note_key are generated columns, so they follow the write.
func (q *Queries) UpdateDraftItemComposition(ctx context.Context, arg UpdateDraftItemCompositionParams) error {
	_, err := q.db.ExecContext(ctx, updateDraftItemComposition,
		arg.ID,
		arg.SizeID,
		arg.PreparationNote,
		arg.ModifierKey,
	)
	return err
}
