// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tables.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const claimIdempotencyRecord = `-- name: ClaimIdempotencyRecord :one
INSERT INTO idempotency_keys (key, actor_id, action, request_hash, response_code, response_body)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (actor_id, key) DO UPDATE
    SET response_code = idempotency_keys.response_code,
        response_body = idempotency_keys.response_body
RETURNING key, actor_id, action, request_hash, response_code, response_body, created_at
`

type ClaimIdempotencyRecordParams struct {
	Key          uuid.UUID       `json:"key"`
	ActorID      uuid.UUID       `json:"actor_id"`
	Action       string          `json:"action"`
	RequestHash  string          `json:"request_hash"`
	ResponseCode int32           `json:"response_code"`
	ResponseBody json.RawMessage `json:"response_body"`
}

func (q *Queries) ClaimIdempotencyRecord(ctx context.Context, arg ClaimIdempotencyRecordParams) (IdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, claimIdempotencyRecord,
		arg.Key,
		arg.ActorID,
		arg.Action,
		arg.RequestHash,
		arg.ResponseCode,
		arg.ResponseBody,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.ActorID,
		&i.Action,
		&i.RequestHash,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const createTable = `-- name: CreateTable :one

INSERT INTO tables (name, normalized_name)
VALUES ($1, $2)
RETURNING id, name, normalized_name, available, created_at, updated_at
`

type CreateTableParams struct {
	Name           string `json:"name"`
	NormalizedName string `json:"normalized_name"`
}

// -- Tables --
func (q *Queries) CreateTable(ctx context.Context, arg CreateTableParams) (Table, error) {
	row := q.db.QueryRowContext(ctx, createTable, arg.Name, arg.NormalizedName)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.Available,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdempotencyRecord = `-- name: GetIdempotencyRecord :one

SELECT key, actor_id, action, request_hash, response_code, response_body, created_at
FROM idempotency_keys
WHERE actor_id = $1 AND key = $2
LIMIT 1
`

type GetIdempotencyRecordParams struct {
	ActorID uuid.UUID `json:"actor_id"`
	Key     uuid.UUID `json:"key"`
}

// -- Shared idempotency (ADR-005) --
func (q *Queries) GetIdempotencyRecord(ctx context.Context, arg GetIdempotencyRecordParams) (IdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, getIdempotencyRecord, arg.ActorID, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.ActorID,
		&i.Action,
		&i.RequestHash,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const getTableForUpdate = `-- name: GetTableForUpdate :one
SELECT id, name, normalized_name, available, created_at, updated_at
FROM tables
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetTableForUpdate(ctx context.Context, id uuid.UUID) (Table, error) {
	row := q.db.QueryRowContext(ctx, getTableForUpdate, id)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.Available,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTablesSessionAuthority = `-- name: GetTablesSessionAuthority :one

SELECT s.id AS session_id, s.staff_identity_id, s.state, s.active_workspace,
       s.last_human_activity_at, s.expires_at, s.revoked_at,
       i.enabled AS identity_enabled, i.pin_hash
FROM staff_access_sessions s
JOIN staff_identities i ON i.id = s.staff_identity_id
WHERE s.id = $1 AND s.staff_identity_id = $2
`

type GetTablesSessionAuthorityParams struct {
	ID              uuid.UUID `json:"id"`
	StaffIdentityID uuid.UUID `json:"staff_identity_id"`
}

type GetTablesSessionAuthorityRow struct {
	SessionID           uuid.UUID      `json:"session_id"`
	StaffIdentityID     uuid.UUID      `json:"staff_identity_id"`
	State               string         `json:"state"`
	ActiveWorkspace     sql.NullString `json:"active_workspace"`
	LastHumanActivityAt time.Time      `json:"last_human_activity_at"`
	ExpiresAt           time.Time      `json:"expires_at"`
	RevokedAt           sql.NullTime   `json:"revoked_at"`
	IdentityEnabled     bool           `json:"identity_enabled"`
	PinHash             string         `json:"pin_hash"`
}

// -- Authority --
func (q *Queries) GetTablesSessionAuthority(ctx context.Context, arg GetTablesSessionAuthorityParams) (GetTablesSessionAuthorityRow, error) {
	row := q.db.QueryRowContext(ctx, getTablesSessionAuthority, arg.ID, arg.StaffIdentityID)
	var i GetTablesSessionAuthorityRow
	err := row.Scan(
		&i.SessionID,
		&i.StaffIdentityID,
		&i.State,
		&i.ActiveWorkspace,
		&i.LastHumanActivityAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.IdentityEnabled,
		&i.PinHash,
	)
	return i, err
}

const getTablesSessionRoles = `-- name: GetTablesSessionRoles :many
SELECT role
FROM staff_operational_roles
WHERE staff_identity_id = $1
ORDER BY role ASC
`

func (q *Queries) GetTablesSessionRoles(ctx context.Context, staffIdentityID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getTablesSessionRoles, staffIdentityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentTableOccupants = `-- name: ListCurrentTableOccupants :many

SELECT ta.table_id, ss.id AS service_session_id, ss.service_number
FROM table_assignments ta
JOIN service_sessions ss ON ss.id = ta.service_session_id
WHERE ta.released_at IS NULL AND ss.state = 'ACTIVE'
ORDER BY ta.assigned_at ASC, ta.id ASC
`

type ListCurrentTableOccupantsRow struct {
	TableID          uuid.UUID `json:"table_id"`
	ServiceSessionID uuid.UUID `json:"service_session_id"`
	ServiceNumber    string    `json:"service_number"`
}

// -- Occupancy (read-only view of Sales-owned tables) --
func (q *Queries) ListCurrentTableOccupants(ctx context.Context) ([]ListCurrentTableOccupantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCurrentTableOccupants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentTableOccupantsRow{}
	for rows.Next() {
		var i ListCurrentTableOccupantsRow
		if err := rows.Scan(&i.TableID, &i.ServiceSessionID, &i.ServiceNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTables = `-- name: ListTables :many
SELECT id, name, normalized_name, available, created_at, updated_at
FROM tables
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListTables(ctx context.Context) ([]Table, error) {
	rows, err := q.db.QueryContext(ctx, listTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Table{}
	for rows.Next() {
		var i Table
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NormalizedName,
			&i.Available,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameTable = `-- name: RenameTable :one
UPDATE tables
SET name = $2, normalized_name = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, normalized_name, available, created_at, updated_at
`

type RenameTableParams struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	NormalizedName string    `json:"normalized_name"`
}

func (q *Queries) RenameTable(ctx context.Context, arg RenameTableParams) (Table, error) {
	row := q.db.QueryRowContext(ctx, renameTable, arg.ID, arg.Name, arg.NormalizedName)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.Available,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setTableAvailability = `-- name: SetTableAvailability :one
UPDATE tables
SET available = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, normalized_name, available, created_at, updated_at
`

type SetTableAvailabilityParams struct {
	ID        uuid.UUID `json:"id"`
	Available bool      `json:"available"`
}

func (q *Queries) SetTableAvailability(ctx context.Context, arg SetTableAvailabilityParams) (Table, error) {
	row := q.db.QueryRowContext(ctx, setTableAvailability, arg.ID, arg.Available)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.Available,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const storeIdempotencyResult = `-- name: StoreIdempotencyResult :exec
UPDATE idempotency_keys
SET response_code = $3, response_body = $4
WHERE actor_id = $1 AND key = $2
`

type StoreIdempotencyResultParams struct {
	ActorID      uuid.UUID       `json:"actor_id"`
	Key          uuid.UUID       `json:"key"`
	ResponseCode int32           `json:"response_code"`
	ResponseBody json.RawMessage `json:"response_body"`
}

func (q *Queries) StoreIdempotencyResult(ctx context.Context, arg StoreIdempotencyResultParams) error {
	_, err := q.db.ExecContext(ctx, storeIdempotencyResult,
		arg.ActorID,
		arg.Key,
		arg.ResponseCode,
		arg.ResponseBody,
	)
	return err
}

const tablesAdvisoryLock = `-- name: TablesAdvisoryLock :exec
SELECT pg_advisory_xact_lock($1)
`

func (q *Queries) TablesAdvisoryLock(ctx context.Context, pgAdvisoryXactLock int64) error {
	_, err := q.db.ExecContext(ctx, tablesAdvisoryLock, pgAdvisoryXactLock)
	return err
}
