// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tables.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createTable = `-- name: CreateTable :one

INSERT INTO tables (name, normalized_name)
VALUES ($1, $2)
RETURNING id, name, normalized_name, available, created_at, updated_at
`

type CreateTableParams struct {
	Name           string `json:"name"`
	NormalizedName string `json:"normalized_name"`
}

// -- Tables --
func (q *Queries) CreateTable(ctx context.Context, arg CreateTableParams) (Table, error) {
	row := q.db.QueryRowContext(ctx, createTable, arg.Name, arg.NormalizedName)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.Available,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTableForUpdate = `-- name: GetTableForUpdate :one
SELECT id, name, normalized_name, available, created_at, updated_at
FROM tables
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetTableForUpdate(ctx context.Context, id uuid.UUID) (Table, error) {
	row := q.db.QueryRowContext(ctx, getTableForUpdate, id)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.Available,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCurrentTableOccupants = `-- name: ListCurrentTableOccupants :many

SELECT ta.table_id, ss.id AS service_session_id, ss.service_number
FROM table_assignments ta
JOIN service_sessions ss ON ss.id = ta.service_session_id
WHERE ta.released_at IS NULL AND ss.state = 'ACTIVE'
ORDER BY ta.assigned_at ASC, ta.id ASC
`

type ListCurrentTableOccupantsRow struct {
	TableID          uuid.UUID `json:"table_id"`
	ServiceSessionID uuid.UUID `json:"service_session_id"`
	ServiceNumber    string    `json:"service_number"`
}

// -- Occupancy (read-only view of Sales-owned tables) --
func (q *Queries) ListCurrentTableOccupants(ctx context.Context) ([]ListCurrentTableOccupantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCurrentTableOccupants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentTableOccupantsRow{}
	for rows.Next() {
		var i ListCurrentTableOccupantsRow
		if err := rows.Scan(&i.TableID, &i.ServiceSessionID, &i.ServiceNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTables = `-- name: ListTables :many
SELECT id, name, normalized_name, available, created_at, updated_at
FROM tables
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListTables(ctx context.Context) ([]Table, error) {
	rows, err := q.db.QueryContext(ctx, listTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Table{}
	for rows.Next() {
		var i Table
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NormalizedName,
			&i.Available,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameTable = `-- name: RenameTable :one
UPDATE tables
SET name = $2, normalized_name = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, normalized_name, available, created_at, updated_at
`

type RenameTableParams struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	NormalizedName string    `json:"normalized_name"`
}

func (q *Queries) RenameTable(ctx context.Context, arg RenameTableParams) (Table, error) {
	row := q.db.QueryRowContext(ctx, renameTable, arg.ID, arg.Name, arg.NormalizedName)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.Available,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setTableAvailability = `-- name: SetTableAvailability :one
UPDATE tables
SET available = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, normalized_name, available, created_at, updated_at
`

type SetTableAvailabilityParams struct {
	ID        uuid.UUID `json:"id"`
	Available bool      `json:"available"`
}

func (q *Queries) SetTableAvailability(ctx context.Context, arg SetTableAvailabilityParams) (Table, error) {
	row := q.db.QueryRowContext(ctx, setTableAvailability, arg.ID, arg.Available)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.Available,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
