/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppKdsRouteImport } from './routes/_app/kds'
import { Route as AppManageRouteImport } from './routes/_app/manage'
import { Route as AppNoAccessRouteImport } from './routes/_app/no-access'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppShiftRouteImport } from './routes/_app/shift'
import { Route as AppTablesRouteImport } from './routes/_app/tables'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthWorkspaceRouteImport } from './routes/auth/workspace'
import { Route as AppManageIndexRouteImport } from './routes/_app/manage/index'
import { Route as AppManageAvailabilityRouteImport } from './routes/_app/manage/availability'
import { Route as AppManageCatalogRouteImport } from './routes/_app/manage/catalog'
import { Route as AppManageStaffRouteImport } from './routes/_app/manage/staff'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppKdsRoute = AppKdsRouteImport.update({
  id: '/kds',
  path: '/kds',
  getParentRoute: () => AppRoute,
} as any)
const AppManageRoute = AppManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AppRoute,
} as any)
const AppNoAccessRoute = AppNoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppShiftRoute = AppShiftRouteImport.update({
  id: '/shift',
  path: '/shift',
  getParentRoute: () => AppRoute,
} as any)
const AppTablesRoute = AppTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWorkspaceRoute = AuthWorkspaceRouteImport.update({
  id: '/auth/workspace',
  path: '/auth/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AppManageIndexRoute = AppManageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppManageRoute,
} as any)
const AppManageAvailabilityRoute = AppManageAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => AppManageRoute,
} as any)
const AppManageCatalogRoute = AppManageCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppManageRoute,
} as any)
const AppManageStaffRoute = AppManageStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppManageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/history': typeof AppHistoryRoute
  '/kds': typeof AppKdsRoute
  '/manage': typeof AppManageRouteWithChildren
  '/no-access': typeof AppNoAccessRoute
  '/settings': typeof AppSettingsRoute
  '/shift': typeof AppShiftRoute
  '/tables': typeof AppTablesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/workspace': typeof AuthWorkspaceRoute
  '/manage/availability': typeof AppManageAvailabilityRoute
  '/manage/catalog': typeof AppManageCatalogRoute
  '/manage/staff': typeof AppManageStaffRoute
  '/manage/': typeof AppManageIndexRoute
}
export interface FileRoutesByTo {
  '/history': typeof AppHistoryRoute
  '/kds': typeof AppKdsRoute
  '/no-access': typeof AppNoAccessRoute
  '/settings': typeof AppSettingsRoute
  '/shift': typeof AppShiftRoute
  '/tables': typeof AppTablesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/workspace': typeof AuthWorkspaceRoute
  '/': typeof AppIndexRoute
  '/manage/availability': typeof AppManageAvailabilityRoute
  '/manage/catalog': typeof AppManageCatalogRoute
  '/manage/staff': typeof AppManageStaffRoute
  '/manage': typeof AppManageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/history': typeof AppHistoryRoute
  '/_app/kds': typeof AppKdsRoute
  '/_app/manage': typeof AppManageRouteWithChildren
  '/_app/no-access': typeof AppNoAccessRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/shift': typeof AppShiftRoute
  '/_app/tables': typeof AppTablesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/workspace': typeof AuthWorkspaceRoute
  '/_app/': typeof AppIndexRoute
  '/_app/manage/availability': typeof AppManageAvailabilityRoute
  '/_app/manage/catalog': typeof AppManageCatalogRoute
  '/_app/manage/staff': typeof AppManageStaffRoute
  '/_app/manage/': typeof AppManageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/kds'
    | '/manage'
    | '/no-access'
    | '/settings'
    | '/shift'
    | '/tables'
    | '/auth/login'
    | '/auth/workspace'
    | '/manage/availability'
    | '/manage/catalog'
    | '/manage/staff'
    | '/manage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/history'
    | '/kds'
    | '/no-access'
    | '/settings'
    | '/shift'
    | '/tables'
    | '/auth/login'
    | '/auth/workspace'
    | '/'
    | '/manage/availability'
    | '/manage/catalog'
    | '/manage/staff'
    | '/manage'
  id:
    | '__root__'
    | '/_app'
    | '/_app/history'
    | '/_app/kds'
    | '/_app/manage'
    | '/_app/no-access'
    | '/_app/settings'
    | '/_app/shift'
    | '/_app/tables'
    | '/auth/login'
    | '/auth/workspace'
    | '/_app/'
    | '/_app/manage/availability'
    | '/_app/manage/catalog'
    | '/_app/manage/staff'
    | '/_app/manage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthWorkspaceRoute: typeof AuthWorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kds': {
      id: '/_app/kds'
      path: '/kds'
      fullPath: '/kds'
      preLoaderRoute: typeof AppKdsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manage': {
      id: '/_app/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof AppManageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/no-access': {
      id: '/_app/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof AppNoAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shift': {
      id: '/_app/shift'
      path: '/shift'
      fullPath: '/shift'
      preLoaderRoute: typeof AppShiftRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tables': {
      id: '/_app/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof AppTablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/workspace': {
      id: '/auth/workspace'
      path: '/auth/workspace'
      fullPath: '/auth/workspace'
      preLoaderRoute: typeof AuthWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/manage/': {
      id: '/_app/manage/'
      path: '/'
      fullPath: '/manage/'
      preLoaderRoute: typeof AppManageIndexRouteImport
      parentRoute: typeof AppManageRoute
    }
    '/_app/manage/availability': {
      id: '/_app/manage/availability'
      path: '/availability'
      fullPath: '/manage/availability'
      preLoaderRoute: typeof AppManageAvailabilityRouteImport
      parentRoute: typeof AppManageRoute
    }
    '/_app/manage/catalog': {
      id: '/_app/manage/catalog'
      path: '/catalog'
      fullPath: '/manage/catalog'
      preLoaderRoute: typeof AppManageCatalogRouteImport
      parentRoute: typeof AppManageRoute
    }
    '/_app/manage/staff': {
      id: '/_app/manage/staff'
      path: '/staff'
      fullPath: '/manage/staff'
      preLoaderRoute: typeof AppManageStaffRouteImport
      parentRoute: typeof AppManageRoute
    }
  }
}

interface AppManageRouteChildren {
  AppManageAvailabilityRoute: typeof AppManageAvailabilityRoute
  AppManageCatalogRoute: typeof AppManageCatalogRoute
  AppManageStaffRoute: typeof AppManageStaffRoute
  AppManageIndexRoute: typeof AppManageIndexRoute
}

const AppManageRouteChildren: AppManageRouteChildren = {
  AppManageAvailabilityRoute: AppManageAvailabilityRoute,
  AppManageCatalogRoute: AppManageCatalogRoute,
  AppManageStaffRoute: AppManageStaffRoute,
  AppManageIndexRoute: AppManageIndexRoute,
}

const AppManageRouteWithChildren = AppManageRoute._addFileChildren(
  AppManageRouteChildren,
)

interface AppRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppKdsRoute: typeof AppKdsRoute
  AppManageRoute: typeof AppManageRouteWithChildren
  AppNoAccessRoute: typeof AppNoAccessRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShiftRoute: typeof AppShiftRoute
  AppTablesRoute: typeof AppTablesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppKdsRoute: AppKdsRoute,
  AppManageRoute: AppManageRouteWithChildren,
  AppNoAccessRoute: AppNoAccessRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShiftRoute: AppShiftRoute,
  AppTablesRoute: AppTablesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthWorkspaceRoute: AuthWorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
