/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppKdsRouteImport } from './routes/_app/kds'
import { Route as AppNoAccessRouteImport } from './routes/_app/no-access'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppShiftRouteImport } from './routes/_app/shift'
import { Route as AppTablesRouteImport } from './routes/_app/tables'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthWorkspaceRouteImport } from './routes/auth/workspace'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsAvailabilityRouteImport } from './routes/_app/settings/availability'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppKdsRoute = AppKdsRouteImport.update({
  id: '/kds',
  path: '/kds',
  getParentRoute: () => AppRoute,
} as any)
const AppNoAccessRoute = AppNoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppShiftRoute = AppShiftRouteImport.update({
  id: '/shift',
  path: '/shift',
  getParentRoute: () => AppRoute,
} as any)
const AppTablesRoute = AppTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWorkspaceRoute = AuthWorkspaceRouteImport.update({
  id: '/auth/workspace',
  path: '/auth/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAvailabilityRoute = AppSettingsAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => AppSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/history': typeof AppHistoryRoute
  '/kds': typeof AppKdsRoute
  '/no-access': typeof AppNoAccessRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/shift': typeof AppShiftRoute
  '/tables': typeof AppTablesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/workspace': typeof AuthWorkspaceRoute
  '/settings/availability': typeof AppSettingsAvailabilityRoute
  '/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/history': typeof AppHistoryRoute
  '/kds': typeof AppKdsRoute
  '/no-access': typeof AppNoAccessRoute
  '/shift': typeof AppShiftRoute
  '/tables': typeof AppTablesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/workspace': typeof AuthWorkspaceRoute
  '/': typeof AppIndexRoute
  '/settings/availability': typeof AppSettingsAvailabilityRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/history': typeof AppHistoryRoute
  '/_app/kds': typeof AppKdsRoute
  '/_app/no-access': typeof AppNoAccessRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/shift': typeof AppShiftRoute
  '/_app/tables': typeof AppTablesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/workspace': typeof AuthWorkspaceRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/availability': typeof AppSettingsAvailabilityRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/kds'
    | '/no-access'
    | '/settings'
    | '/shift'
    | '/tables'
    | '/auth/login'
    | '/auth/workspace'
    | '/settings/availability'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/history'
    | '/kds'
    | '/no-access'
    | '/shift'
    | '/tables'
    | '/auth/login'
    | '/auth/workspace'
    | '/'
    | '/settings/availability'
    | '/settings'
  id:
    | '__root__'
    | '/_app'
    | '/_app/history'
    | '/_app/kds'
    | '/_app/no-access'
    | '/_app/settings'
    | '/_app/shift'
    | '/_app/tables'
    | '/auth/login'
    | '/auth/workspace'
    | '/_app/'
    | '/_app/settings/availability'
    | '/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthWorkspaceRoute: typeof AuthWorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kds': {
      id: '/_app/kds'
      path: '/kds'
      fullPath: '/kds'
      preLoaderRoute: typeof AppKdsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/no-access': {
      id: '/_app/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof AppNoAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shift': {
      id: '/_app/shift'
      path: '/shift'
      fullPath: '/shift'
      preLoaderRoute: typeof AppShiftRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tables': {
      id: '/_app/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof AppTablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/workspace': {
      id: '/auth/workspace'
      path: '/auth/workspace'
      fullPath: '/auth/workspace'
      preLoaderRoute: typeof AuthWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/availability': {
      id: '/_app/settings/availability'
      path: '/availability'
      fullPath: '/settings/availability'
      preLoaderRoute: typeof AppSettingsAvailabilityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAvailabilityRoute: typeof AppSettingsAvailabilityRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAvailabilityRoute: AppSettingsAvailabilityRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppKdsRoute: typeof AppKdsRoute
  AppNoAccessRoute: typeof AppNoAccessRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppShiftRoute: typeof AppShiftRoute
  AppTablesRoute: typeof AppTablesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppKdsRoute: AppKdsRoute,
  AppNoAccessRoute: AppNoAccessRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppShiftRoute: AppShiftRoute,
  AppTablesRoute: AppTablesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthWorkspaceRoute: AuthWorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
